### ISSUE TITLE
Zom crashes after not using it for a while.

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#100]
I was on Zom on iTouch OS 9.3.1 and it was working fine. I then left it for about 15 mins (checked an email in between). When I opened Zom again, it crashed. The first time it crashed, it said I need to sign in and then every attempt after that to open Zom, it crashed without any warning. I did not sign out of my account.

**Comment by n8fr8** [comment]
Please let us know if this improves with the latest build.
