### ISSUE TITLE
onboarding meta ticket

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#103]
This is a big parent ticket for the following issues for iOS onboarding:

- Account will auto-generate regardless of what user name is entered (same as Zom Android).... This is the "tenzin" problem, as we have discussed at length
- User will select a nickname for auto-generated account. This nickname will be user’s handle in chats / invite share links etc.
- When you click enter it should create the account instead of check mark in top righthand corner... right now you have to enter the name you want, then tap the checkmark, instead of just hitting enter on the keyboard
- Ability for user to see their autogenerated password and screenshot of where user can find password

**Comment by n8fr8** [comment]
Did the account generation new code not get integrated into the last build? It still seems to have the "tenzin problem" from what I tested.

**Comment by gekhung** [comment]
Same here. It is showing the error.

**Comment by N-Pex** [comment]
No, it seems the PR had not been accepted yet when I did the build. It'll be there in the next!

**Comment by n8fr8** [comment]
I was just happy with unique ness for now. If we can make it 8 and add a . (dot) character between the name and the random ending, that would all be great as a nice to have.

**Comment by n8fr8** [comment]
Everyone happy with this.
