### ISSUE TITLE
microphone/share UI should be disabled, not appear/disappear

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#109]
Microphone and “+” menu bar should appear right away when you enter chat screen

**Comment by cstiens** [comment]
Done! @N-Pex This issue can be closed.

**Comment by n8fr8** [comment]
I agree this is working, but there is some glitchiness with the mic button. It doesn't open the audio recording feature, and instead shows the general media attachment UI. Should we open a bug ticket for that separately?

**Comment by N-Pex** [comment]
Yes, there is issue #207 for this, closing this ticket.
