### ISSUE TITLE
new message notification if you aren't currently in chat

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#110]
right now notification seem to only show if you are not in the app itself. if you are in another chat, and you get a message, you won't see a notification of it, and might miss it.

" coming through when you’re in the app but not on the current contacts screen. "

**Comment by n8fr8** [comment]
possibly use a toast, or in-app notification of some sort

**Comment by n8fr8** [comment]
http://stackoverflow.com/questions/14872088/get-push-notification-while-app-in-foreground-ios

**Comment by n8fr8** [comment]
https://github.com/avielg/AGPushNote

**Comment by davidchiles** [comment]
Looks like this is a feature available in iOS 10. https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate 

Could be related to a larger notification changes like interactive notifications.

**Comment by chrisballinger** [comment]
* 85% of existing Zom users have iOS 10 (from iTunes Connect analytics)
* 82% of existing ChatSecure users have iOS 10 (from iTunes Connect analytics)
* 82% of global users have iOS 10: https://mixpanel.com/trends/#report/ios_10

**Comment by cstiens** [comment]
Working!
