### ISSUE TITLE
make the sticker selector more like Android

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#113]
tabs, with swiping between sticker sets possible?

**Comment by N-Pex** [comment]
Is this ok?

**Comment by n8fr8** [comment]
Is there supported to be a screen shot?

**Comment by N-Pex** [comment]
![simulator screen shot 26 maj 2016 22 57 28](https://cloud.githubusercontent.com/assets/5418622/15589949/6e68340e-2395-11e6-9987-60d22239cfe6.png)

Still shows up full screen, but you can now swipe left/right to switch set (the title is updated). Uses standard "dots" to show how many sets there are.

**Comment by n8fr8** [comment]
Super!

**Comment by n8fr8** [comment]
Is there some other indicator that the user can swipe? The dots are really subtle and I am worried they will miss the others that are available.

**Comment by N-Pex** [comment]
Currently no. Maybe we should append something to the title, like "Topgyal [4/5]" or similar?

**Comment by n8fr8** [comment]
what about putting the swipe indicator at the top, or using a brighter color for the selected dot?

**Comment by N-Pex** [comment]
Moving the indicator to the top is kind of hacky, but we can change color. Like this?

![simulator screen shot 3 juni 2016 09 31 19](https://cloud.githubusercontent.com/assets/5418622/15771882/fc4b2050-296d-11e6-922d-0bdd71a3cb50.png)

**Comment by n8fr8** [comment]
Great!
