### ISSUE TITLE
add support for sticker short codes/aliases

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#114]
instead of sending sticker graphics, support sending the sticker-id, like android zom currently does

"Sticker Short Codes in IOS for sending stickers in groups as well as Chats."

**Comment by n8fr8** [comment]
I will post the info I have on how we are identifying stickers on the android side

**Comment by n8fr8** [comment]
/sticker:<folder>/<file>  is what we use on android currently

/sticker:stickers/losar/goodnight.png

which is pretty ugly, but works. let me think of something better.

**Comment by n8fr8** [comment]
what about :(packname)-(filename without extension):
so :losar-goodnight:

**Comment by n8fr8** [comment]
i think that works... the question is do we want to clean up the sticker filenames now or no?
ultimately, we need a nice JSON file descriptor that loads with each sticker pack etc etc, but thats not for now

**Comment by N-Pex** [comment]
@n8fr8 Ok, I implemented this for incoming messages, so that sending ":losar-goodnight:" from my Android device to my iOS device now works. What are the criteria for sending? Should it always send short codes? Also, sending a sticker (as opposed to typing the text ":losar-goodnight:") from my Android seemed to still send it as an image (beta-8)

**Comment by n8fr8** [comment]
@N-Pex i think we should always send short codes for now. we can maybe figure out a way to know it is a Zom client we are talking to in the future, and then use short codes then. Android uses the short codes in group chat now, but still photos in one-to-one. I will change that.

**Comment by n8fr8** [comment]
are all of your sticker codes lowercase? do they map to the file names?

**Comment by N-Pex** [comment]
I actually wrote some custom code to match them, so it accepts any case, like ":Losar:goodNIghT:". If it can't find the sticker it shows the text verbatim.

**Comment by n8fr8** [comment]
great

**Comment by N-Pex** [comment]
Ok, think I got this one down, looking forward to testing Android<->iOS! =)

**Comment by n8fr8** [comment]
It works... well mostly. I have to normalize the codes on my side, but yeah, looking good!
