### ISSUE TITLE
 Onboarding - Update splash graphic

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#116]
Use Android page layout >>>

(wrong graphic)

**Comment by n8fr8** [comment]
![onboarding_main](https://cloud.githubusercontent.com/assets/30851/15712527/99288ea6-27e0-11e6-8e3b-f1ce19b885e2.png)

Use this instead of the one with the "Free Text @ Voice..." header in it

**Comment by N-Pex** [comment]
I just removed the text, it was not part of the image.

About the image above, that's not an iPhone screen, so Apple won't like it...

**Comment by gekhung** [comment]
Will share the iPhone screen today.

**Comment by n8fr8** [comment]
Oh right. Argh. We have the iPhone screen version. Are you saying that you used the same graphic and just removed the text? I was confused what was text and what was in the image.

**Comment by N-Pex** [comment]
The text was not part of the image, so I just removed the text but still use the old image. That one is wrong however, if nothing else because it contains the old lock icon (and other "messages" in the screen shot)

**Comment by n8fr8** [comment]
okay. will try to get an updated screenshot, but for now, sounds good.

**Comment by gekhung** [comment]
I noticed the locks too. We will replace the lock on top right with info icon and locks under chats with shield. The chat content will also be replaced by that in Android version.

I did not get confirmation yet on when this will be delivered, but I am expecting by noon tomorrow.

**Comment by N-Pex** [comment]
@gekhung Any update on this?

**Comment by gekhung** [comment]
I have shared this with @n8fr8
