### ISSUE TITLE
update stickers to latest designs

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#124]
Zomkyi stickers need to be updated (updated designs should already be in GitHub design folder)

**Comment by N-Pex** [comment]
@n8fr8 I updated from Zom-Assets/Stickers, but the Zomkyi were not updated(?). However, I added Tiboji and some Losar stickers.

**Comment by n8fr8** [comment]
I will update the Zomkyi stickers today. Thought I had done that!

**Comment by n8fr8** [comment]
New stickers posted: https://github.com/zom/Zom-Assets/tree/master/stickers/zomkyi
