### ISSUE TITLE
Remove ChatSecure texts, links, mentions

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#129]
We want to leave the basic "about" info (based on ChatSecure, etc) , but need to remove UserVoice link and settings mention of ChatSecure, and replace with Zom.

Just want to avoid confusion with the user.

**Comment by N-Pex** [comment]
Unsure exactly all that this issue contains, but now I've removed the feedback and donation links and changed ChatSecure to Zom in the English language files (need to do this for ALL languages I guess, with a script).

Anything else I am missing? =)
