### ISSUE TITLE
UI Audio Glitch

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#130]
Using iPhone 4S with iOS 8.4 - When I use audio, the first one sends without really being given an opportunity to say anything. Before you know what is going on the audio has sent. UI glitch?

**Comment by n8fr8** [comment]
This seems to be related to a tapping the mic quickly under 1s and sending empty audio, perhaps when it prompts you the first time to enable mic permissions?

**Comment by davidchiles** [comment]
I can take a look at this today.

**Comment by davidchiles** [comment]
https://github.com/ChatSecure/ChatSecure-iOS/commit/f65b64ee5f95a5ff820bc90f754bd9bf9dde9c81 Should stop really short recordings from being sent. I set it at 0.5 seconds for now.

**Comment by cstiens** [comment]
@davidchiles This appears to be fixed. When I tap the microphone quickly (under 1s) an empty audio message is not sent. Any more work to do here?
