### ISSUE TITLE
Adding friend (scanning) takes back to Enable push option page.

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#135]
I scanned QR Code of Zom on Android with my iOS device (iTouch: 9.3.1). Once the QR code was captured, it instantly took me back to Enable Push page. I noticed that the contact is added in the friend list.

**Comment by n8fr8** [comment]
The general issue with this is the confusion of flow after you scan a QR Code or open a link

**Comment by n8fr8** [comment]
We don't have this anymore in the onboarding...  add friend is in the main screen now, so it won' tback pu to enable push.

**Comment by n8fr8** [comment]
After you scan QR Code or open link, it should show the friend list, while waiting for confirmation.

**Comment by cstiens** [comment]
@N-Pex  When I tested this, after scanning a QR code, it took me to an open conversation with the person I scanned. It should show the friend list instead.

**Comment by N-Pex** [comment]
@cstiens I know there has been some talk about his. But I agree, since we are probably "waiting for confirmation", maybe the friend list is better. @n8fr8 What do you think?

**Comment by n8fr8** [comment]
Yes, show the friend list. Thanks!

**Comment by cstiens** [comment]
@N-Pex In version 52, after I add a friend, it takes me to the friend list for less than a second, then automatically into a chat with the person I added (I didn't tap anything). It should stay on the friend list until the user takes an action.

**Comment by cstiens** [comment]
@N-Pex I'm testing this in version 53, and the scroll is great! The 'sms' text and icon are larger than the other 2, causing the word to get clipped. See screenshot

![img_0027](https://cloud.githubusercontent.com/assets/1434597/21155164/9a5cc522-c136-11e6-8e60-90a9f493a279.PNG)
