### ISSUE TITLE
push reliability

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#141]
Gist here with logs from zom-push server:
https://gist.github.com/n8fr8/e06b4414e94f85b0ef2dd30defa1432a

**Comment by n8fr8** [comment]
I have started with a clean Zom Android setup now, and it seems like we are never receiving the tokens via the TLV from the latest Zom iOS. the latest ChatSecure iOS is fine.

**Comment by chrisballinger** [comment]
It does show that a push was sent successfully to Apple at the very end of
the log, but that doesn't guarantee that it is delivered in a timely manner
(or at all) once it's in Apple's hands.

**Comment by n8fr8** [comment]
But it seems like there were many HTTP request to zom-push, but only one push to APNS?

**Comment by chrisballinger** [comment]
`/api/v1/messages` is the only API call that triggers a push. The rest of the requests are coming from the iOS client trying to fetch tokens. What's concerning is that we changed the behavior to only fetch 5 tokens at a time, and only send out 1 fresh token per new OTR session, so I'm not sure what the Zom iOS client is doing. Perhaps it is having trouble storing the tokens.

FYI: The server will invalidate old tokens after 60 days, but you would see a 404 in the log when hitting the `/messages` endpoint. When receiving tokens the Android client should make sure to store the expiration date (it's in the TLV JSON), purge expired tokens, and always use the freshest/newest token.

**Comment by n8fr8** [comment]
okay will double check that. as i said, right now, we aren't getting any tokens at all from Zom iOS in the TLV exchange. something is not getting initiated properly.

**Comment by n8fr8** [comment]
(or maybe Zom iOS is not getting tokens to share, which is why it keeps pinging?)

**Comment by n8fr8** [comment]
@N-Pex looping you in

**Comment by chrisballinger** [comment]
One possibility is that we recently updated the iOS SDK to store the expiration date from the server, and the current Zom push server isn't giving out the expected fields. Another possibility is that when serializing the token for the TLV, the expiration date field isn't found, causing the entire serialization to fail.

**Comment by n8fr8** [comment]
ah that sounds like we are on to something....

**Comment by n8fr8** [comment]
This issue is now being addressed in ticket #145 related to device ID format issues
