### ISSUE TITLE
Group Appear Twice in Chat

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#153]
Group is showing up twice - showing up as a group chat and as a chat from a contact. One with actual group name and the other one (same group) with a long name.

**Comment by davidchiles** [comment]
Temporary fix here https://github.com/ChatSecure/XMPPFramework/commit/d3f9ee1200eb8b66f9660de01068c330a8e96b81

**Comment by cstiens** [comment]
@davidchiles Do we need to keep this ticket open? Is there more work to do? In the UI now, it only appears once, but I see that you've made a 'temporary fix'.

**Comment by cstiens** [comment]
Thank you Chris!!!
