### ISSUE TITLE
Group chat has the lock

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#156]
group chat is still using lock icon instead of shield.

**Comment by chrisballinger** [comment]
There should be no lock or shield at all on group chats because they are not end-to-end encrypted.

**Comment by gekhung** [comment]
![img_0007](https://cloud.githubusercontent.com/assets/11950115/16013462/7eb998d8-315b-11e6-99a6-f006fcf846ee.PNG)

**Comment by gekhung** [comment]
The group chat also had the initiate encryption option:

https://cloud.githubusercontent.com/assets/11950115/15943163/b050ef1c-2e55-11e6-8a4e-ceee1c5bdbcc.PNG
