### ISSUE TITLE
Moving sticker to top in Media sharing option

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#157]
Move Sticker to top of option list (when you click on camera icon)

**Comment by n8fr8** [comment]
Can we remove video as an option?

**Comment by cstiens** [comment]
The video option has been removed. @N-Pex Do you know what the 'move sticker to top of option list' means?

**Comment by N-Pex** [comment]
@cstiens We used to have a normal "action sheet" for the attachment picker, but this has now changed to the circular buttons, like on Android, so this ticket is no longer valid.
