### ISSUE TITLE
Tibetan characters/usernames in onboarding causes crash

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#159]
- enable tibetan keyboard
- type tibetan letters into username box in onboarding
- crash?

solution: replace/remove tibetan characters with allowed ascii chars

**Comment by n8fr8** [comment]
While it seems like the spec should support unicode, it seems like the server or xmpp lib on iOS may not?

**Comment by n8fr8** [comment]
1) use regex to remove all NON alpha numeric chars
2) if there are no chars left in the string, then replace with "zomuser"
3) store original entered user value as a nickname/display name in local data method
4) on login, send vcard with the user entered value as the nickname

**Comment by n8fr8** [comment]
here is the regex we use on Android "[^A-Za-z0-9]";

**Comment by davidchiles** [comment]
Thanks for the regex 😄 

https://github.com/ChatSecure/ChatSecure-iOS/pull/520

**Comment by N-Pex** [comment]
@davidchiles The main logic here seems to work fine, but for some reason it (re)tries the old jid as well? I attached a longer desription to the ChatSecure issue.

**Comment by N-Pex** [comment]
Oh, scratch that. I think this is caused by my fix for "Enter means go". I'll have another look.

**Comment by n8fr8** [comment]
Does this include the vcard sending support? Couldn't get that to work
in my tests if so.

**Comment by davidchiles** [comment]
@n8fr8 vcard-temp work is going on here https://github.com/ChatSecure/ChatSecure-iOS/pull/523.

https://github.com/ChatSecure/ChatSecure-iOS/pull/520 just covers errors from XMPP servers where it rejects the JID for a policy violation, like non-english characters.
