### ISSUE TITLE
Messages Not Visible

### ISSUE THREAD

**Issue by cwmke** [zom/Zom-iOS#162]
When sending or receiving messages on an iPad, the area where they normally appear shows nothing but the messages are still sent. 

Also, after adding the text to send and pressing send, the text remains in the input field where it can continually be sent.

This began after the latest update. I reinstalled the app to see if that would help but there was no difference.

This is without otr enabled.

Thanks for any help.

**Comment by n8fr8** [comment]
Hmm, thanks! Will test on iPad here and see. Is this full iPad or iPad mini? What screen size?

**Comment by cwmke** [comment]
Sorry about that!  Full size, I'm not sure the screen size but it's model MGKL2LL/A running version 9.3.2.
