### ISSUE TITLE
Removing 'Stop Encryption' from (i) info button in chat.

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#173]
Interim fix to avoid user confusion.

**Comment by n8fr8** [comment]
The (i) menu is confusing, and as we replace with the profile view potentially, we need to make sure we have consitency on manual key verificaiton.

**Comment by cstiens** [comment]
This issue is accounted for in issue 169. 
https://github.com/zom/Zom-iOS/issues/169
