### ISSUE TITLE
User should not be able to send a message until a contact has approved them

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#176]
Interim fix is to add a pending option
- needed until omemo protocol is integrated and stable because right now it’s inconsistent when a user receives friend confirmation message

**Comment by cstiens** [comment]
A user should not be able to send a message to a contact until that contact has approved them. If that contact has scanned the user's QR code, that is equivalent to approving someone. 

Currently, in Chatsecure, I cannot send a message until my contact approves me. However, in Zom, I can. It should function like Chatsecure.

**Comment by N-Pex** [comment]
@chris @davidchiles Actually, conversation view controller checks this, but compose does not, so maybe you want to grab this into upstream: https://github.com/zom/ChatSecure-iOS/commit/42a05fbd20b3dd8d7bfbf077cb72ee6084d7ccfc

**Comment by N-Pex** [comment]
WIll be fixed in build 54.

**Comment by cstiens** [comment]
Perfect!
