### ISSUE TITLE
Change the camera icon to the + icon (same as android) 

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#177]
![screenshot_2016-08-17-12-52-11_1](https://cloud.githubusercontent.com/assets/11950115/17745496/f623cfbe-6479-11e6-97ed-4bb5ef191c8a.jpg)

**Comment by N-Pex** [comment]
Not using the exact icons for iOS, since we use FontAwesome icons now. Do they need to be exactly the same?

**Comment by cstiens** [comment]
The gallery, camera and sticker icons for Android and iOS match now, excluding the style of Android being in a circle, but I think this is okay. @N-Pex this ticket can be closed.

**Comment by N-Pex** [comment]
@cstiens Ok, they are in a circle now. Also, the picker is not hidden by the keyboard any more.
