### ISSUE TITLE
Group chat contact select not working

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#178]
1) open new chat/contact select screen
2) tap the group chat mode icon
3) select the contacts you want in group chat
4) group chat starts... but with no one in it
- invited contacts never receive invite message

**Comment by n8fr8** [comment]
one-to-one message go through fine between the test accounts fyi

**Comment by n8fr8** [comment]
also just tested, iOS never receives group invite or joins, for a group it is added to from an Android device. other android devices receive invite fine.

**Comment by N-Pex** [comment]
I definitely see some strangeness here as well. I create a group with 3 people, but only 2 of them are added to the group. If I then leave to main screen and try to come back to the group I get a crash.

Later I deleted the group and tried to create a new one. I then had a strange new "friend" identified by a GIUD in there as well, the old group I am guessing(?)

@davidchiles I am not sure I can get further on this, could you please have a look?

**Comment by N-Pex** [comment]
@chrisballinger , @davidchiles I am not totally sure, but it seems to me like this is related to some OTRBuddys in my roster having accountUniqueId nil. 

Then later, when selecting buddies to add to the group, in completeSelectingBuddies you have "[buddies anyObject]" to get the account id. For me, this happens to give a nil one.

It seems like the first part of this fails to get a valid id:

- (OTRXMPPBuddy *)buddyWithJID:(XMPPJID *)jid xmppStream:(XMPPStream *)stream transaction:(YapDatabaseReadTransaction *)transaction
{
    if (![self.accountUniqueId length]) {
        OTRAccount *account = [OTRXMPPAccount accountForStream:stream transaction:transaction];
        self.accountUniqueId = account.uniqueId;
    }

**Comment by N-Pex** [comment]
There has been a few of changes in this area as well, I think we need to re-test this.
