### ISSUE TITLE
Stickers are resized / made into JPEGs?

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#18]
When I send a sticker from iOS to Android, it shows up on Android very small and with a white solid background. My hunch is that the sticker is being resized and turned into a JPEG when it is sent. This code is likely done for photo sharing.

**Comment by n8fr8** [comment]
(Solution might be that we don't resize PNG files, only JPEGs)

**Comment by N-Pex** [comment]
Added support for non-scaled PNGs in 7a68a9367cebc3bb902b349cc3b29857f049f781 and 4f9e4363886eaf13171f9d370098e4c36f908e57.

**Comment by n8fr8** [comment]
Will review this soon and hopefully close... I guess they are still getting cropped a bit in the UI widget?

**Comment by N-Pex** [comment]
Yes, they are a bit cropped, I did not dig deeper into that yet.

**Comment by N-Pex** [comment]
@davidchiles or @chrisballinger : OTRMediaItem.m, line 64, has:

imageView.contentMode = UIViewContentModeScaleAspectFill;

This seems to crop incoming stickers. Can we change that to UIViewContentModeScaleAspectFit, or is this by design for photo support etc?
