### ISSUE TITLE
Sending Knock

### ISSUE THREAD

**Issue by silencshadow** [zom/Zom-iOS#182]
Hello,

knocks sending from iOS to iOS Zom is not working. 

regards

**Comment by cstiens** [comment]
Chris, David and/or Mikael are going to test 'knock' this week.

**Comment by davidchiles** [comment]
I was able to send a knock from [ChatSecure in the iOS](https://github.com/ChatSecure/ChatSecure-iOS/commit/023f23dc53e35522b70af96215050f731f6bb8bd) in the simulator to Zom 1.0.10 (51) from TestFlight on my device.

**Comment by cstiens** [comment]
@davidchiles how do I send a knock as a user?
