### ISSUE TITLE
1.0.8 rejected by Apple

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#186]
Here's the message. They had, for the first time, required us to provide a demo account, even though it is not required, so I setup one on dukgo that should have worked.

@chrisballinger @davidchiles Any comment about ipv6 support?

***

Sep 12, 2016 at 12:23 AM
From Apple
2. 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1

We discovered one or more bugs in your app when reviewed on iPad and iPhone running iOS 9.3.5 on Wi-Fi connected to an IPv6 network.

Specifically, the log-in could not be completed. Activity indicator continued to spin indefinitely after we filled in Basic Nickname and touched checkmark.

We've attached screenshot(s) for your reference.

Next Steps

Please run your app on a device while connected to an IPv6 network (all apps must support IPv6) to identify the issue(s), then revise and resubmit your app for review.

If we misunderstood the intended behavior of your app, please reply to this message in Resolution Center to provide information on how these features were intended to work.

For new apps, uninstall all previous versions of your app from a device, then install and follow the steps to reproduce the issue(s). For updates, install the new version as an update to the previous version, then follow the steps to reproduce the issue(s).

Resources

For information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and About Networking

If you have difficulty reproducing a reported issue, please try testing the workflow described in Technical Q&A QA1764: How to reproduce bugs reported against App Store submissions.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log
<img width="768" alt="attachment-2583493658094408906screenshot245" src="https://cloud.githubusercontent.com/assets/30851/18438189/4707c67a-78ce-11e6-9ccf-570ca3d7b2b7.png">
<img width="768" alt="attachment-7060030966395762538screenshot246" src="https://cloud.githubusercontent.com/assets/30851/18438188/46e150f8-78ce-11e6-8763-4e10156a646a.png">

**Comment by n8fr8** [comment]
Good info on testing here: http://www.brianjcoleman.com/tutorial-how-to-test-your-app-for-ipv6-compatibility/

**Comment by N-Pex** [comment]
I don't think this is related to IPv6. Just tested by setting up a IPv6 network and that works fine!

I could however get it to crash on my iPad by restarting, and editing "hi" in the message field. Then the "you are not connected" thingy popped up. When I clicked "connect" it crashed. Also, hitting the "info" icon seems to cause a crash. Maybe the bug is that there is an edit field in the first place, given that you are not actually in a chat when you start up. I guess this is iPad specific.

Looking at the second screen shot then: any idea how to get there? I could not replicate that state with a login dialog looking like that... I will try to test some more!

**Comment by n8fr8** [comment]
""Specifically, the log-in could not be completed. Activity indicator continued to spin indefinitely after we filled in Basic Nickname and touched checkmark."

Somehow they were able to enter only a nickname and attempt to login, which caused a hang.

**Comment by n8fr8** [comment]
@davidchiles seems it might be related to the Tor option. Can we make that option disappear if we detect that we are on an IPv6 only network? 

This might work: http://stackoverflow.com/questions/7072989/iphone-ipad-osx-how-to-get-my-ip-address-programmatically

**Comment by n8fr8** [comment]
Oh lord, 1.0.8 was now magically accepted by Apple, with this comment "We noticed that the aforementioned issue is now resolved. We will continue the review, and will notify you if there are any further issues."

We'll keep at the Tor on IPv6 issue, but for now closing this ticket!
