### ISSUE TITLE
Testflight build crashed on launch

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#187]
From Apple:
2. 1 PERFORMANCE: APP COMPLETENESS
Performance - 2.1

We were unable to review your app as it crashed on launch. We have attached detailed crash logs to help troubleshoot this issue.

Next Steps

Please revise your app and test it on a device while connected to an IPv6 network (all apps must support IPv6) to ensure it will launch without crashing.

Resources

For additional information about supporting IPv6 Networks, please refer to Supporting IPv6 DNS64/NAT64 Networks and Supporting IPv6-only Networks.

For a networking overview, please see About Networking.

For information on how to symbolicate and read a crash log, please see Tech Note TN2151 Understanding and Analyzing iPhone OS Application Crash Reports.

If you have difficulty reproducing this issue, please try testing the workflow described in Testing Workflow with Xcode's Archive feature.

If you have code-level questions after utilizing the above resources, you may wish to consult with Apple Developer Technical Support. When the DTS engineer follows up with you, please be ready to provide:
- complete details of your rejection issue(s)
- screenshots
- steps to reproduce the issue(s)
- symbolicated crash logs - if your issue results in a crash log

[temp..zqlohfhg.crash.txt](https://github.com/zom/Zom-iOS/files/490097/temp.zqlohfhg.crash.txt)
[temp..lnjgfaqj.crash.txt](https://github.com/zom/Zom-iOS/files/490098/temp.lnjgfaqj.crash.txt)

**Comment by chrisballinger** [comment]
Was this build produced after the CocoaPods 1.0.1 commit upstream? The issue is that ChatSecureCore.framework isn't being bundled in Zom for some reason.
