### ISSUE TITLE
UI on iPad doesnot show message

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#190]
I just installed Zom on an ipad, registered my jabber id and sent a message to another jabber user
 (in fact to myself just with a different jabber id).

 However, the user interface on the ipad does not show the message I typed (only inside the input line)
 and when I receive a reply, I do not see this either - only in the "chats" list (my roster) I see
 the last line of the received message and the time since it was received.

 I have seen the same problem with ChatSecure.

 Is this a known problem ?

**Comment by n8fr8** [comment]
Yes. It is fixed in the Test Flight version.
