### ISSUE TITLE
does suggest servers

### ISSUE THREAD

**Issue by gwasher** [zom/Zom-iOS#193]
Does zom select  servers from the mostly- or all green column tested servers via

https://gultsch.de/compliance.html 

![server xep as tested](https://cloud.githubusercontent.com/assets/23587635/20459756/3e5b256e-ae82-11e6-9d9a-9d777ca66c18.png)

**Comment by n8fr8** [comment]
We have our own list, and do consider the ones recommended here and elsewhere.
