### ISSUE TITLE
Add new "buddhist" sticker pack

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#198]
assets coming soon

**Comment by cstiens** [comment]
@N-Pex Is this resolution high enough? I'm not familiar with the size and resolution of the other stickers.

![butter lamp-01](https://cloud.githubusercontent.com/assets/1434597/20985578/ab4ac77c-bc8a-11e6-83ea-34e9796a853d.png)

**Comment by cstiens** [comment]
@N-Pex Ignore this question. I found the size, and am working on getting images at 370x320 that are not blurry.

**Comment by N-Pex** [comment]
@cstiens Ok, thanks.

**Comment by cstiens** [comment]
@N-Pex The assets can be found here: 
https://drive.google.com/drive/u/0/folders/0B98EO-hKbBPnQy15VXVubnFHZ1E

**Comment by n8fr8** [comment]
we will need to agree on the short codes for these as well, based on the
sticker names as usual.

**Comment by N-Pex** [comment]
Ok, added these, will be in version 54.

@n8fr8: I just used the file names in the link above (as lower case) and the sticker pack name "buddhist". Good enough?

**Comment by n8fr8** [comment]
Muy bien!

**Comment by cstiens** [comment]
@N-Pex The buddhist-mandala sticker is not showing up in a chat when it's sent. Instead it displays the text, ":buddhist-mandala:"

**Comment by N-Pex** [comment]
@cstiens Strange. I can see that this image has no alpha channel, while the others do. Not sure why that would make it fail though. Could you please send me a new image with alpha?

**Comment by N-Pex** [comment]
Ah, it was a jpeg. Converted to png now. @n8fr8 You will want to pick this up instead (I would have put these in Zom-Assets, but I don't think I have write access).

![mandala](https://cloud.githubusercontent.com/assets/5418622/21256106/95307cb0-c370-11e6-8840-174a45dcdba7.png)

**Comment by cstiens** [comment]
Works now!
