### ISSUE TITLE
Remove on/offline status and replace with "last seen" message

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#199]
We want to move away from focusing online/offline and instead use "last seem" with a time, and also the typing indicator as activity status. This will confuse users less.

**Comment by cstiens** [comment]
Action items:
- Remove green indicator all together (it's inconsistency is causing confusion)
- Add 'Last seen to chat view header

**Comment by chrisballinger** [comment]
There are some XMPP extensions that might make this work a lot better: https://github.com/ChatSecure/ChatSecure-iOS/issues/716

It would also avoid us needing to store last seen in the database and could instead use the in-memory cache. I'm not sure how well this is supported by servers though.
