### ISSUE TITLE
Zom iOS - Opening Zom from TestFlight

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#2]
While I click on 'Open' button from TestFlight, there is some issue with the interface. It takes me to a blank page with lines (screenshot doesn't capture that, so couldn't share one) for about 10 seconds and then takes me to Zom.

Is that something to do with TestFlight?

I have also noticed the same while opening Zom from the dashboard after it crashed.

Reinstalled ZOM, the 'Create New Account' page looks great.

**Comment by N-Pex** [comment]
The blank table view with lines was in fact a launch image. Changed this so that Zom now has a dedicated theme colored launch screen: da09e051be113cff8666c4c070eae6354ba89ea4
