### ISSUE TITLE
Add the ability for user to change password

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#203]
In the account view, users need the ability to change their password. We also need an option to display/hide the password. @N-Pex This can be done as it is on Android, and how we've done with Pixelknot by placing an eye icon to the right of the password.

**Comment by chrisballinger** [comment]
The (i) icon is already there to show the password. Changing the password for the account is a bit more complicated and will require changes upstream.

**Comment by cstiens** [comment]
Hey @chrisballinger. Thanks for the clarification. Can you post a screenshot of the icon to show the password in Zom? I don't see it in the latest build.

**Comment by davidchiles** [comment]
I've added some plumbing here https://github.com/ChatSecure/ChatSecure-iOS/commit/6403bb50a7c7d978a32bf4e98a0f172ed12eff6d

@cstiens what's the expected UI/UX for changing the password? A button somewhere that pushes a new view?

**Comment by cstiens** [comment]
@davidchiles Off the top of my head, yes. From the 'account view', a user would tap 'Change password' and a full screen modal view with the keyboard would open. In this view, we need the user to enter the new password twice. Once to set, once to confirm. Since we automatically set a very secure and unmemorable password when users sign up, I don't think we should require them to enter their old password before creating a new one. Thoughts on this?

**Comment by chrisballinger** [comment]
@cstiens Yeah they shouldn't have to re-enter the old password because you can only change the password after you've already authenticated anyway.

**Comment by N-Pex** [comment]
I've checked in some UI for this now. @davidchiles, could you please have a look at didPressChangePasswordButton to hook it up? I couldn't figure out how to get the xmppStream (is it via the OTRXMPPManager, I could not import that easily?)
