### ISSUE TITLE
add "Zom Services" in discover tab

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#205]
Under the "Photo Stream" add a new Zom Services entry.

Tapping, for now, should open a new chat with "zombot@home.zom.im" account, just like tapping on a contact.

More detail to come.

**Comment by N-Pex** [comment]
Ok, I added some code to add a "zombot" buddy, but this functionality is hidden for now. Still two issues here:

1. How do we handle approval of the new bot buddy?
2. Need to filter the buddy so that it is not shown in normal friends list(?)

**Comment by n8fr8** [comment]
It can show up in friends list for now. The bot should always be online and automatically approve the user, so the pending status should be fast.

**Comment by cstiens** [comment]
Hey @n8fr8, we need an icon for Zom services. What about a friendly looking robot that doesn't look like the droid robot? Something like this guy ...
![image](https://cloud.githubusercontent.com/assets/1434597/21154511/37eef100-c134-11e6-858d-068e2e47e746.png)

Font awesome and the material design icons don't have good options, so I think we could do something custom.

Also, should we plan to ship the iOS app with Zom Services active, even though we may not be able to do extensive testing?

**Comment by cstiens** [comment]
Zom services is in the Discover tab and opens a new chat with "zombot@home.zom.im"
