### ISSUE TITLE
Change button text to 'Add' rather than displaying the account ID

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#206]
If there are multiple accounts, we should show the account IDs. However, **if the user only has one zom account** the button above cancel should say only say 'Add'. Just to clarify, this is the button that says 'jodiezom@dukgo.com' in the screenshot below.

![img_0076](https://cloud.githubusercontent.com/assets/1434597/21065191/8e980522-be24-11e6-9df9-43c8633d1c3a.PNG)

**Comment by chrisballinger** [comment]
Fixed

**Comment by cstiens** [comment]
To test, I sent an invite link from my Android phone to the iPhone. Clicking on the link brought up the prompt. However, it still has the account ID on the button instead of add. This may be because I previously had 2 accounts in Zom on my iPhone. (I deleted one to test this.) I will reset and test again.

@chrisballinger can you have a look at this? Will you test it on your phone too?

**Comment by cstiens** [comment]
I uninstalled and reinstalled Zom to test this again with only one account set up from the start. I get the same UI as before. Has this been pushed to the latest test flight?

**Comment by N-Pex** [comment]
Yes, I believe so.

**Comment by chrisballinger** [comment]
Should be actually fixed this time

**Comment by cstiens** [comment]
Perfect!
