### ISSUE TITLE
'+' and Microphone not working when keyboard is open; Microphone not opening at all

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#207]
In a chat view, when I tap on the '+' and microphone, nothing happens.
When the keyboard is closed, I get the correct options for '+'; When the keyboard is closed and I tap on the microphone, I get the options for + (photo, camera and stickers).

**Comment by chrisballinger** [comment]
I'm pretty sure Mikael already fixed this

**Comment by N-Pex** [comment]
@cstiens Are you sure the buttons were enabled, or were they gray? When you are not in an encrypted chat they will be gray, and disabled.

The microphone button opening the attachment picker was a new bug I introduced in the last commit, it will be fixed in build 53.

**Comment by cstiens** [comment]
Hey @N-Pex I just tested this again this morning to be sure. They are enabled, and not working.

**Comment by cstiens** [comment]
Working now
