### ISSUE TITLE
Audio Record for the first time

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#209]
When I use the microphone for the first time, I get an iOS system modal, asking for permission to record audio. Once I tap 'Allow' the recording button says 'release to send', but it didn't actually record. I tapped on it again and it sent an empty message of 0 seconds. 

Since the user has already released the button to respond to the iOS modal, we should return them to the audio view where the button says 'hold to talk' for the first use scenario.

**Comment by cstiens** [comment]
@N-Pex I did more testing on this. It turns out that the above scenario happens with a fresh install of Zom.

If I have already allow permissions, then go and change them in settings to un-allow and test this again .. the prompt I receive is different. It requires me to open ios settings outside of zom to make the change. Then when I return to Zom, I start from scratch.

**Comment by cstiens** [comment]
This is still an issue

**Comment by N-Pex** [comment]
@cstiens Strange. I never get any modals asking for permission. Not on device, not on simulator. What device/OS version are you on?

**Comment by n8fr8** [comment]
This definitely happens to me on a fresh install, including the weird state the first time.

**Comment by N-Pex** [comment]
@n8fr8 On what device/OS version?

**Comment by N-Pex** [comment]
Never mind, I could get it to fail now, when I run the release version!

**Comment by N-Pex** [comment]
Ok, I think this is fixed now, via this MR: https://github.com/ChatSecure/ChatSecure-iOS/pull/718

**Comment by cstiens** [comment]
Yes! Yay! It's fixed
