### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#21]
Conversation weren't encrypted at start between Zom on Android and iOS but was able to chat. Once I clicked on the lock on Zom in iTouch to verify, the msgs stopped going through.

**Comment by n8fr8** [comment]
Strange... did it say the encryption was started on iOS side?

**Comment by gekhung** [comment]
Nope, the lock still remain unlocked in iOS and there was no notification saying the conversation then on will be encrypted. In fact, after clicking on the lock, the messages doesn't go through between the accounts. The msgs send from Android doesn't appear in iOS but in android, it's still showing two tick marks & the three jewels.
