### ISSUE TITLE
Flow from contacts and conversations views

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#213]
The flow on iOS should match Android.

**Conversations**
We need to add a 'New chat' button in top bar. This icon should be a '+' symbol.
Tapping on the 'new chat' button opens the friends list, where the user taps on a friend to chat with.

**Friends List**
Tapping on a contact from the friends list, opens their profile view.
We need to add a 'start chat' action in this view to match Android.

**Comment by N-Pex** [comment]
This turned out to be pretty straight forward, so please test in version 55.

**Comment by cstiens** [comment]
Works great!
