### ISSUE TITLE
Show Password

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#215]
@chrisballinger The 'eye' icon is now displayed next to the password. However, the default password is so long that it gets clipped and I can't see the full password. Can we move this to a second line, or wrap the text to a second line. If users can't see the full password it defeats the purpose of seeing it at all.

**Comment by davidchiles** [comment]
I just tested this with a newly created account and everything looks fine. There should also be more room in the account profile view for longer passwords.

**Comment by cstiens** [comment]
There's still a '...' in the account information view, but this looks great in the 'me' tab. I'm going to go ahead and close it out.
