### ISSUE TITLE
Select default account

### ISSUE THREAD

**Issue by N-Pex** [zom/Zom-iOS#217]
Now that we have a "me" tab, we need a way to select a "default" account to show there, like on Android. Currently it just uses the first account it finds.

**Comment by cstiens** [comment]
We could add an option here to 'Set as default' or 'Use this account'

![img_0055](https://cloud.githubusercontent.com/assets/1434597/21268580/0951d2c0-c375-11e6-855b-538691c6d905.PNG)

**Comment by N-Pex** [comment]
@cstiens Fixed this now. But currently, when having multiple accounts, when selecting "Add Friend" you get a "Choose account" dialog. I guess we should remove this and just add the friend to the default account?

**Comment by cstiens** [comment]
@N-Pex Yes. I think it makes sense to remove it, and to add friends to the default account. As it is now, it's pretty confusing to have the 'choose account' step in the workflow.

**Comment by chrisballinger** [comment]
@N-Pex You might want to make this the account.uniqueId

https://github.com/zom/Zom-iOS/blob/4af79fea19b45b5b0b5d3858ba1bd39d2a4825aa/Zom/Zom/Classes/ZomAppDelegate.m#L138

In theory there's nothing stopping you from having the same JID on multiple accounts. For instance a Tor and non-Tor account.

**Comment by N-Pex** [comment]
@chrisballinger Great, thanks, fixed this now!
