### ISSUE TITLE
Add Beta Tag to the Group Chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#218]
Add 'Beta' text below 'Create a Group'

**Comment by chrisballinger** [comment]
I'm pretty sure you can't add the word "beta" to anything on iOS, it will
get rejected by Apple.

**Comment by davidchiles** [comment]
This article from 2013 agrees http://venturebeat.com/2013/02/08/9-surprising-reasons-mobile-apps-get-rejected-from-the-apple-app-store/

**Comment by cstiens** [comment]
Interesting. Well, I guess we have our answer. Thank you for getting this info! I guess it's best to not add it if it means we may get rejected.

**Comment by davidchiles** [comment]
The article also states:

> Use of the word “beta” or otherwise indicating that your app is unfinished

I'm concerned that the "Coming Soon" subtitles would get us rejected too.

**Comment by N-Pex** [comment]
@davidchiles @n8fr8 @cstiens @chrisballinger Hm, yes, what should we do?

**Comment by cstiens** [comment]
It looks like we got away with 'Coming Soon'. I'm going to close this issue.
