### ISSUE TITLE
Audio playback for received messages

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#219]
Gray out audio playback for received messages until the full file has been received.
@davidchiles this is for the issue we discussed on scrum this morning.

**Comment by cstiens** [comment]
@davidchiles This was fixed in one of the final test flight versions I tested in December. However, I just downloaded Zom from the Apple store, and audio messages are not playing back. They do gray out until the full message is received, but after the message is fully received, it displays a 0:00 second message, and plays nothing. 

![img_0076 2](https://cloud.githubusercontent.com/assets/1434597/21867430/c1acf25c-d813-11e6-8411-f0ab6ac8945c.PNG)

**Comment by davidchiles** [comment]
@cstiens Which app (app/platform/version) is sending the audio messages?

**Comment by cstiens** [comment]
The messages were sent from a Samsung Galaxy s7 (Android version 6.0.1) running the latest version of Zom that in the Play Store.

**Comment by cstiens** [comment]
I just tested this again to reproduce it. It's working now. I have no idea why. There were only two differences in this test (other than it being a different day):
1. I tested with a different ios account that received the message (hosted on calyx instead of dukgo)
2. I tested with the same account that received the message, but this time more messages had been exchanged. In the initial test where it failed, the audio message was the first one received.

I can do more testing to see if I can reproduce it. Maybe it was a fluke?

**Comment by N-Pex** [comment]
I just built a version 60 without this, but let me know if I should re-build with any fix for this please.

**Comment by cstiens** [comment]
Yes, the build should include the fixes that @davidchiles cherry picked for this.

**Comment by cstiens** [comment]
@davidchiles Were you able to identify if there was a regression in the audio playback with the OMEMO merge?
