### ISSUE TITLE
Friends View on First Use, Show graphic

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#220]
Before there are any friends to display in the friends list, show the graphic at the top of the list. I believe this was in a previous build, but got removed when we switched to the tab UI. I'll track down the asset.

**Comment by N-Pex** [comment]
@cstiens In the "Zom | Chat" tab or in "Zom | Friends" (instead of the "Add friend" button, or as a complement?)

**Comment by N-Pex** [comment]
@cstiens: Could you please elaborate on where this graphic should be added? In the friends tab we already have a "add friend" button, so it is not really empty.

**Comment by n8fr8** [comment]
I believe she means in the conversation list, which is the first screen you see.

I think rather than crazy logic about # of friends, etc, we should just have the add friends header graphic, that you can dismiss with 1 tap on an X, or just have it disappear after adding one friend.

**Comment by N-Pex** [comment]
Ok, I re-added this now. It will disappear after adding one friend.

**Comment by cstiens** [comment]
Done
