### ISSUE TITLE
Avatar: Ability to add and change from the Me tab

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#221]
@N-Pex This is something that can be worked on and added in to the next test flight build for testing. Let me know if you have any UI questions. I know you've already made some progress on it.

**Comment by N-Pex** [comment]
@davidchiles ZomCongratsViewController and ZomProfileViewController ("me" tab) now both set avatarData. I am not sure, but it seems like this only resets local image cache. I guess we need to add some code to actually send this new avatar to server/contacts(?)
