### ISSUE TITLE
Add Friends step in onboarding

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#222]
I created a new account to test the onboard flow on Jan 11, and found that the 'Add Friends' step was not included in the process. I'm not sure if it got removed or was never added, but we need to have it. 

I've attached screenshots of the screens in the current onboard flow. (zom version 1.0.11)

![img_0059](https://cloud.githubusercontent.com/assets/1434597/21997661/140eb9e6-dbf6-11e6-91fb-bbf1cb0619d7.PNG)

![img_0060](https://cloud.githubusercontent.com/assets/1434597/21997666/17f4e080-dbf6-11e6-95c9-10864f7a6a53.PNG)

![img_0062](https://cloud.githubusercontent.com/assets/1434597/21997673/1d95673a-dbf6-11e6-95d6-682b8c8b9ce7.PNG)

![img_0066](https://cloud.githubusercontent.com/assets/1434597/21997680/2519c4f6-dbf6-11e6-9e2f-502929049c75.PNG)

![img_0067](https://cloud.githubusercontent.com/assets/1434597/21997686/2a66b7de-dbf6-11e6-912b-1d74a98b10cf.PNG)

![img_0068](https://cloud.githubusercontent.com/assets/1434597/21997688/2ea49c08-dbf6-11e6-8611-6fe4f8e2cb02.PNG)

![img_0070 2](https://cloud.githubusercontent.com/assets/1434597/21997692/364922e4-dbf6-11e6-93e4-4dc4a3dea8d9.PNG)

**Comment by N-Pex** [comment]
@cstiens I notice when looking at this, that the onboarding "add friends" is not the same as normal "add friends", e.g. the "manual add" is not present and the background is different. Is this the way it should be or should they look more consistent?

**Comment by n8fr8** [comment]
On Android, this is what we show in onboarding... it is meant to just give them a chance to invite people or quickly add people via scanning. It is different than the typical "add friend" screen in the app

![screenshot_20170123-152523](https://cloud.githubusercontent.com/assets/30851/22252029/da6dea2e-e21a-11e6-855d-5fd9410e4120.png)

**Comment by cstiens** [comment]
Hey @N-Pex, I saw that you added the graphic in the conversations view already: https://github.com/zom/Zom-iOS/issues/220#issuecomment-274829787. Let's hold off on adding this step, since we have the other. I will discuss the desired design with the product team.

**Comment by cstiens** [comment]
@N-Pex, @n8fr8 found that this view is showing up as a black screen in the onboarding of the last Test Flight release v 1.0.12(59). Is the easiest step forward to go ahead and include it, since it's already implemented? If so, let's do it.

**Comment by N-Pex** [comment]
No, this is just a stupid bug, will be fixed in next build.
