### ISSUE TITLE
Make home.zom.im the default server

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#227]

**Comment by davidchiles** [comment]
## Still need:
- [ ] Server image to be displayed. Preferred 512x512 px.
- [ ] Twitter URL
- [ ] Server description

**Comment by chrisballinger** [comment]
@davidchiles 

1. For now you could copy over the app icon
2. https://twitter.com/zomapp but it's empty
3. Not sure about that one

**Comment by n8fr8** [comment]
3. Zom's home servers, setup just right, keeping all your messages safe and sound! :)

**Comment by N-Pex** [comment]
@davidchiles I jumped in there and added 1. Zom image, 2. "https://twitter.com/zomapp" and 3. "Zom's home servers, setup just right, keeping all your messages safe and sound!", but then did not have the rights to push this to the repo! =)

**Comment by chrisballinger** [comment]
@N-Pex GitHub's permission settings are really confusing but I think I fixed it.

@n8fr8 Can we schedule a call with the server maintainer? There are a few XEPs that should be enabled (XEP-0198, XEP-0357, XEP-0363, XEP-0313, and more). Also a big issue, STARTTLS is not required at the moment for c2s or s2s so it's vulnerable to downgrade attacks.

**Comment by N-Pex** [comment]
@chrisballinger Yes, thanks, I just pushed my changes!

**Comment by n8fr8** [comment]
@chrisballinger that is really surprising considering who set it up. Argh. Will do.

**Comment by n8fr8** [comment]
@N-Pex @chrisballinger on a clean install of the new build, I was prompted to approve the home.zom.im TLS certificate. We don't want that to be necessary - can we build in the pinned cert fingerprint to avoid this?

**Comment by chrisballinger** [comment]
The [cert is already in there](https://github.com/zom/xmpp-server-list/blob/82730ca1b4e8c9b95de9a0cdbb9664b4c672837e/servers.json#L16), I think it's just not currently being added to the trust store.

**Comment by cstiens** [comment]
The prompt to approve the TLS certificate is still in the UI in Version 1.0.13 (62). Can we avoid/remove it?

**Comment by N-Pex** [comment]
@chrisballinger Any great ideas when and where in the code to do this? =)

**Comment by chrisballinger** [comment]
In the certificate handling code we need to load the certificate base64
from the json and add it to the trust store. I'll think about the best spot
to put it.

**Comment by n8fr8** [comment]
AndroidPinning has a tool for generating pin values:
https://github.com/moxie0/AndroidPinning/tree/master/tools

**Comment by n8fr8** [comment]
This is our current out of date file for Zom Android:
https://github.com/zom/Zom-Android/blob/master/app/src/main/assets/servers.json

**Comment by N-Pex** [comment]
@chrisballinger @davidchiles I think I got this working now (but the cert was wrong!), checked in an updated file at https://github.com/zom/xmpp-server-list/blob/zom/servers.json

I needed to make OTRCertificatePinning.h and OTRXMPPServerInfo.h public and add them to ChatSecureCore.h, but am unsure on what branch/repo to use for a pull request on this =)

**Comment by chrisballinger** [comment]
@N-Pex Oh awesome. You can send a PR upstream to master branch

**Comment by cstiens** [comment]
fixed!

**Comment by n8fr8** [comment]
Woohoo - 〈( ^.^)ノ

**Comment by n8fr8** [comment]
Hmm... so I just did a fresh install on my iPod Touch, and I still got the certificate prompt for home.zom.im.

**Comment by chrisballinger** [comment]
It may be pinning to `zom.im` and not `home.zom.im`?

**Comment by N-Pex** [comment]
No, it's pinning to home.zom.im.

My guess is that the device remembers a cert for home.zom.im since earlier? We have this code:

NSArray *storedCerts = [OTRCertificatePinning storedCertificatesWithHostName:@"home.zom.im"];
 if (storedCerts == nil || [storedCerts count] == 0) {
     ... store it ...

**Comment by chrisballinger** [comment]
It will show a new dialog if the public key ever changes, which could be the case every 90 days for Lets Encrypt's default settings. You can override it to reuse the private key though.
