### ISSUE TITLE
Swift compiler segmentation fault

### ISSUE THREAD

**Issue by chrisballinger** [zom/Zom-iOS#229]
While working in the [`omemo`](https://github.com/zom/Zom-iOS/tree/omemo) branch for the merge, I was hit by a segmentation fault in the Swift compiler. There's a chance that updating to Swift 3 might help, but it's probably something else.

@N-Pex does this happen on your machine as well? Make sure to `git submodule update`, and then run `bundle install`, `bundle exec pod install` for both ChatSecure and Zom. You may also need to re-run the build scripts for OTRKit and CPAProxy.

**Comment by N-Pex** [comment]
@chrisballinger Yes, I see this from time to time, usually fixed by just rebuilding the project again...

**Comment by chrisballinger** [comment]
@N-Pex I cleaned and deleted derrived data but it still does it for me. :( Were you able to get this commit to compile at all?

**Comment by N-Pex** [comment]
@chrisballinger Hm, no =( I just cloned a fresh new copy and built all, but yes, I get a segmentation fault now. Seems related to ZomOverrides.h and/or OTRSetting.h(?) Did you manage to find out more?

**Comment by chrisballinger** [comment]
Not yet, I'll take another look tomorrow now that I know it's not just my machine. Thanks for checking!

**Comment by chrisballinger** [comment]
Resolved
