### ISSUE TITLE
build 60: delay opening conversatio

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#234]
when I tap on a conversation in the main list, there is a noticeable delay before the full conversation view opens up

**Comment by chrisballinger** [comment]
We've made a lot of optimizations in the omemo branch that will significantly help with this. It was a significant amount of work that can't really be cherry picked.

**Comment by n8fr8** [comment]
but this is a regression. It didn't happen before this build.

**Comment by cstiens** [comment]
Fixed with avatar improvements
