### ISSUE TITLE
'Me' tab was empty after updating to Test Flight version 1.0.13 (62)

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#239]
When I updated, I just stayed logged in to the account I had setup, and the ‘Me’ tab was empty. It didn’t display anything for the account.

**Comment by N-Pex** [comment]
@cstiens Sounds like it failed to log in.

**Comment by cstiens** [comment]
This hasn't been a reoccurring problem with the new build.

**Comment by cstiens** [comment]
Haven't seen this issue since.
