### ISSUE TITLE
Add friend doesn’t work if you’re not connected to the server

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#244]

**Comment by N-Pex** [comment]
This should be fixed by the upstream PR here: https://github.com/ChatSecure/ChatSecure-iOS/pull/734

**Comment by cstiens** [comment]
@N-Pex Is this fix included in the lastest version on test flight?

**Comment by cstiens** [comment]
Adding a friend when the person inviting or accepting is offline now works! Awesome job.
