### ISSUE TITLE
Group Chat: Unable to invite people to a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#253]
I created a group on my iPhone, but can't invite people to that group after it's created.
App Version 1.0.13 (64)

**Comment by mimi89999** [comment]
@cstiens Also, if I create a MUC from Gajim or Conversations, I don't see an option to join by entering the JID in Zom iOS. If I add the Zom iOS contact to the MUC in Conversations, I still don't see the MUC in Zom.

I think that MUC is simply not yet supported by Zom.

**Comment by cstiens** [comment]
Hey @mimi89999 Thank you for the feedback. We're about to be putting more time toward group chat, so your timing is perfect. 

> Also, if I create a MUC from Gajim or Conversations, I don't see an option to join by entering the JID in Zom iOS. If I add the Zom iOS contact to the MUC in Conversations, I still don't see the MUC in Zom.
I think that MUC is simply not yet supported by Zom.

@chrisballinger do you know if Zom iOS supports MUC?

**Comment by chrisballinger** [comment]
It "should" work but it is so buggy that I'm not surprised there is an
issue. It needs an overhaul.

**Comment by N-Pex** [comment]
@cstiens Do we have the UI design for this anywhere? Currently it looks like this, if you hit the "group" icon when in a multi user chat:

I guess we should have a "+" button top right to invite more users, or any other means? Also, I guess we should not list ourselves here (currently test2 is the one that created the group)

![simulator screen shot 28 juni 2017 15 04 35](https://user-images.githubusercontent.com/5418622/27638635-31863e38-5c14-11e7-8783-0c8d52b6a6f2.png)

**Comment by cstiens** [comment]
@N-Pex I do have designs. I'm planning to talk with the product team about them more tomorrow to get the go ahead to implement.

**Comment by cstiens** [comment]
Fixed.
