### ISSUE TITLE
Remember that you've enabled push

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#256]
After logging out, when I log back in to an existing account, shouldn't Zom remember that I've already enabled push?

**Comment by N-Pex** [comment]
@cstiens Yes, I think so. What steps did you take exactly?

**Comment by cstiens** [comment]
It's usually after a fresh install. (i.e. I uninstall and reinstall).

**Comment by chrisballinger** [comment]
Push permissions are reset after app reinstalls, but that should still be
handled by the onboarding.

**Comment by N-Pex** [comment]
Ok, I guess this is no issue then?

**Comment by cstiens** [comment]
@chrisballinger even with a new install, if the user logs in to an existing account, is it possible to remember that they've already opted in to notifications, so that we don't have to ask them again?

**Comment by chrisballinger** [comment]
Nope, push permissions are handled at the OS-level. We actually already have code to skip the permissions screen if push was already enabled during the lifetime of the install.
