### ISSUE TITLE
No double check for photos and audio even though they go through

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#257]
User is getting a double check when messages go through, but only a single check for photos and audio when they go through.

**Comment by N-Pex** [comment]
Seems like dateSent is never set on the multimedia messages (from Upstream).

**Comment by N-Pex** [comment]
@chrisballinger Any idea why?

**Comment by chrisballinger** [comment]
@N-Pex I vaguely remember that being changed in the recent-ish past. You might be able to use git blame to figure out the history there and if there would be any side effects.

**Comment by cstiens** [comment]
So far this is working.
