### ISSUE TITLE
screenshots for apple store

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#26]
4.7 inch and 5.5 inch

- onboarding
- stickers
- invite qr code
- main chat window

**Comment by N-Pex** [comment]
Will these do?

[Screenshots.zip](https://github.com/zom/Zom-iOS/files/56704/Screenshots.zip)

**Comment by n8fr8** [comment]
We need a full size image:

4.7-inch Retina screenshot
If your app indicates that it is optimized for the iPhone 6, at least one 4.7-inch screenshot is required. Up to four additional screenshots can be uploaded. You can rearrange the screenshots when you create or edit the iTunes Connect record.
Screenshot requirements are:
72 dpi, RGB, flattened, no transparency
High-quality JPEG or PNG image file format
750 x 1334 pixels for hi-res portrait
1334 x 750 pixels for hi-res landscape
Locked
5.5-inch Retina screenshot
Screenshot requirements are:
72 dpi, RGB, flattened, no transparency
High-quality JPEG or PNG image file format
1242 x 2208 pixels for hi-res portrait
2208 x 1242 pixels for hi-res landscape

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2

**Comment by n8fr8** [comment]
just portrait is fine, at 750 x 1334 for iPhone 6 / 4.7" size and 1242 x 2208 for iPhone6Plus 5.5"

**Comment by N-Pex** [comment]
@n8fr8 : I Added a few of them here now, maybe we can add/change later.

[Screenshots2.zip](https://github.com/zom/Zom-iOS/files/61822/Screenshots2.zip)

**Comment by n8fr8** [comment]
Perfect, thanks!
