### ISSUE TITLE
Add Photostream

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#263]
The first stab at this should show all of the images sent and received on Zom in a gallery view. We will fine tune this feature, and add info about who the photo was sent to and/or received from later.

**Comment by chrisballinger** [comment]
Some candidates to evaluate further:

- [IDMPhotoBrowser](https://github.com/thiagoperes/IDMPhotoBrowser) - 2236 stars, updated Feb 12 2017. Obj-C.
- [INSPhotoGallery](https://github.com/inspace-io/INSPhotoGallery) - 176 stars, updated Oct 11, 2016. Swift 3.0.
- [NYTPhotoViewer](https://github.com/NYTimes/NYTPhotoViewer) - 1942 stars, updated Feb 16, 2017. Obj-C.

**Comment by chrisballinger** [comment]
We will need to use the GCDWebServer/IOCipher bridge for async image loading.

**Comment by cstiens** [comment]
@N-Pex Can you take a stab at this one? Chris is going to continue to wrap up the file transfer work, then focus on group chat.

**Comment by N-Pex** [comment]
@cstiens Ok, basic functionality is in there now, but I guess it could use some more styling! =)

**Comment by cstiens** [comment]
Sweet! Could you share a screenshot from the simulator when you get a chance? @N-Pex

**Comment by N-Pex** [comment]
@cstiens This is what it looks like currently, with a gallery view and then a single-image view (in which you can swipe between images). The gallery we have full control over, the swipe-view we can change background to black and do some basic styling and configuration.

![simulator screen shot 22 juni 2017 08 27 27](https://user-images.githubusercontent.com/5418622/27420945-6e8128e8-5728-11e7-8f6b-6273a61f5315.png)
![simulator screen shot 22 juni 2017 08 35 19](https://user-images.githubusercontent.com/5418622/27420946-6e856638-5728-11e7-8839-394039390003.png)

**Comment by chrisballinger** [comment]
Looking good!

**Comment by cstiens** [comment]
I'm going to close this ticket. We'll make new tickets for UI-related improvements. Thank you guys!
