### ISSUE TITLE
Send notification when a friend request has been accepted

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#265]
When a friend accepts a request, the person that sent the message should receive a confirmation notification saying 

**zomusername**
You are now friends on Zom

Here's what we show on Android:
<img width="422" alt="screenshot 2017-03-15 21 53 12" src="https://cloud.githubusercontent.com/assets/1434597/23979490/d4e27708-09c7-11e7-947c-85e152dd1ffe.png">

**Comment by N-Pex** [comment]
Ok, sent a PR for support upstream.

**Comment by cstiens** [comment]
Ok this works. So, now you get the confirmation if you have Zom open or running in the background. But, since the app doesn't run in the background all of the time, users who have closed or stopped zom, won't get notified until they open zom again.
