### ISSUE TITLE
Before the OTR session is established, display UI explaining delay

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#268]

**Comment by cstiens** [comment]
This should be displayed in a chat view with a new friend while the OTR session is being established.

<img width="458" alt="screenshot 2017-03-20 14 11 46" src="https://cloud.githubusercontent.com/assets/1434597/24116554/3740faa4-0d75-11e7-8655-734598fa976e.png">

**Comment by N-Pex** [comment]
A bit unsure how this will work between OMEMO clients etc, needs a lot of testing.

**Comment by cstiens** [comment]
Done.
