### ISSUE TITLE
One-to-one encrypted .mp3 file sharing

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#270]
For encrypted file sharing, we're going to start with one media type at a time, with .mp3 files first.

I will help with the UI on this, but here are some things we can start looking into.
- Flow for selecting an audio file from the gallery
- Flow for adding an audio file directly from chat view
- Size limit (ex: set to 5 MB) --
- How we handle file sizes that are larger than the limit -- split into separate files vs. recode
- Playback the audio within the app

**Comment by chrisballinger** [comment]
There is no file browser on iOS so you can't choose arbitrary files from a gallery. The best we could do is register Zom as capable of handling audio files from a share sheet dialog in another app, but I'm not aware of any music apps that allow for this behavior because DRM. I guess you could share your recordings from the Voice Memos app.

Or do you mean forwarding audio messages that people have sent you?

**Comment by cstiens** [comment]
One of the use cases, is to be able to send voice recordings of interviews. In that case, I assume people would share from the voice recorder app they used to record it. But, let me get more clarity on that.

**Comment by cstiens** [comment]
Here's the workflow people use to share .mp3 news files through WeChat:

- Download an .mp3 on the computer
- Send it to themselves via email
- Open the email on their phone
- Download the file
- From the email, tap the iOS share action
- Choose WeChat

@N-Pex Can we mimic this workflow to allow people to share via Zom? That would be our starting place for this feature. The second (which is similar, maybe the same) would be to allow sharing an .mp3 file from the voice recorder app.

**Comment by N-Pex** [comment]
I think this should work now. If it exceeds the limit given by the server we show an error, need to retest this though.

**Comment by cstiens** [comment]
This is working. There is a bug that happens occasionally—https://github.com/zom/Zom-iOS/issues/484

But I'll go ahead and close this since the functionality is in. Thumbs up!
