### ISSUE TITLE
UI for multiple Zom Bots

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#273]

**Comment by cstiens** [comment]
<img width="857" alt="screenshot 2018-02-06 14 47 27" src="https://user-images.githubusercontent.com/1434597/35939105-c428795c-0c10-11e8-961e-31b268e3e47e.png">

**Comment by tladesignz** [comment]
Code start here: 
https://github.com/zom/Zom-iOS/blob/master/Zom/Zom/Classes/View%20Controllers/ZomDiscoverViewController.swift#L27

Base storyboard:
https://github.com/zom/Zom-iOS/blob/master/Zom/OTRResources/Interface/Base.lproj/Tabs.storyboard

**Comment by N-Pex** [comment]
Ok, I added the functionality (the bot info is pulled from a plist, which means we can easily "translate" that file and have different bots for different languages/regions).

So still needed:
@n8fr8 Bot JIDs
@cstiens Artwork

**Comment by n8fr8** [comment]
zomkyibot@home.zom.im
quizbot@home.zom.im

**Comment by cstiens** [comment]
@N-Pex I've attached all of the artwork and UI mockup in this zip file. [zombot-v1.zip](https://github.com/zom/Zom-iOS/files/1708588/zombot-v1.zip)

![uibots_v3](https://user-images.githubusercontent.com/1434597/35995259-67507b1c-0cd8-11e8-91bc-6c408128a76c.png)

**Comment by cstiens** [comment]
@N-Pex 3 minor tweaks:
1) Will you adjust the spacing between the name (ex: Zomkyi) and the phrase (ex: Ask me about Zom) on both bots so that they're closer together? 
2) Also, more importantly, will you make the entire area with the name and chat icon clickable? See screenshot with the red outline indicating the selected area. Sorry, I meant to include that in the design info.
3) Will you change the title of the screen to 'Zom Services'. That's what we have translations for and what should technically be the title since you click on zom services from the discover tab.

![img_0506](https://user-images.githubusercontent.com/1434597/36009147-84d95c2a-0d10-11e8-90f6-7dc610b6e5a7.jpg)
