### ISSUE TITLE
Group Chat: Delayed invite notification

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#274]
I received a notification (15-20 minutes later) that I'd been invited to a group after I had already sent messages to the group.

We ran multiple tests, and only had this issue once. I will try to reproduce it in our next round of group chat testing.

**Comment by chrisballinger** [comment]
Invites (of any kind) don't send push messages. Was the app in the background?

**Comment by cstiens** [comment]
Right. It was likely a local notification. It was displayed the same as a push notification, but the app was definitely running. We had zom open on all of the phones we were testing with.

**Comment by chrisballinger** [comment]
Ah if its running in the foreground then that's probably also a (different) server issue. Is this using the Zom conference server?
