### ISSUE TITLE
Migrate existing dukgo users to a new server

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#278]

**Comment by cstiens** [comment]
@chrisballinger please link to the list of action items you create for chat secure here. Thanks!!

**Comment by chrisballinger** [comment]
Upstream here: https://github.com/ChatSecure/ChatSecure-iOS/issues/737

**Comment by cstiens** [comment]
Here's an initial sketch of the UI for migration. The first step is showing a message within the conversations view. We may also want to send a system notification for this. The second step is getting the new account set up.

<img width="711" alt="zom-migration-v1" src="https://cloud.githubusercontent.com/assets/1434597/25096261/1764eed8-2365-11e7-8c02-c575707bde1c.png">

**Comment by cstiens** [comment]
Still need:
- What should the message to your friends say?
  @chrisballinger are there any actions your contacts have to take after you send this message?
- Should OMEMO TOFU handle the key? (In this case, the friend would not receive the key.) On our call we decided OMEMO TOFU would handle it. @n8fr8 any input here?
- Adding new jabber info to vCard (Mikael is doing this)
- Migrate the trust status of the keys (Chris is adding this to the list)

**Comment by N-Pex** [comment]
@cstiens could you please have a look at text and design for this?

![simulator screen shot 19 apr 2017 15 37 40](https://cloud.githubusercontent.com/assets/5418622/25196114/f0ebb9da-253f-11e7-98c2-5f3f0d1c9d21.png)

**Comment by n8fr8** [comment]
This is great, fast progress! @chrisballinger one concern or thought I have is if we can keep the same remote contact for the person moving to the new account, rather then creating a new duplicate contact. I know there is a 1-to-1 relationship now between contacts and accounts, but is that necessary? Can you set a new "default" account, or just change the account entry id for the existing contacts?

**Comment by n8fr8** [comment]
Let's also keep focused on the fact that none of the users known what a JID is or what a forward account is. We want to do as much automatically as possible, focusing on the novice user, who will either click "ignore" or will just click "ok ok ok ok". Can we just make it all happen within one "ok"?

**Comment by n8fr8** [comment]
I think adding the forwarding address in the VCard is a GREAT Idea, and we should just auto approve those if they show up.

**Comment by n8fr8** [comment]
Also, related to this, I think we need to accept messages from people not in my roster. Roster subscription is only for presence, and shouldn't be used as a block list. This would make the process of starting OMEMO and sending messages after a migration much more fluid.

**Comment by chrisballinger** [comment]
Accepting unsolicited messages wouldn't help OMEMO because the bundles
require PEP, and that's not available until presence subscription is
granted. :-\

**Comment by n8fr8** [comment]
Oh... didn't realize PEP is tied to presence.

**Comment by n8fr8** [comment]
Alright, well let's keep this focused on the migration specific issues. Just thought, we could streamline the approval process during the migration with this, but apparently not.

**Comment by chrisballinger** [comment]
Slight issue with some parts of this plan... Dukgo seems to have already been shutdown. I haven't been able to access the server at all for the last few days. Their XMPP port is open/listening but the server seems to not be responding.

This feature will be generic enough to allow you to migrate any account from server->server so I'll be able to test with that, but at the moment I can't add any dukgo accounts to test because we don't let you add accounts on broken servers. For now I can add another entry to the `OTRServerDeprecation` list for another (working) server to test the "shutdown warning" code path.

**Comment by N-Pex** [comment]
Maybe new accounts are not allowed, but I can still login with my old one(s). You can probably get one of my old ones to test with if you want. But yeah, testing with another server should work equally well I guess.

**Comment by chrisballinger** [comment]
@N-Pex Ah you're right! Using an old account still works.

**Comment by chrisballinger** [comment]
@N-Pex When you pull the upstream code, could you hook this up?

```objc
- (IBAction)didPressStartMigrationButton:(id)sender {
    // TODO: fill this in
    OTRAccount *oldAccout = nil;
    OTRAccountMigrationViewController *migrateVC = [[OTRAccountMigrationViewController alloc] initWithOldAccount:nil];
    migrateVC.modalPresentationStyle = UIModalPresentationFormSheet;
    [self.navigationController pushViewController:migrateVC animated:YES];
}
```
