### ISSUE TITLE
unread count not decreasing?

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#28]
"Top left where it says "Chat" the number keeps going up as I chat even though I've read the message (screenshot IMG_7147.jpg)"

![img_7147](https://cloud.githubusercontent.com/assets/30851/11802737/f5dd9f78-a2c1-11e5-9ed3-045ea3b1aa05.jpg)

**Comment by davidchiles** [comment]
This should be fixed [here](https://github.com/ChatSecure/ChatSecure-iOS/commit/748197c8537864694662fecc88be75bfe3d0cd1e).
