### ISSUE TITLE
Pull updated xmpp-server-list after pulling latest upstream

### ISSUE THREAD

**Issue by chrisballinger** [zom/Zom-iOS#287]
@N-Pex There is code that filters out servers that don't support XEP-0357 and XEP-0363, and the old json file doesn't include that. The latest server list includes Zom at the top so behavior shouldn't change otherwise.

https://github.com/ChatSecure/xmpp-server-list

If this change isn't pulled, the Zom server will not appear!

**Comment by N-Pex** [comment]
Ok, thanks!
@chrisballinger, @n8fr8 Is there a reason to use a Zom-specific server list, or can I just use master?

**Comment by n8fr8** [comment]
Master is fine as long as home.zom.im server is the default.

**Comment by N-Pex** [comment]
Ok, great, closing this then.
