### ISSUE TITLE
Inbox / Archive Toggle in Conversations View

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#290]
After migration, the inbox view shows outgoing friend requests for each active conversation you’ve had in your convo view (i.e. “with pending approval” next to the person's name).

The functionality is in the core migration code. Mikael is working on getting the toggle to show up in Zom.

**Comment by N-Pex** [comment]
Ok, toggle now shows.

@cstiens Unsure if it is supposed to be up in the navigation bar (instead of Zom|Chats) or under it? Currently under it.

**Comment by cstiens** [comment]
It should be in the header.

**Comment by cstiens** [comment]
Done!
