### ISSUE TITLE
Active / Archive in Friend View

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#291]
Scenario: I migrate to zom, all of my old contacts are moved to archive.
My new contacts will show in my active view (even if they have dukgo accounts) with pending approval.

If a friend has migrated, move their Dukgo account out of the active view and into the archive view. This portion of the issue is currently assigned to Chris in #289.

**Comment by cstiens** [comment]
@N-Pex how close are we to having this toggle in the friends view?

**Comment by N-Pex** [comment]
@cstiens I think I got it working now in the next build.

**Comment by cstiens** [comment]
Done!

**Comment by cstiens** [comment]
Done!
