### ISSUE TITLE
Auto-remove expired dukgo accounts

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#296]
**Questions**
- By default, will Dukgo accounts still be displayed in the UI even after they won't be accessible?
- If we want to clear them out — Can we auto-remove contacts hosted on Dukgo after May 9th? 
- For a personal account — Can we auto-remove your Dukgo account from your account view after May 9th?
- Are there any bad side effect to auto-deleting these accounts?

**Comment by chrisballinger** [comment]
Automatically deleting an account deletes all attached buddies, and
deleting each buddy removes your old message history with them, so it
should be avoided.

**Comment by cstiens** [comment]
I'm going to close this issue, because I don't think it's something we need to put our resources toward at this point.
