### ISSUE TITLE
Remove status indicators

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#297]
@chrisballinger to indicate is brand specific in upstream code.
@N-Pex to hide status indicators in Zom.

Please correct me if I've missed something here.

**Comment by cstiens** [comment]
@chrisballinger can you work on your side of this task today?

**Comment by chrisballinger** [comment]
`OTRBranding.showsColorForStatus` has been added upstream in https://github.com/ChatSecure/ChatSecure-iOS/commit/f9031747e898d995983041632615e1faa677e98f. This value will be false in Zom, and result in no status indicators, unless the `ShowsColorForStatus` is accidentally set to true in Zom's `Branding.plist` file.

**Comment by cstiens** [comment]
Done. Thanks!
