### ISSUE TITLE
Switch to "new format" OMEMO

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#298]
Related to this: https://github.com/vanitasvitae/smack-omemo/issues/24

**Comment by cstiens** [comment]
@chrisballinger has this been done?

**Comment by n8fr8** [comment]
We really need this now, since the latest Smack 4.2.2 we are using in Zom Android silenty drops the legacy format messages

**Comment by chrisballinger** [comment]
Resolved upstream: https://github.com/ChatSecure/ChatSecure-iOS/commit/ef504b351dd66ec7314900736ff6dc15941367c3
