### ISSUE TITLE
Zom on iOS feedback - QR Code

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#3]
Touch 6
iOS version 9.0

I upgraded Zom to the latest version without uninstalling the previous version and the 'Add Buddy' option didn't have QR or Share option.
Showed my QR Code from the share option after choosing 'Share' option from my account in the Settings.
Used Zom on Android to Scan, got a notification in Android that the contact is added, but doesn't appear in both Zom on iOS and Android.
Reinstalled Zom and in the onboarding process, Zom crashed when I selected Scan QR option. reinstalled Zom twice after this but kept crashing.

**Comment by chrisballinger** [comment]
This was fixed in the Android version
