### ISSUE TITLE
Show prompt to move to friend's new account based on V-card info

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#300]
In version 1.0.15 (70), this view did not show when the old account was opened. Note: This test was done when migrating from an account hosted on zom servers. @N-Pex it should still show up, right?

![chat view-friend-newaccount](https://cloud.githubusercontent.com/assets/1434597/25667292/b3eb22ce-2fe8-11e7-8cda-881ecdd8b09c.png)

**Comment by cstiens** [comment]
On the migrated phone, this view was shown under the old account of the person that migrated. See issue #302 for details on the migrated account being displayed in the migrator's friends list. 

![img_2246](https://cloud.githubusercontent.com/assets/1434597/25674958/5d8027f8-3002-11e7-949f-48566eb5fefd.PNG)

**Comment by cstiens** [comment]
@N-Pex This is showing up in some cases and in some not. In our tests from today, it showed up for some contacts once they migrated, but not all. I haven't been able to see any reason why it has showed up for some people and not others.

**Comment by N-Pex** [comment]
For me it never showed up today, that's why I created this: https://github.com/zom/Zom-iOS/issues/320

The receiving buddies never fetch the updated vcard for the migrated user, so they never know that the migrated used has migrated!

**Comment by N-Pex** [comment]
Really hard to debug down deep in the libraries.

**Comment by chrisballinger** [comment]
Yep, vCards are a mess and horribly buggy.. on both the client and server.
