### ISSUE TITLE
App is auto-sending multiple 'new account' info messages

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#301]
The second messages is sent 6 minutes after the first one.

**Comment by cstiens** [comment]
![img_2245](https://cloud.githubusercontent.com/assets/1434597/25675052/af4092b2-3002-11e7-8057-642c5944184e.PNG)

**Comment by cstiens** [comment]
Connected to #303

**Comment by chrisballinger** [comment]
Maybe fixed here: https://github.com/ChatSecure/ChatSecure-iOS/commit/391dd28733c0cf96ae22332477b5e360bb2044c8

**Comment by cstiens** [comment]
I believe this is fixed. We have not seen this happen again.
