### ISSUE TITLE
The account I migrate to (new account) is shown in my friends list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#302]
After I migrate, my new account is active and set to the default. It is also listed in my friends list. I am my own friend. ;) It should not show in the friends list.

**Comment by cstiens** [comment]
freedomhouse.4e4d@home.zom.im is the new account on the phone that migrated.
freedomhouse@home.zom.im is the 'old' account (the one that was migrated from)

![img_2243 2](https://cloud.githubusercontent.com/assets/1434597/25675228/43a1c3ae-3003-11e7-82d9-bde2ef23dc07.PNG)

**Comment by chrisballinger** [comment]
Maybe fixed here: https://github.com/ChatSecure/ChatSecure-iOS/commit/391dd28733c0cf96ae22332477b5e360bb2044c8

**Comment by cstiens** [comment]
We haven't seen this happen again, so I think it's fixed. Great job!
