### ISSUE TITLE
Contacts appearing multiple times in friends list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#303]
Every time, the old account sends out new account info to your contacts, it lists that friend again in the friends list (in gray).

![img_2245](https://cloud.githubusercontent.com/assets/1434597/25668220/ae66ee34-2feb-11e7-953d-61b6ac996bb5.PNG)

**Comment by chrisballinger** [comment]
Maybe fixed here: https://github.com/ChatSecure/ChatSecure-iOS/commit/391dd28733c0cf96ae22332477b5e360bb2044c8
