### ISSUE TITLE
Old chat should move to archive in convo view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#305]
![img_0223](https://cloud.githubusercontent.com/assets/1434597/25675721/1d9b97aa-3005-11e7-97ec-edc415c7c4de.PNG)

![img_0224](https://cloud.githubusercontent.com/assets/1434597/25675724/1fbbc65e-3005-11e7-9eca-64f6585f26f1.PNG)

**Comment by chrisballinger** [comment]
@N-Pex I think this is related to Zom overriding the upstream database view. It should point to `OTRFilteredConversationsName` now.

**Comment by N-Pex** [comment]
@chrisballinger I don't think so, the conversations view is not overridden by Zom, it's only the compose view.
