### ISSUE TITLE
Migration: old account should be signed out, no auto login

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#306]
Once migration is done, we should automatically log out of the old account, and set the pref to not automatically log in

**Comment by n8fr8** [comment]
Actually we don't want to logout of the old account... because people won't get messages from their others friends who haven't migrated. Anyhow....

**Comment by cstiens** [comment]
After our group test today, we decided that Zom should auto logout after migrating. This would prevent a few things from happening that are currently causing confusion:
- User won't get double friend requests; Therefore, you wouldn't be adding your friends' new account to your old and new account.
- Friends would not be able to chat with your old account. See #307 

We would also need to disable the flag to auto-login for this case.

@n8fr8 please fill in details as needed.

**Comment by cstiens** [comment]
@N-Pex This is working in some cases, but not all. In our tests, it did log out automatically about 50% of the time.

**Comment by N-Pex** [comment]
@cstiens Stable Internet? I find this strange, since we never added code to log out! The only thing happening now is that "auto-login" is set to false, so why you would be logged out is beyond me.

**Comment by cstiens** [comment]
That is weird. Maybe I'm confused and I logged out manually.. I'll test this again tomorrow. 
Either way, we do need to log the user out of the dukgo account after they migrate. @N-Pex any blockers in implementing this?

**Comment by chrisballinger** [comment]
Unfortunately cleanly logging out after migration is pretty much impossible because everything is done asynchronously all over the place in different queues. You could log out after a short fixed delay, like 5-10 seconds, but during poor network conditions it may result in an incomplete migration.

**Comment by N-Pex** [comment]
Ok, I've now added a 60 second delay before logout. It may or may not be enough. The timer may or may not fire if we enter background. Still better than nothing though.

**Comment by cstiens** [comment]
Great. I think a 60 second delay is better than nothing. @n8fr8 do you think 60 seconds is sufficient for the delay based on your experience with bad internet in India?
