### ISSUE TITLE
Need more padding at the end of the convo view list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#314]
This screenshot shows the end of the scroll.

![img_0239](https://cloud.githubusercontent.com/assets/1434597/25762834/f446524e-31a5-11e7-8070-7106e41f5073.PNG)

**Comment by N-Pex** [comment]
@cstiens Why did you remove the label, did you test this on latest?

**Comment by cstiens** [comment]
Yes, we tested it on the latest and had the same issue.
