### ISSUE TITLE
Update wording for new account message

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#315]
Update wording for "my new account information" message to "I've upgraded my account. Zom with me at username.home.zom.im"

![screen shot 2017-05-05 at 3 29 24 pm](https://cloud.githubusercontent.com/assets/1434597/25763192/8192f9bc-31a7-11e7-9b70-20837c503ca3.png)

**Comment by N-Pex** [comment]
... with the minor tweak that there is a colon after "at" (because of how the string is built up in code).

**Comment by cstiens** [comment]
Done.
