### ISSUE TITLE
Build 72 lags

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#317]
When app first launches it's lagging. This can be reproduced by trying to quickly switch between tabs.

Force quitting and restarting doesn't fix it. For Nathan, it eventually just came out of it. For TL, it was slow during the whole test.

**Comment by n8fr8** [comment]
I think we got past this? I haven't noticed it as much.

**Comment by chrisballinger** [comment]
It's not fixed, but it should be intermittent. It's caused by YapDatabase
not being able to finish its WAL flush during the 30s background intervals.

**Comment by cstiens** [comment]
Didn't happen at all during testing.
