### ISSUE TITLE
Update text from 'Switch' to 'Chat Now'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#318]
When an old account is wanting to chat with a friend who has upgraded the button needs to read  'chat now'. Below image is correct. 
![screen shot 2017-05-05 at 3 33 35 pm](https://cloud.githubusercontent.com/assets/1434597/25763284/f1fdc6a0-31a7-11e7-9db5-98c592a48bf0.png)

**Comment by cstiens** [comment]
@N-Pex This is minor, but the text still says 'switch'. Since you'll be in the code for the invite links, can you go ahead and change this button text to 'Chat Now'?

**Comment by N-Pex** [comment]
Should be fixed with new language fixes in version 81, let's just verify.

**Comment by cstiens** [comment]
Done. Perfect!
