### ISSUE TITLE
"Upgrade Account" prompt not going way after upgrade

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#319]
I have one Dukgo account, that was not logged in.
I was prompted to "upgrade account" so I did. The upgrade completed successfully, or so I was told. 
I clicked "done" and I believe it disappeared.
However, when I returned to that chat list view, it was there again. No matter how many times I upgraded, it was still there.

Now, when I went to my Dukgo account to make sure I was logged in, and THEN ran the upgrade, it completed successfully, and the upgrade prompt never returned.

**Comment by cstiens** [comment]
We've had a similar experience on two devices today (build 74). The prompt to upgrade goes away after you upgrade as long as the user is still logged in to the dukgo account. Once the dukgo account logs out, the prompt to upgrade returns. 

@N-Pex @chrisballinger This isn't really a deal breaker for the first release, but it could cause confusions and will definitely cause people to upgrade more than once.

**Comment by N-Pex** [comment]
Unfortunately, this one is also related to the vCard support. For some reason, the vCard loses the "forwarding jid" (jabberid) value, so suddenly we don't know that the account has migrated.

A hackish workaround would be to store "migrated accounts" in the user defaults object, so we would never show that prompt. I'll look at fixing this tomorrow morning.

**Comment by n8fr8** [comment]
Perhaps you can keep a temporary variable in memory for that session, so that you can immediately dismiss the UI and not show it again, once the user has migrated. Then, the next time you open the app, if there are any dukgo accounts that have the "auto login" flag set, you can show it again? That is how I determine whether or not to show it.

**Comment by N-Pex** [comment]
Ok, build 76 will have this.

@n8fr8 Could you please push it when it's done "processing"? Thanks!
