### ISSUE TITLE
Change add 'Buddy' to 'Friend'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#321]
@N-Pex The text on this changed with build 72 (I believe). Can you change the text back to friend?
It shows in the inbox and archive.

![img_2273](https://cloud.githubusercontent.com/assets/1434597/25860607/a012f4ac-34a7-11e7-87ba-3c85416e40e4.PNG)

**Comment by N-Pex** [comment]
Ok, done.
