### ISSUE TITLE
"Me" tab should show last logged in account

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#322]
The "Me" tab is only showing the first account currently. If a user migrates to a new account, we need to show the new account. This can be done by either having an option to change the default account, or to only show the most recent logged in account.

**Comment by N-Pex** [comment]
The "Me" tab will show your current "default" account. After migration we set your new one as default.

I was waiting for a merge of a PR upstream, but now also re-added the "set as default" in the details view for manual change.
