### ISSUE TITLE
Banner issues - iPad

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#324]
When selecting 'start chat' from a friend's profile. Also, when in my profile view banner for 'Active/Archive' still appearing. 
![img_0135](https://cloud.githubusercontent.com/assets/1434597/25869855/8f5b2510-34c7-11e7-989b-645c18445cea.PNG)
![img_0136](https://cloud.githubusercontent.com/assets/1434597/25869854/8f598c14-34c7-11e7-8d7a-5532c10da396.PNG)
![img_0137](https://cloud.githubusercontent.com/assets/1434597/25869856/8f5cadb8-34c7-11e7-844e-7d0a119abf7a.PNG)

**Comment by N-Pex** [comment]
@cstiens I was not able to reproduce this, but did some other fixes related to the title that may well fix this. Could you please re-test with next version? Does this happen every time or only after special steps?

**Comment by cstiens** [comment]
I will test in the next version, and track the steps taken to see if there are specific things causing it.

**Comment by cstiens** [comment]
The second two cases were happening when I selected a contact from the friends list, which took me to the info view, where I then tapped 'start chat'.

This is fixed in build 75.
