### ISSUE TITLE
Multiple push notification messages sent

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#325]
53 push notifications sent simultaneously saying 'your account will expire in 8 days'
![img_0245](https://cloud.githubusercontent.com/assets/1434597/25870605/502165aa-34ca-11e7-8d6a-dcfa397dd0a6.PNG)

**Comment by N-Pex** [comment]
This is because you have been testing a lot with the same device, migrating over and over. Should not happen for real users. Nevertheless, maybe an added "remove all old" before scheduling a new one would be good.

**Comment by N-Pex** [comment]
Should be fixed by this PR: https://github.com/ChatSecure/ChatSecure-iOS/pull/765
