### ISSUE TITLE
In new account message sent to friends, include invite link

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#326]
Instead of showing the JID, display the invite link. When a user taps on the link it would open a new chat with the new account. @n8fr8 

Side note: Currently, when you tap on the JID link it opens the mail app on the iPhone, which is confusing.

**Comment by cstiens** [comment]
> Clickable JIDs shouldn't open up in the email composer, but there's no way
to tell the difference, so users would need to be given a choice at runtime.
@chrisballinger Are you saying that we don't have control over the JID links opening in email? Can we simply disable the JID link, and add the clickable invite link?

>Another problem with including the invite link in the message is that it's very long. 
I agree with you. It is long. But, it does link users into the chat where they need to be, which is a better experience overall, especially if the v-card info doesn't show up for them.

**Comment by n8fr8** [comment]
If the user doesn't have an app that supports the zom.im links, it will open to a web page, where the JID is displayed and the standard Xmpp invite link is enabled.

https://zom.im/i/#c3VwZXJib3dsbGxsbC41N2RmOTdjNy5kZjc4YmMxMkBob21lLnpvbS5pbT9vdHI9ODA4RkEzRkRBOEQ4OTNGNzIyNjZDNTRDMjJFMDc0QzNERjc4QkMxMiZuaWNrbmFtZT1zdXBlcmJvd2xsbGxs

We should improve the layout on that page a bit, but it does work.

**Comment by N-Pex** [comment]
@n8fr8 Hm, while testing this now with build 75, the link that I get to open in the app is:

xmpp:?subscribe&otr-fingerprint=ke.test0051@home.zom.im%1BOL@

Not sure why, but this doesn't seem right does it?

**Comment by n8fr8** [comment]
it does not. i need to fix that. something is off in the parsing.

**Comment by n8fr8** [comment]
I just stepped through this in my debugger on Chrome on my Linux desktop, and it is working fine. The base64 decoding and parsing is as it should be. Maybe there is an issue on mobile safari or some other locale issue.

**Comment by n8fr8** [comment]
var Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(e){var t="";var n,r,i,s,o,u,a;var f=0;e=Base64._utf8_encode(e);while(f<e.length){n=e.charCodeAt(f++);r=e.charCodeAt(f++);i=e.charCodeAt(f++);s=n>>2;o=(n&3)<<4|r>>4;u=(r&15)<<2|i>>6;a=i&63;if(isNaN(r)){u=a=64}else if(isNaN(i)){a=64}t=t+this._keyStr.charAt(s)+this._keyStr.charAt(o)+this._keyStr.charAt(u)+this._keyStr.charAt(a)}return t},decode:function(e){var t="";var n,r,i;var s,o,u,a;var f=0;e=e.replace(/[^A-Za-z0-9+/=]/g,"");while(f<e.length){s=this._keyStr.indexOf(e.charAt(f++));o=this._keyStr.indexOf(e.charAt(f++));u=this._keyStr.indexOf(e.charAt(f++));a=this._keyStr.indexOf(e.charAt(f++));n=s<<2|o>>4;r=(o&15)<<4|u>>2;i=(u&3)<<6|a;t=t+String.fromCharCode(n);if(u!=64){t=t+String.fromCharCode(r)}if(a!=64){t=t+String.fromCharCode(i)}}t=Base64._utf8_decode(t);return t},_utf8_encode:function(e){e=e.replace(/rn/g,"n");var t="";for(var n=0;n<e.length;n++){var r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r)}else if(r>127&&r<2048){t+=String.fromCharCode(r>>6|192);t+=String.fromCharCode(r&63|128)}else{t+=String.fromCharCode(r>>12|224);t+=String.fromCharCode(r>>6&63|128);t+=String.fromCharCode(r&63|128)}}return t},_utf8_decode:function(e){var t="";var n=0;var r=c1=c2=0;while(n<e.length){r=e.charCodeAt(n);if(r<128){t+=String.fromCharCode(r);n++}else if(r>191&&r<224){c2=e.charCodeAt(n+1);t+=String.fromCharCode((r&31)<<6|c2&63);n+=2}else{c2=e.charCodeAt(n+1);c3=e.charCodeAt(n+2);t+=String.fromCharCode((r&15)<<12|(c2&63)<<6|c3&63);n+=3}}return t}};

var inviteLink = document.location.href;

inviteLink = Base64.decode(inviteLink.substring(inviteLink.indexOf("#")+1));
var inviteUser = inviteLink.substring(0,inviteLink.indexOf("?"));
var inviteKey = inviteLink.substring(inviteLink.indexOf("otr=")+4).substring(0,40);
var xmppLink = "xmpp:" + inviteUser + "?subscribe&otr-fingerprint=" + inviteKey;

document.getElementById("contactinfo").innerHTML="<a style=\"color:white\" href=\"" + xmppLink + "\">" + inviteUser + "</a>";

document.getElementById("qrcode").onclick = function() { 
		document.location.href=xmppLink;

        };
document.getElementById("buttonaddfriend").onclick = function() { 
		document.location.href=xmppLink;

        };

**Comment by cstiens** [comment]
When you tap on the invite link in build 75, it takes you to the zom website with the button to 'add friend'. On the iPhone 7, when I tap 'add friend' it took me back into the old chat with the dukgo account.

On the iPhone 6, when I tap 'add friend' on the website, it prompts me to open in Chatsecure. As a normal user would, I didn't read the text and just tapped Open. 
On the iPad, when I tap 'add friend' on the website, it prompts me to open in Chatsecure.

**Comment by cstiens** [comment]
@N-Pex please see my notes above.

**Comment by N-Pex** [comment]
@cstiens The error is server side, it does not give back good links (I think)

**Comment by N-Pex** [comment]
As for the xmpp: protocol being used both by ChatSecure and Zom, maybe we should use a zom: protocol or something?

**Comment by chrisballinger** [comment]
I cannot seem to override the handling of https links to prevent them from opening in Safari. 

There is no way to choose which app handles certain URIs, so if you want to ensure that only Zom can open the links, you'll need to handle a Zom URI, ideally in the same format as the XMPP URIs. If you want to allow desktop apps and compatibility with other apps, you should still offer an XMPP URI though.

**Comment by cstiens** [comment]
@N-Pex is there a clear and quick way forward?

If not, @n8fr8 I **don't** think we should ship it with the links not working correctly. Rather, go back to showing the JID (preferably unlinked).

**Comment by N-Pex** [comment]
@cstiens @n8fr8 Ok, so I added code to enter a chat with the newly accepted invite, but this seems to bring other problems to the surface. I at one time ended up with both test users having the other as "pending" after the accepted invite. Also, I think there are database issues with the current code, since the invite would just "create a new user", but we already have like a placeholder for it, because of the incoming friend request after migration.

Anyway, uploaded as Version 77, so you can try if you like.

Other than that, we are running out of time for tweaks.

**Comment by n8fr8** [comment]
I don't understand why the https://zom.im links aren't being handled. When a receive a zom invite link through Messages, it opens in Zom just fine. Why aren't zom invite links from without our own app being handled in the same way?

xmpp: links are the way to go ultimately, and the edge cases for people with both apps installed are rare, and mostly just us.

Otherwise, will test the latest build. However more urgent is the TLS cert pinning problem.

**Comment by chrisballinger** [comment]
the https link handling is designed for other apps to deep link to your
app, but once you're inside your app iOS assumes that you want to go to the
actual link.
