### ISSUE TITLE
If you're friends with an account that is signed out, the chat shows 'pending approval'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#330]
@N-Pex @chrisballinger (build 74) Again, this isn't a deal breaker because it doesn't affect your ability to chat with new accounts. It is confusing though.

**Comment by N-Pex** [comment]
Yes, something is off here. In my testing, the buddy of a migrated user will (after a while?) see the OLD account of the migrated user as "Pending Approval". Seems strange.

@chrisballinger In handleRosterItem -> updateBuddy I see the data packet: <item jid="micke.test0051@dukgo.com" ask="subscribe" subscription="from"/>, so definitely the mutual relationship is ended somewhere...

**Comment by cstiens** [comment]
After testing today, I only found this to happen on the iPad.
