### ISSUE TITLE
Add Tibetan translation for 'Add friend'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#332]
@N-Pex 
![img_0255](https://cloud.githubusercontent.com/assets/1434597/25961109/bb1ea99c-363e-11e7-8d6a-065dbea1f6b0.PNG)

**Comment by N-Pex** [comment]
@cstiens Yes, I don't have the string for this!

**Comment by cstiens** [comment]
Add buddy
གྲོགས་པོ་སྣོན། 

Also: Here's a link to the google doc with all the translations in case you need it handy—https://docs.google.com/document/d/1WIL1udV-OgR-UFOTDCjWWZILBA9AivFTsz64g9tmbV8/edit
