### ISSUE TITLE
home.zom.im certificate pin change is blocking logins

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#333]
home.zom.im's letsencrypt cert expired, so the pin value is new and different than what is built into the app.

New users of Zom, using the app store release, are prompted to save/approve the cert. Existing users are not prompted or told there is a problem. They simply can't login.

This is an issue with the public, production release of Zom iOS. We need to fix this right away in the build we are submitting for release to Apple for approval, by changing the cert pin.

There is no way to roll back to the old cert, because (OF COURSE!) it expired yesterday,.

**Comment by chrisballinger** [comment]
In the future this can be avoided by reusing the existing private key during Lets Encrypt renewal. We pin to the public key, not to the leaf node itself.

Additional error messages can be added to make this problem more apparent to the user. Existing users can fix this problem before the update by going to Settings -> Account (i) -> Edit Account -> Checkmark (to login) -> Cert dialog approve.

**Comment by n8fr8** [comment]
Great. I have asked our server admin to regenerate a new cert based on the previous private key. 

We should avoid error messages, but yes let's consider how we warn/educate the user in the future of the key changes.

**Comment by cstiens** [comment]
> Great. I have asked our server admin to regenerate a new cert based on the previous private key.

@n8fr8 Once we have the new 'cert based on the previous private key', do we just need to change to it in the app? Or are there other steps we need to take to ensure that existing users can log in?

**Comment by chrisballinger** [comment]
Nothing to change in the app, assuming the existing code works properly. Otherwise, see my workaround above.

**Comment by n8fr8** [comment]
This should be fixed now. I tested with build 77, and I didn't get a prompt about saving a new certificate.

**Comment by chrisballinger** [comment]
Awesome. Do you have the process to reuse key w/ certbot documented
anywhere?

**Comment by n8fr8** [comment]
Nick and I are working on it and will debrief Monday, after both our children celebrate their birthdays today/this weekend. What timing! :)
