### ISSUE TITLE
Share media from the Photos app to Zom

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#338]
I will look at the standard workflow for this process across other chat apps, but this seems to be logical.
- zom would be an option on the share sheet
- pop up your list of contacts in Zom
- show Zom sending the message 
- then go back to Photos app

**Comment by N-Pex** [comment]
Turns out this is very problematic and requires some major refactoring to pull off. This is because a "share extension" is not allowed to open up the "containing app" - it can only share user preference files and share code, via a common library. So we would need to refactor out quite a bit of code into a lib that's shared between Zom/CS and the share extension.

**Comment by n8fr8** [comment]
We need to talk about this again.

**Comment by N-Pex** [comment]
@tladesignz For selecting friend and sending, have a look at handleImport in ZomImportManager.swift file. It's used for sharing audio files to Zom.

**Comment by N-Pex** [comment]
@tladesignz Nice work! Could you also add the icon to the share extension?

I only tested it briefly, but noticed that by default the share extension was disabled in the photo app. Is there a way we can enable it/ask the user to enable it?

**Comment by tladesignz** [comment]
@N-Pex:
- Share extension icon:
  Not sure, what you mean? When I tried it, the app icon was automatically used.

- Disabled sharing button:
  Nope, doesn't look like: https://stackoverflow.com/questions/34821475/how-does-ios-determine-which-share-extensions-are-enabled-by-default

**Comment by N-Pex** [comment]
@tladesignz Ok, thanks for looking into it. I noticed in the simulator for iPhone 7 iOS 10.1 the icon for the share extension was not showing up, but seems to work on later devices.

**Comment by tladesignz** [comment]
@N-Pex I witnessed this behaviour myself. However, this seems a bug with the simulator. In later runs/reinstalls it should be there. I have an actual iPhone 7 running iOS 10.3.3 and the icon is there.

Additionally, I read on the net, that all extensions use the containg app's icon, *except* action extensions. (Which ours is not). E.g. compare this StackOverflow: https://stackoverflow.com/questions/39001813/how-do-you-provide-an-icon-for-an-action-extension
