### ISSUE TITLE
Need to be able remove files (photos, etc) that are shared in Zom

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#341]
Being able to do this from the photostream makes sense.

**Comment by N-Pex** [comment]
What's the expected result of this? Delete stuff that we have downloaded (but that will be downloaded again if we hit that chat history) or somehow delete files we have uploaded to the server (we need to figure out if/to what extent that is possible?)

**Comment by n8fr8** [comment]
I think it is about clearing local storage, or perhaps just removing one item. If you are in a group chat or talking with someone and they send something that is inappropriate, or that you just want to see once and remove, for instance.... or maybe you are out of space, and want to clear anything "older than X", etc.

I had also thought about having an auto-delete after a certain time feature, with the ability to easily save/fav items.

**Comment by cstiens** [comment]
> somehow delete files we have uploaded to the server (we need to figure out if/to what extent that is possible?)

It seems like it may be important to clear stuff from our server that people delete. If they delete it, they don't want it to exist anymore. So, it seems odd that we would keep it, right?


> I think it is about clearing local storage, or perhaps just removing one item.

Yes. The first step is just being able to remove a single photo from your device when you're viewing it. Secondly, it would be nice to multi-select in the photostream.

> I had also thought about having an auto-delete after a certain time feature, with the ability to easily save/fav items.

I've been thinking about this too. I think about it as 'expiring' media that's old. Then, like you said, Nate, always keeping favorites. Let's tackle this in our second round of media enhancements.

**Comment by cstiens** [comment]
@N-Pex UI for deleting from a single chat in https://github.com/zom/Zom-iOS/issues/386
