### ISSUE TITLE
Build 81 crashes on OS version 9.3.4 when sending text messages

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#344]
On OS 9.3.4 (iPhone SE), build 81 crashed 90% of the time that Rosa sent messages to Nathan. @N-Pex Can you look into this. Let me know if you need more info. Rosa was sending text messages only when the crashes occurred.

**Comment by N-Pex** [comment]
Most probably this was because of incoming photos earlier in the thread. Once those were read the migration message detection code would crash the app (issue #342). Please retest this in version 83 or later.
