### ISSUE TITLE
OMEMO key not shared, Using OTR

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#345]
Hey @chrisballinger This is similar to the issue we were having the other day. Both contacts are on the Zom server. The contact that says its using OMEMO has the OMEMO key for the friend they are chatting with. The friend (saying it's using OTR) does not have the OMEMO key for the contact.

![img_0301](https://user-images.githubusercontent.com/1434597/27388466-2a7b6bd0-5661-11e7-8857-6458e0c9ae61.PNG)

**Comment by chrisballinger** [comment]
That's strange. Once the other side receives your OMEMO message it should be able to start the session. I think this separate from the presence bug, but I am sure that it isn't helping.

This may be related to a corrupt key, but I really can't tell from here.

**Comment by N-Pex** [comment]
I think this is just a result of bug #337.
