### ISSUE TITLE
HTTP Upload is failing due to Zom XMPP server HTTP/TLS configuration issue

### ISSUE THREAD

**Issue by chrisballinger** [zom/Zom-iOS#346]
`https://home.zom.im:5281` fails the ATS certificate checks in iOS.

cc @n8fr8

**Comment by n8fr8** [comment]
It is a "no matching cipher" issue, which means the XMPP server that is hosting that port, is different than the Nginx web server in terms of ciphers. It is also different than what the XMPP port must offer. So strange.
