### ISSUE TITLE
Info view for group chat - Show members and avatar

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#348]
@N-Pex Please disregard the top portion of this mockup for now. I need to work with the design a bit more to determine a better way to add existing zom contacts to the group. Showing the members of the group and their avatars in this layout is something that is ready to implement, though. Thx!

**Comment by cstiens** [comment]
Here's the latest design for this view. @N-Pex the idea is to streamline the profile views across the app on iOS and Android, which is why this mockup looks different than the current view of profiles in Zom iOS. We can chat more about it on the scrum.

![profile-group2](https://user-images.githubusercontent.com/1434597/28336037-11ca2c00-6bc6-11e7-8364-dc5d0a02ccea.png)

**Comment by cstiens** [comment]
@N-Pex Here's the icon for the QR code—
[ic_qr.pdf](https://github.com/zom/Zom-iOS/files/1163513/ic_qr.pdf)
![ic_qr](https://user-images.githubusercontent.com/1434597/28435725-d4703468-6d59-11e7-9ec0-65c548fbc45a.png)
![ic_qr 2x](https://user-images.githubusercontent.com/1434597/28435726-d4770cb6-6d59-11e7-8978-536e34649430.png)

**Comment by N-Pex** [comment]
@cstiens Ok, thanks! One question: which part of the view should be scrollable?

**Comment by cstiens** [comment]
@N-Pex Here's an icon font that contains only the native ios share icon. The size is 1 KB compared to 778 bytes (which is the size of the svg outside of a font). We can add more icons to this font in the future if we need, but I wanted to provide this for starters.

[ios-icon-font.ttf.zip](https://github.com/zom/Zom-iOS/files/1195133/ios-icon-font.ttf.zip)

**Comment by cstiens** [comment]
> Ok, thanks! One question: which part of the view should be scrollable?

@N-Pex All of it should scroll. :)
