### ISSUE TITLE
Voice messages still not working?

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#35]
When trying to send voice message from  iPod Touch with iOS 9.1 you get an error message and on my end (iPhone receiving) got 3 messages of long gobbly-gook.

**Comment by davidchiles** [comment]
This should be fixed [here](https://github.com/ChatSecure/ChatSecure-iOS/commit/a2b63815116e0dbc8e67388f21ad9d5d7399790c). This bug was because on iOS 9 you're not allowed http connections without setting an exception and we're making http requests to localhost. So now it's set as an exception.
