### ISSUE TITLE
App asks me to enable push every time I open it (build 86)

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#356]
Rosa keeps having this issue. Each time she opens the app to use it, it asks her to enable push.

She's on an iPhone SE running 10.3.2.

**Comment by N-Pex** [comment]
@cstiens Would be great with a screen shot of the server information, the registration info in particular. Me tab -> Gear icon -> (i) on the account -> Server Information.

What happens if she taps "reset" on that screen?

**Comment by cstiens** [comment]
@N-Pex Here's the screenshot of the server info. I'll ask Rosa what happens when she taps reset.
<img width="444" alt="server" src="https://user-images.githubusercontent.com/1434597/28840394-71e3d0a4-76bc-11e7-8bc3-4db77eba9780.png">

**Comment by N-Pex** [comment]
Does this still happen or did the fix above solve the situation?

**Comment by cstiens** [comment]
> Does this still happen or did the fix above solve the situation?

I asked Rosa and she has not seen this happen again!
