### ISSUE TITLE
Rejected due to out of date / in accurate screenshots

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#359]
We need to update our screenshots / art for the iTunes app store, as the screens we show are out of date and also, in some cases, just rendered, and not actually from the app. Apple has rejected us for this.

Can we regenerate the screenshots we show, so they are accurate and resubmit?

@chrisballinger can you help with this? 

This is a minor emergency, but can be done on Monday. Thanks!

**Comment by n8fr8** [comment]
@N-Pex if you can regen screenshots for all the sizes, update the store listing, and resubmit for release, that would be wonderful. I am going offline shortly, so don't think I can get it done in time.

**Comment by N-Pex** [comment]
@n8fr8 Ok, I can have a look. I see that you have already removed the offending screen shots(?), so shouldn't we just be able to resubmit it now, without further changes?

**Comment by chrisballinger** [comment]
You only need to generate the two biggest sizes for iPhone and iPad now:
iPhone 7 Plus (5.5") and iPad Pro 12.9"

**Comment by N-Pex** [comment]
Ok, done! Let's hope this makes Apple happy.
