### ISSUE TITLE
How do I delete contacts?

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#36]
15. Recurring - Can’t delete contacts.

**Comment by davidchiles** [comment]
Is this about removing a conversation from the list of conversations in the main table view? Or remove them from the 'buddy list' in an XMPP way?

The former is done by swiping on a table view cell from right to left just like in Messages.app

**Comment by gekhung** [comment]
I think this is for delete contacts from buddy list.

**Comment by davidchiles** [comment]
Needs some more work but making progress. https://github.com/ChatSecure/ChatSecure-iOS/commit/1dee0ff8b459c0ac5e261659ee1216c85e70b4da
