### ISSUE TITLE
Group UI: If someone sends a message that is not your friend, prompt to add

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#363]
@N-Pex We are getting feedback on the other touch points for adding people that aren't your friends, but we can go ahead and implement this one.

So, if someone sends a message to the group and they are not your friend, you will not be able to decrypt it (and see it) until you add them as a friend. Rather than displaying the message, we would show the prompt in the mockup 'Laura sent a message. Become friends to see it' along with the friend request, inline in the chat. The second screen shows what is displayed after the friend request is approved. We still need a design to handle the case that someone taps the 'x' and does not add the person. I'll work on that.

<img width="1650" alt="group-add-friend" src="https://user-images.githubusercontent.com/1434597/28932317-aa0dbf02-783e-11e7-8cf6-1fd50dcd26c5.png">

Here are the styling specs:

/* Rectangle: */
background: #F1F1F1;

/* Laura sent a message: */
font-family: SFProText-Regular;
font-size: 13px;
color: #4A4A4A;
letter-spacing: 0.32px;
line-height: 18px;

/* Nickname: */
font-family: HelveticaNeue-Medium;
font-size: 14px;
color: #000000;
letter-spacing: 0.35px;
line-height: 18px;

/* name@home.zom.im: */
font-family: .SFNSText;
font-size: 13px;
color: #000000;
letter-spacing: 0.3px;
line-height: 14px;

**Comment by chrisballinger** [comment]
You won't be able to see their previous message because of how OMEMO works. More accurately it should say something like "Become friends to see their future messages"

**Comment by cstiens** [comment]
@chrisballinger thank you for that info. Switching the wording to your suggestion sounds good.
