### ISSUE TITLE
Mute groups

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#368]
For now, let's implement mute as on/off. In the future, we can consider setting a time limit for mute. 

We also need the UI to change when muted.

**Comment by cstiens** [comment]
<img width="419" alt="screenshot 2017-08-16 14 54 07" src="https://user-images.githubusercontent.com/1434597/29382556-86de9ffc-8292-11e7-9f61-50c217eca4d3.png">

Here are the links to the material icons: 

https://material.io/icons/#ic_notifications_active
https://material.io/icons/#ic_notifications_off

**Comment by N-Pex** [comment]
Will be implemented in version 88.

**Comment by cstiens** [comment]
Done. Thanks!
