### ISSUE TITLE
UI to kick someone out of a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#369]

**Comment by tiffrobo** [comment]
Took me a minute to find this, but it's in. 

- I tried kicking someone out that was active and it works. 
I don't know what the desired workflow is, but when I kick someone out, they still have the group on their side and can send messages although they are not received. 
- **BUT**, I tried the function, and it doesn't seem to do anything if the person isn't active in the group (they are grey). 

- **Also**,  there seems to be a bug. When you kick someone out of the group messages no longer seem to be going through. So people still in the group can't talk, but if you re-add the person just kicked out you can chat again. I will do some longer testing. Maybe I'm not giving it enough time to process.


- I tried making others admins and it works. Although you can't undo this action. 
- Viewing their profile works.  

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125

**Comment by tiffrobo** [comment]
Working! Also, Re-adding 'kicked out' member back to the group works! 


**Kicked out**
- Removed from everyone in the groups' roster.
- Even though you've been kicked out you still see the group in your convo view. You do not receive new messages or notifications. And if you check the group roster you are not shown in the roster. 

**Readded**
- Show up in all group members rosters.
- Text messages fetched.
- If you were an admin you are no longer an admin. 

Device: iPhone 7
OS: 11.2.2
Device: iPhone 6
OS: 10.3.3
Device: iPad
OS: 10.3.2
Build: 126

**Comment by cstiens** [comment]
> Even though you've been kicked out you still see the group in your convo view. You do not receive new messages or notifications. And if you check the group roster you are not shown in the roster.

You can open the group from the convo view and see the full group chat. You can send messages, but they don't go through. But, as the person getting kicked out, you don't actually know that you got kicked out.

@N-Pex what can we do for the person that got kicked out?
- send a notification?
- remove the group from their convo view?
- automatically archive the group?

**Comment by cstiens** [comment]
Closing this ticket for now since it's in. I created a new one to improve the experience. https://github.com/zom/Zom-iOS/issues/596
