### ISSUE TITLE
Text for group chat friend request

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#378]
@N-Pex Here's the text as promised—"Chloe has things to say. Become friends to see upcoming chats." Also, I noticed that in build 89 it says 'User Rosa...' instead of just Rosa. See screenshot..

<img width="293" alt="screenshot 2017-09-01 09 51 21" src="https://user-images.githubusercontent.com/1434597/29975194-247b27fc-8efb-11e7-866d-a965ea20930e.png">

**Comment by N-Pex** [comment]
Fixed in 90.
