### ISSUE TITLE
Sometimes when you open the app, it looks like you don’t have an account

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#381]
**What did you do?** I opened Zom like I normally do.

**What did you expect to see?**  I already have an account and stay logged in, so I expected to see my list of conversations.

**What did you see instead?** The onboarding setup

**How did you resolve the issue?** I setup a new account. Then, once I got into the app, I saw all of the friends and conversations from my old account. I just started using Zom like normal. 

So, the new account was set as the default account (and showed in the me tab). However, since I was talking with contacts associated with my pre-existing account, I was actually using that account. The bug is that the app forced me to onboard when my account was still there. We discussed this on our Thursday scrum and @n8fr8 said it seems like it may be a database issue.

**Device model, OS and Version** iPhone
**Zom Build** 88

**Comment by n8fr8** [comment]
Onboarding is triggered due to database not being setup properly, so it looks like you have 0 accounts

**Comment by cstiens** [comment]
I haven't seen this lately. @chrisballinger did this get fixed as a result of some of the work you did?

**Comment by N-Pex** [comment]
@cstiens Any reports of this lately?

**Comment by cstiens** [comment]
We haven't seen this happen since. I believe it was solved in some of the work Chris did. I'll close it. If we see it again, we'll re-file.
