### ISSUE TITLE
Not getting messages that are queued on the server

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#382]
Some messages I send never go through. They just remain on my side with a single check.

<img width="460" alt="screenshot 2017-09-01 10 16 23" src="https://user-images.githubusercontent.com/1434597/29976178-c52f81a4-8efe-11e7-8a54-53899833423f.png">

**Comment by N-Pex** [comment]
Dup of #373?

**Comment by cstiens** [comment]
Yes, thanks. I'll close this. I've moved the comment above to issue #373
