### ISSUE TITLE
Add sharing options to the fullscreen photo view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#386]

**Comment by cstiens** [comment]
@N-Pex This is what I'm thinking for this UI. Swiping right to left would let you scroll through the images in the chat. Swiping up or down would close this view, like it works right now. 

- Action icon: brings up the iOS share sheet as expected
- Reply icon: would bring you to the choose a friend view within zom. We may want to swap this out for a different icon. I can't find a system icon to do this, so let me look to see if there are any other patterns we should align with.
- We can leave out the 'heart' icon for now.
- Trash: This would delete the photo.


<img width="394" alt="screenshot 2017-11-06 14 21 27" src="https://user-images.githubusercontent.com/1434597/32462133-ee5c3c6a-c2fd-11e7-87aa-f83f0e9d4061.png">

**Comment by cstiens** [comment]
@N-Pex I see that we have the sharing options in this view now. Can you update the UI to match the screenshot above? We can leave the heart out for now, but we do need to add the ability to delete from local storage.

**Comment by N-Pex** [comment]
@cstiens What about information text, "sent from" and date. Show this at the top then?
