### ISSUE TITLE
Account error

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#389]
Device OS: iOS 10.3.3,  iOS 10.3.3
Model: iPhone 7, iPhone 6

While trying to send messages in Zom I noticed only getting one check verification that the message sent. Messages were not going through. Began troubleshooting.

- I went into my profile page. Everything looks fine. 

![img_2992](https://user-images.githubusercontent.com/30634981/30180437-8483f1d6-93d5-11e7-817f-574ba5b9af89.PNG)

- Tap Settings. See a red X next to my Zom ID. I tap on the settings (information) and see a red X next to Edit Account. 

![img_2989](https://user-images.githubusercontent.com/30634981/30180446-8f9a128a-93d5-11e7-9436-91458333d554.PNG)

- Tap arrow to edit account. Everything on this page looks fine (no red X). 

![img_2990](https://user-images.githubusercontent.com/30634981/30180700-662f6930-93d6-11e7-8290-86429f855064.PNG)

- Tap checkmark in corner. Error message appears. 
- Failed to connevt to XMPP. Tap Ok.

![img_2991](https://user-images.githubusercontent.com/30634981/30180461-9c59468a-93d5-11e7-97ff-8b5875bb00bd.PNG)

- Tap account button (going back to account page). Tap server information arrow. 
- Push registration error. XMPP server incompatible. Option to either reset or deactivate. 

![img_2988](https://user-images.githubusercontent.com/30634981/30180494-ac5ea610-93d5-11e7-90ce-0b8311408a1f.PNG)

- Tried both. Neither resolve the issue. Went to do another task in the office and after some time 
I heard a push notification come through. Checked the account info and log in page. No red X. I was able to send and receive messages.

**Comment by N-Pex** [comment]
I think the server was down a bit yesterday?!? I noticed my test account on Android could not connect to server as well.

(That's one definite problem with no longer showing the green/grey online/offline circles around the avatar, it's hard to notice when you are not online yourself!)

**Comment by N-Pex** [comment]
I am going to close this as a "server was down" issue. Notice in the second screen shot the text "Log in", indicating that you were in fact not logged in. If you were online this would be "Log out".
