### ISSUE TITLE
'Add Zom friends' in group info doesn't work

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#391]
Currently tapping it doesn't take you to the view to choose friends. @N-Pex Do you have any blockers to fixing this?

**Comment by N-Pex** [comment]
Should be fixed in version 91.

**Comment by cstiens** [comment]
The button works now! If you created the group, you can add people to it. There are issues when another member (who did not create the group) tries to add people, but we've discussed that. I'll file a ticket for it. Closing this one!
