### ISSUE TITLE
Adding a friend by scanning their QR code not working all the time

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#395]
Here are the steps I took:

- Opened add a friend screen, tapped scan. Tried to scan a QR code of a new contact.

- I expected to scan the friend QR code, have them receive a friend request and see the friend added to my friends' list. Also, get a notification when we've become friends. 

- What I saw, was when I scanned the friend's QR code from the add a friend screen, the Username field very briefly flashed with the contacts Zom ID and the field was highlighted.
However, the friend was not added. I did not receive any notification and they were not in my friends' list. 

- This exact same issue happened on Jodi's iOS device.

Device and Version: iOS 10.3.3 iPhone 7 
- App Version: Build 90

**Comment by N-Pex** [comment]
@tiffrobo Did the add friend screen go away, or did the Username field just flash then remain on screen, empty?

**Comment by tiffrobo** [comment]
The add friend screen remained. Did not go away. Username field flashed,
and then remained empty.

**Comment by N-Pex** [comment]
This can happen if the scanned QR is invalid somehow. On what device was the QR displayed? If it was on the webpage, @n8fr8 fixed some error there which could have caused exactly this problem.

**Comment by cstiens** [comment]
This happened when we were scanning people's QR codes from their Zom app. We scanned iOS and Android phones and it happened in both instances. This was always only when scanning from iOS.

**Comment by N-Pex** [comment]
Ok, thanks, weird. I haven't been able to reproduce this, will try more.

**Comment by cstiens** [comment]
We'll test this in build 95 and see if it keeps happening.

**Comment by cstiens** [comment]
In build 99, we haven't had any problems with scanning QR codes. We've tested on 6 different devices. I'm going to close this for now. We'll reopen or create a new issue if it comes up again.
