### ISSUE TITLE
Wrong group name displayed

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#396]
When opening a group chat the name in the navigation bar displays the wrong name initially. It seems to display the last chat name you had open (whether that's a group chat or a chat between two friends). It seems to take 3-30sec to change to the correct name. 

We saw this bug happen numerous times on other iOS devices. 

Device: OS 10.3.3 iPhone 7 
App version, build: Build 90

**Comment by N-Pex** [comment]
Haha, literally not 5 minutes ago I saw this myself and thought that I must fix this! =)

I guess what we can do is blank the title out immediately, while we load the data.

**Comment by cstiens** [comment]
Fixed!
