### ISSUE TITLE
Pending approval from a friend request keeps showing when I open groups

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#397]
Here are the steps I took:

- I received a new friend request from someone. Tapped green check to accept. 
Opens a chat with the 'new' friend that shows 'Waiting for your friend to accept you'. I tap back.

-  I open a group chat (the new friend is not a part of this group chat) and see 'Waiting for your friend to accept you'. I cannot chat. I go back. 
 
![img_0390](https://user-images.githubusercontent.com/30634981/30283940-2cd50b34-96df-11e7-850c-5cdd6d695d54.PNG)

- After going back to conversations, I try again. Reopen same group chat and I see the same thing. After tapping back, I open a different group chat and again see 'Waiting for your friend to accept you'. I tap back.  

- I close the app, swipe it away and reopened it. Opened a group chat and was able to chat. Did not see 'Waiting for your friend to approve you'. Seems to resolve the issue. 

Device OS: OS 10.3.3
Device: iPhone 6 and iPhone 7
App version, build: Build 90

**Comment by N-Pex** [comment]
Fixed in version 91.
