### ISSUE TITLE
Zom iOS - Account Passphrase/Password

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#4]
I couldn't figure out how to get my passphrase/password for the account while uninstalling Zom.
When I select the account from the Settings, it only gives 'Share' and 'Logout' and 'Cancel' option.

**Comment by n8fr8** [comment]
Need to have the ability to review/edit account settings and see the auto-gen'd password

**Comment by n8fr8** [comment]
+1 can we bump this up? We just need a way to show the user their password in the account settings

**Comment by n8fr8** [comment]
Add the <0> icon to reveal the password

**Comment by n8fr8** [comment]
Allow access to account info dialog w/o having to logout

**Comment by N-Pex** [comment]
Added a "Show information" option when you are logged in, opening up the login pane in read only mode. If you are not logged in, I added an "i" accessory view that allows viewing of the password.

What do you think?

**Comment by n8fr8** [comment]
Sounds solid to me!
