### ISSUE TITLE
Incoming media message stuck in progress

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#400]
An iOS becomes friends with a new fellow (on Android) and when the new chat opens I begin receiving incoming photos. Four photos are incoming with a process indicator. Only two of the photos actually complete loading and I can view them. The other two are stuck in incoming or processing mode. 

We had just become friends and had not chatted with each other prior to the photos being sent. 

- After 4 days, the photos are still stuck in processing mode. Even after quitting the app. 

![img_0391](https://user-images.githubusercontent.com/30634981/30334793-3ae3e458-97a6-11e7-8571-6b5b040f3bc2.PNG)

![img_0392](https://user-images.githubusercontent.com/30634981/30334798-3e2f8d9c-97a6-11e7-9cfa-3dad65a1bac7.PNG)

- This issue happened again, when the same Android fellow added a different iOS friend and began sending photos.  In this case, they too had just become friends and never chatted before. 

![img_3035](https://user-images.githubusercontent.com/30634981/30335144-2d07925c-97a7-11e7-96e8-cd50e2e52e10.PNG)

Device and OS: iphone 6 and iPhone 7, 10.3.3

**Comment by cstiens** [comment]
Fixed!
