### ISSUE TITLE
Photo sent in group chat is stuck in processing

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#402]
If iOS sends a photo to group chat Android users in the group chat receive a link to the browser where they can view the image. 

From the iOS phone that sent the image, I see the photos stuck in processing/loading form. I waited 10 minutes and the photos never resolved. It still looks as shown in the screenshot below.

![img_3036](https://user-images.githubusercontent.com/30634981/30348226-4393493a-97d4-11e7-864c-a2ea2b1ac058.PNG)

![screenshot_2017-09-12-15-28-51](https://user-images.githubusercontent.com/30634981/30348988-e5cbedea-97d6-11e7-8245-3d3d0ace215f.png)

Device and OS: iPhone 7, 10.3.3
App version and build: Build 91

**Comment by cstiens** [comment]
@chrisballinger I forgot to mention this on our call today. I'm sure you're working on it. But this is another major thing we saw with media sharing in groups.
