### ISSUE TITLE
Better indication of when you're not signed in

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#405]

**Comment by cstiens** [comment]
On Android now, we show the snackbar with the 'status' in any case where you are offline. 
* Signing in...
* No internet

@n8fr8 what other offline cases are you communicating on Android right now?

**Comment by n8fr8** [comment]
Sorry I am confused by your questoion, @cstiens ? Do you mean what other possible snackbar messages do we show?

**Comment by cstiens** [comment]
> Do you mean what other possible snackbar messages do we show?

Yes.

**Comment by cstiens** [comment]
@N-Pex can we go ahead and implement our own version of a snackbar on iOS? There's really not an iOS UI pattern to fit this need. I know we have implemented something similar at the top of the screen for 'no internet'. Can we tweak it to look like the mockups below, and add messaging for the other 2 states (Network offline and signing in)?

<img width="1222" alt="screenshot 2018-02-01 14 05 41" src="https://user-images.githubusercontent.com/1434597/35700608-18172318-0759-11e8-84ea-8bc35392d696.png">

**Comment by N-Pex** [comment]
@cstiens Great, I started on this. With "network offline" you mean "not connected to the server"? Should the snack bars also be shown in the messages controller?

**Comment by cstiens** [comment]
Awesome! Thanks.

> With "network offline" you mean "not connected to the server"? 
I believe that's the case, but @n8fr8 could answer that for sure. We're matching what is implemented on Android.

> Should the snack bars also be shown in the messages controller?
No, not in the message controller. Only in the main views.

**Comment by cstiens** [comment]
These are in! Great work.
