### ISSUE TITLE
Changing group name is finicky

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#410]
Sometimes when you change the name it works and updates for all members of the group. Sometimes it doesn't work. It updates momentarily for the person that changed it, but then reverts back to the auto-generated name. I haven't seen any patterns yet.

**Comment by N-Pex** [comment]
Yes, currently in version 93 not all are admins, so they can't really change the subject/name. But for those that can (the creator) it looked very odd when nothing happened after changing (it needs to roundtrip to the server) so we "fake it" by updating the UI momentarily...

In 94 all are admins, so this should work better(?)
