### ISSUE TITLE
Change input field text to 'Send private message'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#415]
We want to switch the text in the input field from 'Send OMEMO encrypted...' to 'Send private message'.

**Comment by N-Pex** [comment]
Version 95.

**Comment by cstiens** [comment]
Thank you! In single chats, we're seeing "Send private message", but in groups we're seeing "Send plaintext message". This makes sense because group chats aren't encrypted. I'm going to make a separate issue for what that message should be. For now, this one is done!
