### ISSUE TITLE
Update pending approval UI

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#417]
I'll provide the UI for this, but in general, we want to add a button that would re-approve the contact.

**Comment by cstiens** [comment]
UI and notes in Android ticket https://github.com/zom/Zom-Android/issues/323

**Comment by N-Pex** [comment]
Fixed in 95.

**Comment by cstiens** [comment]
Done. 

This is the current behavior from our testing—If you refresh before someone approves you, nothing happens. If someone blocks you, tapping refresh will resend the invite.

I'd like to give better feedback once someone taps resend, but I'll create a separate ticket for that.
