### ISSUE TITLE
When someone adds you to a group it shows a @conference.zom.im ID 

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#419]
When invited to join an existing group chat I received a conference ID instead of the group name.

![img_3041](https://user-images.githubusercontent.com/1434597/30554156-298a581e-9c69-11e7-824a-32903042be64.PNG)

![img_0171](https://user-images.githubusercontent.com/1434597/30554248-83382210-9c69-11e7-81a4-e19d4e4e11e3.PNG)

Device: iPhone 7, iPad 10.3.3
App version, build: Build 94

**Comment by N-Pex** [comment]
@n8fr8 @chrisballinger Is this something the push server sends? I don't see this kind of string being generated either on iOS or Android.

**Comment by cstiens** [comment]
We're not seeing this anymore. Closing.
