### ISSUE TITLE
Unable to open invite zom links in a chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#420]
Clicking on the actual invite link (the first one, not the preview) doesn't open. Clicking on the preview gives you share options.

On a related note, for Zom invite links received in a chat, users should have the option to just add that person as a friend.

![img_3053](https://user-images.githubusercontent.com/1434597/30658025-113df346-9dff-11e7-8ede-0a2a7b32c8bd.PNG)

![img_3055](https://user-images.githubusercontent.com/1434597/30658031-131ab1b8-9dff-11e7-951f-735a1587bdac.PNG)

**Comment by n8fr8** [comment]
Strange, I thought this was implemented in the migration work.

**Comment by N-Pex** [comment]
@cstiens Yes, strange indeed, this works for me. How was the original invite link obtained?

**Comment by cstiens** [comment]
Here are the steps I took:
- On Android, I opened a profile view for a friend. 
- Then, selected share. 
- That took me to the 'choose friend' view.
- I selected an iOS friend, and the message sent.

**Comment by N-Pex** [comment]
@n8fr8 Turns out Android was sending fingerprints containing spaces, so iOS refused to see them as valid invite links. I guess one option would be to strip spaces, but better probably never to generate them in the first place. Please see PR on Android side!
