### ISSUE TITLE
Hide permissions for non-owner

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#427]
We need to hide the ability to 'add a zom friend' to a group and edit the group name for members that are not the owner.

**Comment by N-Pex** [comment]
Implemented in version 98.

On reading the spec I changed this to "members that have the role 'moderator'" according to this table here: https://xmpp.org/extensions/xep-0045.html#roles-priv

**Comment by cstiens** [comment]
Done! Great work
