### ISSUE TITLE
Update SSL certificate with permanent cert

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#428]

**Comment by N-Pex** [comment]
Ok, I've prepared the code, so we should just be able to drop the new cert in there now.

**Comment by n8fr8** [comment]
So for now, let's just pin the current certificate we have, which is generated by LetsEncrypt. I am having some issues related to our migration to the new server infrastructure, and don't want to mess anything up today by screwing around with certs.

I think this is what you need:
29:16:D3:7B:F3:65:FF:E2:BD:CC:02:ED:86:E3:3D:7B:EF:A4:D2:4C:0C:11:9A:0C:96:65:B0:B7:A5:14:82:DC
You can find details here:
https://check.messaging.one/result.php?domain=home.zom.im&type=client
https://github.com/Flowdalic/java-pinning

**Comment by N-Pex** [comment]
Ok, got it, thanks!

**Comment by cstiens** [comment]
We will need to do another update to the permanent certificate (in a couple weeks)

**Comment by cstiens** [comment]
@n8fr8 It looks like the time to update to a permanent certificate is soon upon us. Can we aim to get this into the next iOS build?

**Comment by cstiens** [comment]
With the new solution to update the server with the proper cert using the same key pair ... this is fixed. We've tested and verified on 3 iOS devices!
