### ISSUE TITLE
Inbound group media messages show the link still

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#429]
The inbound media https link is displayed, and then the media is fetched, and displayed properly. Both show up in the group chat display, which is confusing.

**Comment by chrisballinger** [comment]
Fixed in this commit https://github.com/ChatSecure/ChatSecure-iOS/commit/6eb1b2760a1714b30e27bb524eb238546f056e58

**Comment by cstiens** [comment]
Hooray!
