### ISSUE TITLE
"Waiting for Friend" request refresh button misbehaving

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#433]
When you have scanned a friend's QR and are waiting to be approved, you get the nice new "Waiting for Approval" screen with the refresh button.

When you press the refresh button, it seems to automatically switch to being approved somehow, even if the remote user has not approved you.

**Comment by n8fr8** [comment]
This might be a bug in the way Zom Android is handling this re-request for subscribing

**Comment by N-Pex** [comment]
So my guess this is the result of a partial friending problem maybe? Upon refresh it realizes that, hey, we are already friends according to the server.

**Comment by cstiens** [comment]
This was fixed on the Android side.
