### ISSUE TITLE
Input field for unencrypted group chats

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#434]
Single chats say "Send private message"
Groups currently say "Send plaintext message"

**Comment by cstiens** [comment]
@N-Pex Let's change it from "Send plaintext message" to just "Send message" for unencrypted groups.

**Comment by tiffrobo** [comment]
It's in!
Group unencrypted: "send message"
Group encrypted: "send private message"

Single chat: "send private message"

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125

**Comment by tiffrobo** [comment]
In relation to group encryption (OMEMO), the default is set to on within groups. 
Although when you first enable group encryption in settings it says it will not automatically be turned on. 

![img_e82e8041c74f-1](https://user-images.githubusercontent.com/30634981/36551974-6dbc5a20-17be-11e8-9fb5-8119f5b2f54d.jpeg)

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125
