### ISSUE TITLE
If Android creates the group, iOS members still have permission to add friends and edit the name

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#437]
@n8fr8 Would this be an issue on the Android side?

For groups created on iOS, only the group owner has the ability to add friends and change the name. Other iOS members cannot. They only have them if Android creates the group.

**Comment by N-Pex** [comment]
Android side issue, fixed here: https://github.com/zom/Zom-Android/commit/96f98cf208f55943c7fe3b56b4f91b267c76972b. Please re-test with new Android build.

**Comment by cstiens** [comment]
Tested with Android beta 5. Fixed!
