### ISSUE TITLE
Zom crashes when user is re-invited to a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#439]
Here's what happens:
- C's iphone was in a group.
- She left the group.
- T's iphone re-invited her.
- C showed in the the group member list on T's phone.
- C's app was open, and crashed when re-added to the group
- After crashing, C no longer showed in the member list on T's phone.

T tried to add C again, it worked without problems. It didn't crash the app the second time.

Though, we saw this crash in 2 other cases.

**Comment by N-Pex** [comment]
No matter how I try, I can't get this to happen. Any idea if this happens in group with media in them, or also in text only groups? Are you popping in and out of different conversations or mainly staying in the group? Any additional info would help.

**Comment by cstiens** [comment]
> Are you popping in and out of different conversations or mainly staying in the group? 

No, just staying in that group chat. @N-Pex Were you able to reproduce it?
I'm not sure if it's a group with media or text only, but we can test that again today.

**Comment by tiffrobo** [comment]
**Case 1: Leave and rejoin a group (Text messages)**
Here's what happens:
T's iPhone created a group chat. **(Text message only)**
C's iphone was in a group chat including conversations with text only
She left the group.
She doesn't show in members list. T's iphone re-invited her. Doesn't appear to have worked. C does not show up in members list and she doesn't receive and messages. T's iPhone re-invites. 
C's app was open in convo view, and app crashed when re-invited. 
C still **not** showing on member list on T's phone. 
T tried to add C again, it didn't work. C was never able to rejoin group.
**Note: C's nickname showing in group name** 

**Case 2: Leave and rejoin a group (Media messages)**
Here's what happens:
T's iPhone created a group chat. **(Media messages included)**
C's iphone was in a group chat including conversations with media (audio and photos)
She left the group.
She doesn't show in members list. T's iphone re-invited her. Doesn't appear to have worked. She doesn't show in members list.
C's app was open in convo view, and app crashed when re-invited. 
C still **not** showing on member list on T's phone. 
T tried to add C again, it worked without problems. It didn't crash the app the second time. C received notifications from missed messages sent to the group. 
C sees the last 20 messages in her chat history. 
**Note: C's nickname showing in group name** 

**Case 3: Leave and rejoin a group (Text only)**
(change name of group to not include contact nickname)
T's iPhone created a group (Text Only)
**Changed the name of the group to not include any nicknames of members in the group.**
C left the group. 
C's app was open, her app crashed when she tapped 'leave' the group. 
T still sees C's contact in the members list. 
C is receiving notifications from the group. 
C re-opens app, but the group is not listed in convo view. 
T no longer sees C's contact in the members list. And C no longer receiving notifications.
T re-invites C to the group, C added no problem. It didn't crash the app when re-invited to join group. 
T still sees C's contact in the members list. Notifications and messages come through to C's group chat.

**Comment by cstiens** [comment]
This is no longer happening!
