### ISSUE TITLE
need more screenshots

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#44]
Need iPod and iPad screenshots as well, since the binary says we support it!

iPhone 3+4 (3.5 Inch)
640 x 960

iPad (Air and Mini Retina)
1536 x 2048

**Comment by N-Pex** [comment]
[Screenshots3.zip](https://github.com/zom/Zom-iOS/files/62217/Screenshots3.zip)

**Comment by n8fr8** [comment]
(Sorry!) Last ones:

iPhone 5 (4 Inch)
640 x 1136

iPad Pro
2048 x 2732

**Comment by N-Pex** [comment]
Here we go:
[Screenshots4.zip](https://github.com/zom/Zom-iOS/files/63221/Screenshots4.zip)
