### ISSUE TITLE
Error on link preview

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#443]
![59d6fb1c-b21e-4c3f-83e6-d78f43757690](https://user-images.githubusercontent.com/1434597/30877670-02c7dbae-a2c0-11e7-85b4-5d5185f46beb.jpg)

![fc9bcd91-a936-41bf-9501-423a395957db](https://user-images.githubusercontent.com/1434597/30877688-0d690f7e-a2c0-11e7-9d7e-eb3f207df16c.jpg)

**Comment by tiffrobo** [comment]
This scenario is weird and I haven't seen it again, but will retest.

**Group Chat:** Carrie sent a link to the group and I received the message with the link processing. She resent the link and I still only saw the processing. 
![img_3296](https://user-images.githubusercontent.com/30634981/32077893-955f65b0-ba6a-11e7-9672-1237f2d94437.PNG)

![img_3299](https://user-images.githubusercontent.com/30634981/32077885-8dd1d5da-ba6a-11e7-86e2-924f36f0b056.PNG)


**Single Chat:** She later sent the same link in a single chat and I again saw it processing. With some weird cropped images.  
![img_3297](https://user-images.githubusercontent.com/30634981/32077911-a02c9e9a-ba6a-11e7-8256-5005407a4d72.PNG)

![img_3300](https://user-images.githubusercontent.com/30634981/32077918-a52c1592-ba6a-11e7-85ad-a3264b4ba27c.PNG)

The error may have occurred when I was using my phone data only, not wifi. Will retest.

Device: iPhone 7 iOS 11.0.3
App Version: Build 105

**Comment by cstiens** [comment]
We haven't seen any link errors in recent testing.
Build 115
