### ISSUE TITLE
Missing someone in the group member list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#444]
Ro can't see Alm in the 'Dev Testing Day' group. Alm is a member. Other non-admin see her, but Ro doesn't on her iphone. It seems that the current occupancy didn't load for Ro. 

We talked on the product scrum today about an option to manually reload, or reload the member list when the person opens the info tab. Let's chat about this on the monday scrum.

**Comment by n8fr8** [comment]
I think we need to set "muc#roomconfig_getmemberlist" to "participant" and then we will be able to request the members list of a room w/o being a moderator or admin.

also "'muc#roomconfig_presencebroadcast" should also be "participant"

I haven't been doing that on Android, so will make the change now.

See the details here: https://xmpp.org/extensions/xep-0045.html

**Comment by n8fr8** [comment]
Also, instead of removing someone when I get  "left" notice, I just reload the membership.
Seems like there is iOS relevant info here: https://github.com/robbiehanson/XMPPFramework/issues/521

**Comment by n8fr8** [comment]
Prosody and members list: https://prosody.im/issues/issue/445 
https://hg.prosody.im/0.10/rev/4a178edc9847

**Comment by N-Pex** [comment]
I found and fixed another bug related to this, need to retest in build 102.
