### ISSUE TITLE
Remove 'room owner, moderator' wording, Show crown

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#447]
<img width="736" alt="screenshot 2017-10-02 22 47 09" src="https://user-images.githubusercontent.com/1434597/31109133-8bf85e00-a7c3-11e7-9c5b-5c40e494c725.png">

[ic_admin-crown@3x.pdf](https://github.com/zom/Zom-iOS/files/1351079/ic_admin-crown.3x.pdf)

![ic_admin-crown 3x](https://user-images.githubusercontent.com/1434597/31109125-79f1cb38-a7c3-11e7-8e52-77b935adf2c8.png)

**Comment by N-Pex** [comment]
Fixed in 102.

**Comment by cstiens** [comment]
Done. Beautiful

**Comment by cstiens** [comment]
@N-Pex Here's the crown as you requested.

![ic_admin-crown_48](https://user-images.githubusercontent.com/1434597/31232332-353bd2ca-a9af-11e7-81a1-35b78f851e93.png)

![ic_admin-crown_96](https://user-images.githubusercontent.com/1434597/31232364-506af8e6-a9af-11e7-8aa9-e5c56af6a28f.png)
