### ISSUE TITLE
Order member list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#450]
List non-admin member alphabetically. Always placing the owner at the top.

**Comment by N-Pex** [comment]
Actually got this into 102, so please test!

**Comment by tiffrobo** [comment]
@N-Pex Are the members designed to be ordered according to JID or nickname?

**Comment by N-Pex** [comment]
@tiffrobo Admins at the top, then ordered by nick (if we know it, else we use the jid for that member)

**Comment by cstiens** [comment]
Perfect!
