### ISSUE TITLE
Re-invite anyone in the group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#451]
@N-Pex I saw just one issue when we were testing the member list today. Tiffany left the '102 Member Test iOS' group, but she never turned gray. Even after 8 hours. The problem I'm having is that I can't re-invite her because she shows up as black in my member list.

On iOS, you can only re-invite people if they are gray on your list. We'll test leaving more. But one easy fix to be able to get people back in is to allow the moderator to re-invite anyone in the group. That's the way it behaves on Android right now.

**Comment by N-Pex** [comment]
Ok, added this in build 103.

@cstiens Need a consistent UI for this though, on Android we have the check, on iOS we show item as grayed out (but you can still add it).
