### ISSUE TITLE
QR Code Scan Bug

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#453]
You aren't friends with someone, so you add that friend by scanning their QR code from a different friends list of contacts. 

- Tif is not friends with NP. C and Tif are friends. C is friends with NP. 
- C opens NPs contact information. Four QR Codes listed along with 'Verify Contact'. 
- C verifies NP. 
- C opens NP's first QR code and Tif scans the first QR code of NP. JID flashes. They do not become friends. 
- Tif scans the second QR code for NP. JID flashes. They do not become friends. 
- Tif scans the third QR code for NP. Friend added! NP shows up in Tif's friend's list.  

Devices: iPhone 7, 6 and iPad
Build 103.

**Comment by cstiens** [comment]
@n8fr8 @N-Pex The other issue we had with scanning from iOS was when I opened the QR code for an iOS contact (Jodie) from my Android phone. It would not scan this code. Rather, the JID would flash in the username field, then disappear. I'm not sure which side (ios or android) needs the fix here.

Device: iPhone 6
Build 103 (ios) and Beta 7 (android)

**Comment by N-Pex** [comment]
So one thing we saw was that nicknames that contain spaces (or other not url-safe characters) won't work in the scanning. That will be fixed in next build.
