### ISSUE TITLE
Unable to verify a friend

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#454]
Ro and C had this issue today. When a contact had 2 QR codes in their profile and the option to verify underneath, tapping verify didn't seem to verify them. Usually, when it verifies, the 'Verify' button goes away and you are able to chat with that person. In our cases today, we were still unable to send and receive messages after tapping verify. @chrisballinger  @N-Pex Ro is preserving her phone in this state with one contact. I think it would be most helpful if we had a call with her to debug.

**Comment by cstiens** [comment]
Here are screenshots that show what happens for both contacts that are unable to verify.

1. Sender is unable to send a message 
![image uploaded from ios](https://user-images.githubusercontent.com/1434597/31691533-0d5bde6a-b35c-11e7-9991-26811b85f73e.png)
@chrisballinger do you think this is happening since their last chat together was July 19th (over a month ago)?

2. The error says there's no trusted device found.
![image uploaded from ios 1](https://user-images.githubusercontent.com/1434597/31691574-268e730c-b35c-11e7-96af-b88c4afcac71.png)


3. Keys are displayed in the profile view, but when the user taps verify, nothing happens.
![cannot-verify](https://user-images.githubusercontent.com/1434597/31691710-9787527c-b35c-11e7-8ecf-1bf3bfe3355f.png)

**Comment by cstiens** [comment]
R’s phone
Model: iPhone SE
OS: 10.3.2

C’s phone
Model: iPhone 6
OS: 10.3.3

**Comment by chrisballinger** [comment]
This is possibly related to the disconnect between the upstream profile view and Zom's when there are multiple OMEMO keys present, or there has been a change.

**Comment by N-Pex** [comment]
You should now be able to see a list of them all.
