### ISSUE TITLE
Links 'disappear' when I send them in group chat, Links not showing 

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#455]
After pasting the link into the chat field, I press send. The chat field acts like it sends the message, but nothing shows in the group chat. It does send, though, and Android phones see it in their chat view. However, iOS members don't seems to see it.

@chrisballinger It seems that links are just not showing up on iOS when they are sent or received. This is a regression, because it was definitely working prior to this build.

Build 103

**Comment by chrisballinger** [comment]
Sigh. I know why this is. The recent "fix" to hide the URLs on incoming media messages is too aggressive.

**Comment by cstiens** [comment]
Dang it. Do you have a chance to look at this today? I think they need to be working before we ship to the public.

**Comment by chrisballinger** [comment]
Yeah

**Comment by cstiens** [comment]
Thank you!!

**Comment by chrisballinger** [comment]
@N-Pex I checked in some code to [this branch](https://github.com/ChatSecure/ChatSecure-iOS/tree/fix_missing_url_messages) that seems to fix the problem for me, but I seem to be having another problem where the bubble size is calculated incorrectly or isn't being invalidated or something. 

<img width="559" alt="screen shot 2017-10-06 at 5 44 42 pm" src="https://user-images.githubusercontent.com/518687/31303183-3b09e736-aabe-11e7-93be-32914d98637b.png">

**Comment by cstiens** [comment]
@chrisballinger @N-Pex I've filed the bug for the display of links in issue #456. I'm going to go ahead and close this one since links are displaying now.
