### ISSUE TITLE
Do not auto-download images from people you're not friends with

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#457]

**Comment by cstiens** [comment]
@chrisballinger @N-Pex @n8fr8 Here's an initial idea for how we can handle this. I intentionally didn't include a 'friend request' inline. People get touch happy about the friend requests. So, in the case that the photo is malware, I didn't want someone to hit approve, then regret it later.

<img width="374" alt="screenshot 2017-10-11 16 15 47" src="https://user-images.githubusercontent.com/1434597/31467302-1bea2700-ae9f-11e7-978b-d4ab631f3f57.png">

**Comment by chrisballinger** [comment]
Nice concept!

**Comment by cstiens** [comment]
This functionality is in! Hooray. I'll create a separate ticket for a UI enhancement that includes the ability to add the person as a friend in the chat itself.
