### ISSUE TITLE
Images cropped

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#460]
@chrisballinger I think this has to do with the most recent work on link display. When you quit then reopen the app, they fix themselves and display correctly.

![img_3151](https://user-images.githubusercontent.com/1434597/31406579-8ca56578-adc7-11e7-8757-bd0fcf1d74db.PNG)

**Comment by cstiens** [comment]
@chrisballinger can you take a look at this? Android needs a little more work, so, theoretically we have a bit of time to fix this and push a new build to Apple before going public with it.

**Comment by chrisballinger** [comment]
@N-Pex I didn't get a chance to look at this one today. If possible please take a look, otherwise I'll work on it tomorrow.

**Comment by N-Pex** [comment]
Should be fixed in 105.

**Comment by chrisballinger** [comment]
I noticed that some images are still cropped, but your PR did fix a lot of
issues, including the white flashing and scrolling. I am also seeing
crashes related to collection views where layouts aren't being invalidated
properly, so perhaps your fix is missing a call to invalidate layout
somewhere.

**Comment by N-Pex** [comment]
@chrisballinger I started having a look today at crashes I saw related to views not being invalidated properly. Maybe the same thing? This is related to the "load more" view I think, the culprit can be JSQMessagesCollectionViewFlowLayout.layoutAttributesForElementsInRect returning multiple attributes for same IndexPath (0,0), but this is just speculation at this point, needs more investigation.

**Comment by chrisballinger** [comment]
I'm guessing that it can still be triggered by rapidly scrolling the view
upwards. That used to crash it pretty consistently.
