### ISSUE TITLE
Switch to toggle for 'mute notifications'

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#462]

**Comment by tiffrobo** [comment]
The toggle is in! 
But, when I toggle on/off the bell icon remains with a slash thru it. 

Device: iPhone 7, iOS 11.0.3
App version: Build 106

**Comment by N-Pex** [comment]
Hm, yes, I thought changing the icon and not the text would be weird and if we change the text as well it's almost the same as what we had, just with an added toggle. Maybe no icon at all?

**Comment by n8fr8** [comment]
What if just said "Notifications" with the toggle, default to on?

**Comment by n8fr8** [comment]
I also think we should show the muted icon on the conversation list screen, and the main chat view somewhere.

**Comment by cstiens** [comment]
> But, when I toggle on/off the bell icon remains with a slash thru it.

That's correct. The icon shouldn't change since there's a toggle.

> What if just said "Notifications" with the toggle, default to on?

Yes. I think just saying "Notifications" is good. There has been confusion about what it means to mute. Some people think they will still get notifications, just without sound. Which totally makes sense.

> I also think we should show the muted icon on the conversation list screen, and the main chat view somewhere.

That's a good idea. That way people realize it without having to go hunting for it. I'll think about where that would look best in the UI.

**Comment by cstiens** [comment]
@N-Pex Will you switch the icon to the plain notification bell: https://www.dropbox.com/s/6yd1o10j2t2gtab/Screenshot%202017-11-06%2014.33.33.png?dl=0

<img width="96" alt="screenshot 2017-11-06 14 33 33" src="https://user-images.githubusercontent.com/1434597/32462470-07ba4d36-c2ff-11e7-9741-e1e4a7508a84.png">

And, change the text to 'Notifications' only. After that, we can close this one, and make Android to look the same.

**Comment by cstiens** [comment]
Done!
