### ISSUE TITLE
App crashes when user taps 'download' on timeout error

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#466]
Build 104

User is getting a timeout error (filed #463). But, as a separate issue—when the download button displays in the dialog and the user taps it, the app crashes.

![timeout-download](https://user-images.githubusercontent.com/1434597/31922330-eff0a79c-b839-11e7-9de9-fb348dd239b6.jpg)

**Comment by tiffrobo** [comment]
I have received a few of these Timeout Errors. Trying to pin down the conditions, but I believe all errors were received when I was using my phone data, no wifi. 

Tapping download still crashes the app. And although I've connected to wifi, the errors remain and I cannot load the images.

Device: iPhone 7 iOS 11.0.3
App version: 105 build

![img_3291](https://user-images.githubusercontent.com/30634981/32077370-cb01a586-ba68-11e7-825b-5383915c7396.PNG)

![img_3315](https://user-images.githubusercontent.com/30634981/32077450-23510272-ba69-11e7-944b-c3677a110e12.PNG)


![img_3242](https://user-images.githubusercontent.com/30634981/32077382-d5bd6168-ba68-11e7-896b-9488d28a61fa.PNG)

**Comment by cstiens** [comment]
Screenshots are from T's phone. But, we've also seen this on R's phone.

T's phone
Model: iPhone 7
OS: 10.3.3

R’s phone
Model: iPhone SE
OS: 10.3.2

**Comment by chrisballinger** [comment]
It still crashes? That should have been fixed.

**Comment by cstiens** [comment]
> It still crashes? That should have been fixed.

We can re-test. It wasn't marked for review, so we haven't intentionally tried to reproduce and test it.
