### ISSUE TITLE
Can't create new groups

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#473]
In build 106 and 107 for iOS we can no longer successfully create new groups. 
No members in members list, but the creator. If you send messages you don't receive any checkmarks or a clock. 

**Build 106, Rosa's iPhone** 
![img_3398](https://user-images.githubusercontent.com/30634981/32462674-d4792522-c2ff-11e7-8152-7a5b2794387c.PNG)

![img_3397](https://user-images.githubusercontent.com/30634981/32462676-d79cd3fc-c2ff-11e7-8dd4-c2ce2a67e44e.PNG)

**Build 107, iPhone 7**
![img_3399 2](https://user-images.githubusercontent.com/30634981/32462690-e2d33c5c-c2ff-11e7-9950-69099f7f5194.PNG)

![img_3400](https://user-images.githubusercontent.com/30634981/32462692-e4e84e2e-c2ff-11e7-981b-262332a16ba7.PNG)

**Comment by N-Pex** [comment]
Yes, these was a regression that has been fixed, please try with version 108.

**Comment by cstiens** [comment]
This is working now. Though, there's a bug related to new groups filed at #479
