### ISSUE TITLE
Conference ID displays rather than member ID

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#475]
For the same group, this is happening on R's (iPhone SE) phone but not T's (iPhone 7).

**Comment by N-Pex** [comment]
@cstiens Is this happening for new messages coming to the group?

**Comment by cstiens** [comment]
@N-Pex Do you mean in the notification do they show as conference ID?

![img_7f1b5d4a8785-1](https://user-images.githubusercontent.com/1434597/32620627-e50610b2-c543-11e7-8e68-a86fcf9a1d4e.jpeg)
![jid](https://user-images.githubusercontent.com/1434597/32621866-d9f177e0-c546-11e7-8127-e58ca43e200c.PNG)

**Comment by N-Pex** [comment]
@cstiens No, I mean like in messages received today, as opposed to the ones in the screenshot that are from last week I believe.
