### ISSUE TITLE
Unable to access the option to send photos or audio messages

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#477]
I will be documenting any weird chat view happening within iOS. 

In group chat view I was unable to access the option to send audio or photos.
Maybe it's because I was signed out, but the option should still be available and the message queued to send when I re-connect or sign back in, correct? 

![weirdchat_01](https://user-images.githubusercontent.com/30634981/32622400-55e330a4-c548-11e7-9218-18609cc925af.PNG)

Unable to access the option use audio, photos or stickers while in airplane mode.
This was a few days later. When in airplane mode I saw the same thing. Rosa also saw this issue at the same time, on the same day.

![img_3402](https://user-images.githubusercontent.com/30634981/32564424-d7de59b4-c479-11e7-991f-f3cf4994efe3.PNG)

![img_3401](https://user-images.githubusercontent.com/30634981/32564428-da8f526c-c479-11e7-8a40-c533f883e101.PNG)

Device: iPhone 7, iPhone SE
App version: Build 107, 106

**Comment by N-Pex** [comment]
I guess the question is, SHOULD you be able to "send" images when offline?
