### ISSUE TITLE
The first message(s) I send after creating a group doesn't send

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#479]
Build 109

I have to leave the initial group chat view, go to another screen (like convos or group info) then come back to the group chat. After leaving and coming back, I can write and send messages and they go through to the group. 

If I send any before leaving the group, they don't go through. Additionally, in the case of sending first messages that don't go through, the people added to the group don't see the group. They only see it when an initial message is sent and goes through.

@N-Pex @chrisballinger  Will you test and see if you can reproduce this?

This is a regression from the public build we have out, so we should fix it before releasing to Apple again.

**Comment by chrisballinger** [comment]
This might have something to do with it? https://github.com/robbiehanson/XMPPFramework/issues/746
