### ISSUE TITLE
App crashes when sharing audio from email

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#484]
@N-Pex Here were my steps.
- I opened my email with an audio attachment
- I tapped on the audio, and selected to share it via Zom.
After a couple seconds of delay, the app crashed. I will do the same test again to get more details for you.

**Comment by cstiens** [comment]
Hey @N-Pex this happened when I sent the audio to a single person. I just sent a crash report for it. When I sent the audio to a group it worked. The second time I sent it to a single chat, it worked. It was to the same person. So, it is working sometimes. Interested to see if the crash report helps track anything down.

**Comment by N-Pex** [comment]
Fixed a bug related to this, so I think we need to retest, should be fixed now.

**Comment by tiffrobo** [comment]
Working! At least no crashes today while testing. Is there a file size limit?

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125

**Comment by cstiens** [comment]
> Is there a file size limit?

@tiffrobo yes, but it's determined by the server. We have a separate ticket to cover fail cases if the an audio file is too big, so I'm going to go ahead an close this one.
