### ISSUE TITLE
'Download' for media that is not from a friend doesn't work

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#486]

**Comment by cstiens** [comment]
@chrisballinger did you fix this one? It's referring to the case when an image is not auto-downloaded from a person that is not your friend.

**Comment by chrisballinger** [comment]
It should work to manually download, but images from non-friends are still not auto downloaded.

**Comment by cstiens** [comment]
Awesome! This is working. I think we could give some processing feedback to make the UI better over bad networks. I'll make a separate ticket for that though. Great work Chris!
