### ISSUE TITLE
Messages not going through

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#489]
@N-Pex @chrisballinger 

In my chat with Rosa this morning, she would send messages, but they wouldn't go through. She has a clock on her side. My account was signed out for some time, so this could be part of the reason why they weren't going through. But even once I was signed back in, and we were chatting again, the earlier messages she sent didn't go through. They should queue and resend automatically, right?

I'm mainly referring to text messages. She also had issues with media messages. But, we don't automatically try to resend those anyway.

**Comment by cstiens** [comment]
Related to #468

**Comment by N-Pex** [comment]
@cstiens A clock, really? Interesting. There should be no way the clock is shown in Zom, we show a single check instead.

**Comment by cstiens** [comment]
R’s phone
Model: iPhone SE
OS: 10.3.2

C’s phone
Model: iPhone 6
OS: 10.3.3

**Comment by chrisballinger** [comment]
Can you also include the version and build # in your reports?

e.g. Zom 1.2.3 (123)

**Comment by cstiens** [comment]
> Can you also include the version and build # in your reports?

Yes, we can. These have been around for a while, so I don't know exactly which builds they were on. I guess we could probably extrapolate it from the date. Moving forward, I'll be sure to include build numbers.

**Comment by N-Pex** [comment]
I think we need to retest this again, lots has changed since.

**Comment by tiffrobo** [comment]
Not seeing this in 125. It helps to indicate when the user is offline/online. Should keep an eye on it.

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: version 125
