### ISSUE TITLE
Deleting Contact

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#49]
There should be an option to delete contacts. Currently, when I click on a contact, it shows the tick mark that either can be used for Group Chat or start Private Message.

Right now, when I swipe a chat to the left, it gives me option to delete the chat. Can we have similar option for deleting a contact in the buddy list?

**Comment by davidchiles** [comment]
Working on this. Related to #36.

**Comment by n8fr8** [comment]
This is implemented partially in the new TestFlight beta. Open the new chat/contacts screen, swipe to the left, and press delete!

However, more work needs to be done.

**Comment by gekhung** [comment]
Yeap, tried that and it's working ;) Thanks!
