### ISSUE TITLE
"+" button and "microphone/audio" whited out in chat 

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#492]
During testing today we saw this. Remained after force quitting the app. Both in single chat and group chat. 
You could still use the buttons by tapping on the area. 

![img_efc26a6bd9b4-1](https://user-images.githubusercontent.com/30634981/34119121-a16e9a74-e3e6-11e7-825c-172ed27db2bc.jpeg)

Device: iPhone 7 and iPhone SE
App Version: Build 113

**Comment by cstiens** [comment]
Fixed! Thanks
