### ISSUE TITLE
Messages sent are sending a second time from 'self' as a contact

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#495]

**Comment by chrisballinger** [comment]
I've been working on this today

**Comment by chrisballinger** [comment]
Fixed in this commit: https://github.com/ChatSecure/ChatSecure-iOS/commit/b0adfa742ff28f346b657db24a1273323baaae31

**Comment by chrisballinger** [comment]
I saw this happen again for myself, but only once so far. I believe it happened because I received a reflected message from the room that didn't have my full JID attached to it, and was instead attached to a new room occupant with a JID matching the room itself.
