### ISSUE TITLE
iOS Stuck in Pending Approval with new friend request from Android

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#506]
- B (android) scans T's iOS device's QR code. 
- T (iOS) receives a friend request. 
- T accepts friend request (taps green checkmark). 
- B and Ts keys are exchanged and they are friends. 
- T (iOS) sees B in her contact list with 'Pending Approval' next to their name. Opens a new chat with B, but sees 'Pending Approval' screen. Tries tapping refresh. 
- B (android) is able to send messages to T and gets double checks. 
- T (iOS) sees the new message in the local notification in the convo view snippet, but when she taps on the message she still sees 'Pending Approval' in the chat view.

If iOS (T) scans the Android (B) device's QR code there are no 'Pending Approval' issues.

Not sure if this is an Android or iOS bug @n8fr8 

Device: iPhone 7, iPhone 6, iPad
OS: 11.2.2/10.3.3/10.3.3
App Version: Build 114

**Comment by cstiens** [comment]
@N-Pex This issue is resolved if the Android contact verifies the iOS contact.

**Comment by N-Pex** [comment]
So this is not an iOS bug, it's the Android side not answering automatically.

**Comment by tiffrobo** [comment]
This will be fixed on the Android side.
