### ISSUE TITLE
'Add friends' option disappears occasionally in group chat members view for admin 

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#514]
We have seen the 'add friends' option be finicky in group chat for admin.  Occasionally, the option to 'add friends' is not available for the admin of the group. If it not available (disappears) it will reappear if you either:

1. You force quit and restart the app OR
2. Tap back (out) of the Members List view and then retap "i" (back into the Members List view). 

Devices: iPhone 7, iPhone SE
OS: 11.2.2, 10.3.2
App build: 115

**Comment by N-Pex** [comment]
Ok, it will update correctly in build 118. However, "modify subject" and "add friends" will only be visible if you are an admin AND you are online. We could make sure to "remember" your role, so they could be shown even when offline, but I don't think the operations themselves would work (i.e. be queued).

**Comment by cstiens** [comment]
>  We could make sure to "remember" your role, so they could be shown even when offline, but I don't think the operations themselves would work (i.e. be queued).

This would be nice. Perhaps we could still show the option, but gray it out if you are offline. That way people don't wonder what happened to it. 

I'm marking this as low priority for now.

**Comment by N-Pex** [comment]
Fixed in 124.

**Comment by tiffrobo** [comment]
Haven't seen this in awhile. Working.

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125
