### ISSUE TITLE
Me -> Settings -> Other -> Share text wrong

### ISSUE THREAD

**Issue by tladesignz** [zom/Zom-iOS#518]
Says "Chat with me securely: https://chatsecure.org". Should probably point to https://zom.im?

**Comment by cstiens** [comment]
@chrisballinger to add to the branding p-list.

**Comment by N-Pex** [comment]
Currently Zom does some on-the-fly adjustments to the view, have a look in ZomSettingsManager.swift. Would be great to remove this hackish approach and use branding.plist or similar for all of them.

**Comment by cstiens** [comment]
The text now send the zom link! Thanks.
