### ISSUE TITLE
Change Navigation bar color for adding a friend to Zom using SMS 

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#522]
I want to invite a friend to Zom using SMS. I tap 'Add Friends' then tap 'SMS'. A new screen opens with an autogenerated message.  You just type in the phone number or contact’s info.

- Currently, within this view, the Navigation bar is white making 'Cancel' extremely hard to see. As the user, I thought there was no way to cancel, exit or go back. I force quit and restart the app. 

Device: iPhone 7
OS: 11.2.2
App Version: 116

**Comment by N-Pex** [comment]
Thanks to Apple bug http://openradar.appspot.com/radar?id=6165359065300992 the navigation bar background color is impossible to change without affecting other parts of the app, but at least I could somewhat hackishly apply a workaround that makes the cancel button visible.

**Comment by cstiens** [comment]
Lovely! Thank you!
