### ISSUE TITLE
Photo sent displays as link also

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#523]
- T sent a photo to group chat and sees the sent photo as well as a link. 
- The link is only seen on the sender side. 
- Ts account is on the staging server. 
- She has seen this a few times, but it doesn't always happen.

![img_3863](https://user-images.githubusercontent.com/30634981/35525293-b0a16494-04e9-11e8-85b0-f16c5bce6821.PNG)

Device: iPhone 7
OS: 11.2.2
App version: 117

**Comment by N-Pex** [comment]
Should be fixed now, MAM catchup issue where we didn't recognize that message was already in our DB.

**Comment by cstiens** [comment]
Fixed!
