### ISSUE TITLE
App goes into deadlock

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#526]
The app goes into deadlock often. 
The steps taken vary. Sometimes the app freezes after tapping 'send' in a group or single chat. 
Other times the app goes into deadlock while in profile or convo view. 
Force quitting and restarting the app resolves the issue. 

Device: iPhone 7
OS: 11.2.2
App version: 117

**Comment by N-Pex** [comment]
Should be fixed in 118.
