### ISSUE TITLE
We need tabs for Zom UI

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#53]
The UI must match the Android UI

**Comment by n8fr8** [comment]
"When I go to Whatsapp, it has five main menu drops: Favorites, Recents, Contacts, Chats, and Settings. 
And when I go to WeChat, it has four main menu drops: Chats, Contacts, Discover, and Me. 
But when I go to Zom, I don't see any menu drops except Chats and (i). I think this lack of menu makes it hard for people to navigate instinctively and turns people off from the get-go."

**Comment by cstiens** [comment]
@N-Pex Great work! Will you make the icons in the tabs a little smaller so they visually match Android?
Once that's done, we'll be good to go on this ticket.

**Comment by N-Pex** [comment]
@cstiens Like this (version 52)? =)

**Comment by n8fr8** [comment]
Looking good!

**Comment by cstiens** [comment]
Perfect!
