### ISSUE TITLE
Feedback & Delivery receipts not rendering in group chats

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#538]
@chrisballinger Can you have a look at this ASAP? It may be a quick fix. I'm not sure. What's happening is — for some messages sent within a group chat, the sender does not get any feedback (i.e. check or double check) after sending. Most times, the message does go through, but the sender doesn't ever get any checks.

I believe this is isolated to group chats and not happening in single chats, but I need to test more to verify that.

This may be related to: https://github.com/zom/Zom-iOS/issues/501

**Comment by tiffrobo** [comment]
I'm seeing delivery receipts on all messages sent in group chat. Maybe keep an eye on it...

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: version 125
