### ISSUE TITLE
Rejected by Apple due to ability to skip onboarding?

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#539]
It seems like on an iPad you can dismiss the onboarding, which leads to a blank "me" tab. We need to not let onboarding to be skipped, or show a "setup account" button in the blank me tab.

"Your app or its metadata does not appear to include final content. Specifically, your app’s profile option is blank and the user is unable to sign in or view a profile.

Please see attached screenshots for details.

Next Steps

To resolve this issue, please review your app and metadata to ensure that all of its content is final.

Since your iTunes Connect status is Rejected, a new binary will be required. Make the desired metadata changes when you upload the new binary.

NOTE: Please be sure to make any metadata changes to all app localizations by selecting each specific localization and making appropriate changes."

![attachment-8869495187671786069screenshot-0210-132920](https://user-images.githubusercontent.com/30851/36066877-5f402752-0e80-11e8-813f-05ad87fca99f.png)
![attachment-7503364989490676866screenshot-0210-132927](https://user-images.githubusercontent.com/30851/36066878-5f64198c-0e80-11e8-9c32-83e9d9dbd002.png)

**Comment by N-Pex** [comment]
looking into it

**Comment by N-Pex** [comment]
Still haven't figured out how you can actually skip it.

**Comment by cstiens** [comment]
@N-Pex I found a way to skip it. 

In the very first onboard view, I selected 'Switch Language'. I chose Indonesia, then 'save'. After tapping 'save' it skipped the rest of onboarding and went into the app. Though, after that, I tapped on all of the tabs and back to the convo view and the 1st onboarding screen popped up again.

I agree with @n8fr8 that as a fallback we could add the setup options in the account view, if there's no account setup. https://github.com/zom/Zom-iOS/issues/540

**Comment by cstiens** [comment]
If you need me tomorrow, please Zom me.

**Comment by N-Pex** [comment]
Ok, thanks, I was able to reproduce it now! Strange, thought I tried that, but it was in a simulator.

I've fixed it now, so at least you can't skip using this method.

**Comment by chrisballinger** [comment]
I'm also wondering if they can't figure out that ">>" is the next button. Perhaps it would be more clear if it said "Next >>"
