### ISSUE TITLE
Add setup options in 'me' tab if no account is setup

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#540]
Add the options to 'Create an account' or 'Sign into an existing account' in the me tab if there is no account.

**Comment by cstiens** [comment]
This view could have the same graphic and buttons as the second view in onboarding.

**Comment by tiffrobo** [comment]
Resigning into an old account:
Upon deleting my account and tapping 'new account' I actually signed into a previous account and it worked. It did take a minute to recognize my account.

New account:
Testing again, it takes time to process the new account. I deleted an account, tapped 'new account' created a new account and it was processing for a long time. Finally, I saw 'congratulations' and my new account was signed in.
Every time I created a new account it took some time to process. Some times longer than others, but it always worked. 

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125
