### ISSUE TITLE
UI for group enhancements

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#542]
@N-Pex Here are the interactions for selecting a member from the group profile—
* If you are a group admin, you get a shortcut for admin features displayed in an action sheet. See mockup below.

Tapping on 'Make group admin' returns the user to the member list with that person indicated as an admin.
Tapping on 'view profile' opens the profile
Tapping on 'kickout' removes the person from the list. The member is removed from the list for everyone in the group. I assume we'll probably need to talk about this one. For the person that gets kicked out, the group shouldn't exist for them anymore. Though, we probably need to give them feedback about what happened.

* If you are a non-admin, you are taken to the member's profile. If the person is your friend, you see the profile the same as you do in the friends view. If they are not your friend, you get the option to add them as a friend. We're still finalizing the improved UI for these profile views.

Android ticket: https://github.com/zom/Zom-Android/issues/435

![profile-group_ios-admin-shortcut](https://user-images.githubusercontent.com/1434597/36211389-be33edaa-1166-11e8-995c-44d0f4d05812.png)

**Comment by N-Pex** [comment]
Ok, started on this. Let's discuss more on Monday, I think we may need to implement the full set of operations here, like an owner "revoke admin" for an admin, or "promote to owner" etc..

**Comment by N-Pex** [comment]
Also, on iOS the standard form sheet does not contain header views or icons (and we can't fake them with an icon font unfortunately). So we either have to roll our own (maybe some good lib out there?) or go with the vanilla text-only form sheet.

**Comment by cstiens** [comment]
Vanilla form sheet is fine. We'll test this one!

**Comment by tiffrobo** [comment]
All these enhancements are in:
-make admin
-kick out
-view profile
-cancel


Device: iPhone 7
OS: 11.2.2

Device: iPhone 6
OS: 10.3.3

Device: iPad
OS: 10.3.2

App version: 126
