### ISSUE TITLE
Add in-line text when someone new is added to the group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#544]

**Comment by cstiens** [comment]
@N-Pex do/can we know when someone is added to a group versus when they join a group. I'm thinking about having text for both cases.

"Rosa invited Julie to the group." and "Julie joined the group."

**Comment by cstiens** [comment]
Since we only know when someone joins a group, we would show text that says— "Julie joined the group."

<img width="371" alt="screenshot 2018-03-21 13 50 13" src="https://user-images.githubusercontent.com/1434597/37730905-d24513b4-2d0e-11e8-93f7-7da367ec2cc6.png">

If someone joins and they are not your friend, you would get the inline prompt to add them.

<img width="371" alt="screenshot 2018-03-21 13 49 46" src="https://user-images.githubusercontent.com/1434597/37730938-e37fb530-2d0e-11e8-9a65-e726b38bdbb9.png">

**Comment by tiffrobo** [comment]
In build 127, I see the in-line text when someone who is **not** your friend joins the group, but I don't see when a 'friend' of yours joins/ is added to the group. 

Device: iPhone 7, iPhone 6, iPad
OS: 11.2.2, 10.3.3, 10.3.2
App version: build 127

**Comment by cstiens** [comment]
@N-Pex Can we show both? If the person is already your friend, but added to the group, we would include that inline.

**Comment by tiffrobo** [comment]
Who should see the in-line text? If the owner adds people to the group will they see the in-line text?

This is really buggy. I saw it appear once as a flash. Once it was there and appeared to be working and the other three times it never appeared to anyone in the group. 

Looks good when it appears:)
![img_4827](https://user-images.githubusercontent.com/30634981/39059997-b763e9ba-4485-11e8-9a11-3ed97221c567.PNG)


Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129

**Comment by cstiens** [comment]
I made a new ticket for the bug: https://github.com/zom/Zom-iOS/issues/595
