### ISSUE TITLE
Downloading a photo from Zom to your phone (local gallery storage) crashes the app

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#547]
If I open a photo to fullscreen in Zom and tap 'share' icon then tap 'save image', zom crashes everytime! It doesn't matter if you open the photo from a chat or the photostream. 

Device: iPhone 6+
OS: 11.2.5
Device: iPhone 7
OS: 11.2.2
Build: App version 124

**Comment by N-Pex** [comment]
Ok, Apple requires a new flag in the info.plist. Fixed in 125.

**Comment by tiffrobo** [comment]
Working. 
Currently you tap 'save image' downloading the photo to your gallery, but the screen view never changes out of Zom photo view. Not 100% sure what happened, or if it worked. It's nice in a way because you don't have to switch between any views. You can just continue on with chatting. 

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125
