### ISSUE TITLE
Sharing a photo from my gallery to Zom crashes the app and photo gets stuck processing

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#548]
Sharing a photo from my gallery to Zom crashes sometimes. 
But, every time it crashes the photo shared is stuck in processing. 

- I am in my device's photo gallery, tap on a photo, tap share, tap Zom. 
- Zom opens and I chose a contact or group. App crashes. 
- When I open zom again I see the photo in the group or chat I was wanting to share it with, but the photo is stuck in processing mode. 

I have taken these same steps and it works perfectly. Doesn't matter if I'm sharing with a group or single chat. 

![img_4251d664dea7-1](https://user-images.githubusercontent.com/30634981/36326990-a6c70c70-1322-11e8-8379-56dc6dac4550.jpeg)

Device: iPhone7
OS: 11.2.2
App version: 124

**Comment by N-Pex** [comment]
I managed to duplicate this by:

1. Share an MP3 from email app to Zom, single chat
2. Chat was entered
3. Go back to conversations list
4. Re-Share the MP3 from the email app, select same single chat
5. Crash

**Comment by N-Pex** [comment]
Should be fixed in 125.

**Comment by tiffrobo** [comment]
Working and I have not seen any crashes or photos being stuck in processing.

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: 125
