### ISSUE TITLE
Prompt to add people as friends in group chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#551]
@N-Pex I attached a screenshot of what we're thinking. We're finalizing the icon and sizing. But, in general—this would be the display anytime there are people joining the group that aren't your friend. So, the first time you join a group, or later in time when the admin adds a new person that isn't your friend, you would be given a chance to add them as a friend (ie send a friend request) in-line in the chat. As we talked about, this would only display once, rather than multiple times.

We'll share the full workflow for what happens when you tap the 'add friend' icon and the case for 1 person that's not your friend versus multiple. But, I wanted to go ahead and get the concept to you. Thanks, c

**Comment by cstiens** [comment]
Ooops. Forgot to add the screenshot earlier. Kaci will upload the designs shortly.

**Comment by kckthx** [comment]
[Group_Add_Friendsv2.zip](https://github.com/zom/Zom-iOS/files/1745930/Group_Add_Friendsv2.zip)
Here are all the screenshots for the flow to add friends from a group. There is a subfolder with all the specs listed out as well. 

The New member 2.0-2.1 acts just like the verification flow.

**Comment by kckthx** [comment]
@N-Pex @cstiens here is the Add Friend icon at 90x90px selected and unselected. Let me know if you need other sizes. 

![zom_add_friend_selected_90](https://user-images.githubusercontent.com/36669955/36546134-38f87480-17b0-11e8-8d90-5f20053b5e07.png)
![zom_add_friend_unselected_90](https://user-images.githubusercontent.com/36669955/36546135-39132be0-17b0-11e8-8e6a-ff2629cad30c.png)

**Comment by N-Pex** [comment]
Will be present in build 127.

**Comment by tiffrobo** [comment]
This is awesome! Great work! 
It took a bit of time to render the rosters and in-line text, but everything is in and seems to be working! 

Device: iPhone7, iPhone6, iPad
OS: 11.2.2, 10.3.3, 10.3.2
App version: build 127
