### ISSUE TITLE
Update text for account migration

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#560]

**Comment by cstiens** [comment]
Let's talk about this on a scrum. In this phase we aren't doing any UI or UX changes*. We are only updating strings. The images below show the strings we need to change with the new text above.

![ios-unblockability-migrator](https://user-images.githubusercontent.com/1434597/38389305-a325e974-38e3-11e8-891b-ec5bb3215279.png)

![ios-unblockability-friends](https://user-images.githubusercontent.com/1434597/38389350-cf0d8bf0-38e3-11e8-8169-f03c65ffd9d2.jpg)

**Comment by cstiens** [comment]
@N-Pex These are ready and should be pretty low hanging fruit. We just need to change strings.

**Comment by N-Pex** [comment]
Fixed in 130.

**Comment by tiffrobo** [comment]
All the wording is updated! And migrating acts as I would expect!
One thing,  I see when migration is complete instead of being brought to convo view, you are taken to accounts view. We wanted the view after successful migration to be convo view. Is this possible @N-Pex ?

**Comment by tiffrobo** [comment]
Being taken to account view after the migration is fine! Closing this ticket.
