### ISSUE TITLE
Option to not join a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#563]

**Comment by cstiens** [comment]
@N-Pex We can discuss this on our call tomorrow. But, basically we want to add a UI view that gives the user the option to not join. Technically, they will be added to the group as they are now, but by saying 'no' to joining, they are actually just 'leaving' before they see the group chat view.

This view would be one that is shown the first time you tap on the new group chat in your convo view.

<img width="371" alt="screenshot 2018-03-26 16 02 49" src="https://user-images.githubusercontent.com/1434597/37932899-508389be-310f-11e8-9845-f50415d06989.png">

**Comment by tiffrobo** [comment]
I am seeing this 'Option to join/decline' the group in build 127.

- You don't see who asked you to join, just 'someone'
- If you tap 'join' you are taken into the group chat.
- If you tap 'no thanks' you are taken back to your convo view and the group is not listed in this view.

However, there is a glitch #576 

Devices: iPhone7, iPhone6, iPad
OS: 11.2.2, 10.3.3, 10.3.2
App version: build 127
