### ISSUE TITLE
UI for encrypted groups

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#567]
@N-Pex When you turn on 'encrypted groups' in the settings, it should give the option within each group to turn it on. But, that option (within a group) should be off by default. Users would need to turn on group encryption per group to use it. Can you fix this?

In the current build, when you turn on encrypted groups in the global settings, it turns it on in all the groups.

**Comment by tiffrobo** [comment]
This is fixed! Thank you!

Device: iPhone7, iPhone6, iPad
OS:  11.2.2, 10.3.3, 10.3.2
App version: build 127
