### ISSUE TITLE
UI Glitch showing add friends module in convo view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#569]
Add friend module shows up randomly at times. These steps seems to cause it:
* On main screen 
* Went to discover
* Back to main stream
* Add friend module pops up

Build 126

**Comment by tiffrobo** [comment]
I did not see this today during testing! I will close the ticket, but keep an eye out for it!

Device: iPhone7, iPhone6, iPad
OS: 11.2.2, 10.3.3, 10.3.2
App version: build 127
