### ISSUE TITLE
Fix button color for add friends

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#572]
@N-Pex will you make the button background the highlight color?

![addfriends](https://user-images.githubusercontent.com/1434597/38101663-8691ec60-3346-11e8-9d65-f7455b23e00d.PNG)

**Comment by tiffrobo** [comment]
The 'Add Friends' button now has a red background. Fixed
![img_0293](https://user-images.githubusercontent.com/30634981/38569917-2c166b38-3cb2-11e8-82c6-968bf134cdb9.PNG)

Device: iPhone 6, iPad
OS: 10.3.3
OS: 10.3.2
App version: build 127
