### ISSUE TITLE
No keys for self in group chat

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#575]
Within Group Chat,  in the roster view, tap on myself (Tiff), tap 'view profile' and I have no keys for myself. 

This is for all group chats. 

Device: iPhone 7
OS: 11.2.2

Device: iPhone 6
OS: 10.3.3

Device: iPad
OS: 10.3.2

App Version: Build 126

**Comment by tiffrobo** [comment]
Still no codes for self in group roster. 
![img_0612](https://user-images.githubusercontent.com/30634981/39058794-6ee6848e-4482-11e8-99bf-cb734c6e486d.PNG)
![img_0613](https://user-images.githubusercontent.com/30634981/39058795-6efa73b8-4482-11e8-9799-c6a77b7e1a59.PNG)


Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129

**Comment by cstiens** [comment]
These are in now! Thanks
