### ISSUE TITLE
Splash Screen Invite SMS Link

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#58]
On the splash screen (image attached) the "Invite SMS" option is redundant since the "Sha...ite Link" also gives you an option to share the link via Message. Also when you use the Invite SMS link it doesn't include a link.

**Comment by rosagp** [comment]
![img_7476](https://cloud.githubusercontent.com/assets/4604279/12208997/4b49945c-b61e-11e5-82a6-837248846c19.jpg)

**Comment by N-Pex** [comment]
This was fixed in an earlier release.
