### ISSUE TITLE
Wording update for add friend prompt

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#580]
@N-Pex Instead '3 people are not your friends' say '3 people joined who are not your friends'

![img_0603](https://user-images.githubusercontent.com/1434597/38639700-a38a009a-3d97-11e8-9217-0c0c3bba7bad.PNG)

**Comment by tiffrobo** [comment]
In and working!

Build: iOS 124
Device: iPhone 6, iPhone 7,  iPhone 6+
OS: 10.3.3, 11.2.2, 11.2.5
App version: build 129
