### ISSUE TITLE
Workflow from group contact profile

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#582]
From the group info view
- [ ] Remove 'i' icon next to each member
- [ ] If the user taps anywhere on the list item, the profile would open. Unless, the user is an admin. In that case, the admin user would see the shortcut action sheet.

**Comment by N-Pex** [comment]
@cstiens Um, I am not sure I've seen how this should work/look. Right now they seem to be 2 different thing - tapping a user opens up "old" profile view, tapping the "i" opens up the new "codes" view. How should those two be tied together, if at all?

**Comment by tiffrobo** [comment]
@N-Pex See https://github.com/zom/Zom-iOS/issues/579#issuecomment-385196472

>  tapping the "i" opens up the new "codes" view. How should those two be tied together, if at all?

We should remove the 'i', so the only action on the contact list is to tap to open the profile.

**Comment by N-Pex** [comment]
Fixed in 130.
