### ISSUE TITLE
Keyboard shows up in Join group prompt

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#583]
![img_0599](https://user-images.githubusercontent.com/1434597/38640358-a5c656d6-3d99-11e8-84d0-7398fbee11ae.PNG)

Device: iPhone7, iPhone6
OS: 11.2.2, 10.3.3
App version: 127

**Comment by N-Pex** [comment]
Happened if the keyboard was left open in a chat, then a another chat with the "join group" view was entered.

**Comment by tiffrobo** [comment]
I haven't seen this while testing. 

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129
