### ISSUE TITLE
Fade out from 'Requested' confirmed after 3 seconds

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#584]
I'm referring to the blue full screen confirmation after you send a friend request. Right now you have to tap out of it.

![img_0597](https://user-images.githubusercontent.com/1434597/38640687-98ff4bbe-3d9a-11e8-8d43-6d8c99bfbaba.PNG)

**Comment by tiffrobo** [comment]
The fade out works, but I noticed it now reads "Added" not "Requested"
Which is preferred?

Device: iPhone 6, iPhone 7,  iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 129
