### ISSUE TITLE
Update 'Settings' view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#588]
- [x] Add 'Move Account' option under the account
- [x] Make the outline of the 'off' toggle gray (#CECECE if we need to specify it)

- [x] Change 'OMEMO Group Encryption' to 'Group Encryption'

- [x] Change description under group encryption to 'Encryption must also be manually enabled for each group.' (This is to match Android wording: https://github.com/zom/Zom-Android/issues/462)

![ios-settings_v2](https://user-images.githubusercontent.com/1434597/39008116-69145a6e-43cd-11e8-92b3-4880ddec3c87.png)

**Comment by N-Pex** [comment]
Will be fixed in build 130.

**Comment by tiffrobo** [comment]
Looks good, except there is one difference....
> Change 'OMEMO Group Encryption' to 'Group Encryption'
Reads "Encrypt group chat" instead of 'Group Encryption' 
This is consistent with the wording in group chat view 

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 130

**Comment by tiffrobo** [comment]
Thank you @N-Pex ! Closing this ticket.

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 133
