### ISSUE TITLE
Splash Screen Share Invite Link 

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#59]
On the splash screen (image attached) the Share Invite Link reads "Sha...ite Link". All the words should appear. It would be better if each option was on it's own line. 

-Invite SMS
-Share Invite Link
-Scan QR
![img_7476](https://cloud.githubusercontent.com/assets/4604279/12209046/a67a5d3e-b61e-11e5-8baf-ebcf7addf930.jpg)

**Comment by rosagp** [comment]
Also, when the link is shared via email maybe the Subject line could be pre-populated with some text like "Let's Zom".

**Comment by n8fr8** [comment]
@N-Pex was the shortened share text also fixed for smaller screens?

**Comment by N-Pex** [comment]
@n8fr8 This whole screen has been removed now, replaced by the new final onboarding screen "Your account has been created/create avatar" page(?)

**Comment by n8fr8** [comment]
Oh you are right, since we then send them right into the screen with the "Add Friends to Zom" button. Got it.
