### ISSUE TITLE
New "Add Friends" UI

### ISSUE THREAD

**Issue by kckthx** [zom/Zom-iOS#590]
![add-friends_p2_v3-android](https://user-images.githubusercontent.com/36669955/39056335-0bb03ed8-447c-11e8-8627-819ae2ff4f2b.png)

![add-friends_p2_v3-android-specs](https://user-images.githubusercontent.com/36669955/39056212-ae3a2ac0-447b-11e8-8d27-503839f5fab3.png)

[Add-Friends-Illustration.zip](https://github.com/zom/Zom-iOS/files/1932444/Add-Friends-Illustration.zip)

**Comment by n8fr8** [comment]
whatsapp:// custom URI scheme https://faq.whatsapp.com/iphone/23559013
for @tladesignz

**Comment by tladesignz** [comment]
@kckthx Can you or @cstiens provide the icons, too? I hope, they will be more uniform, than when I go search them on the net. :-)
Please note:
- WeChat support was dropped - not possible in that way without integrating the WeChat API using a registered API key.
- Instead of the "nearby" symbol, we would need an "AirDrop" symbol.
- According to iOS interface guidelines, the "share" button should look a little bit differently, than three dots ("..."). See https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/system-icons/ (search "share" on that page)

**Comment by tladesignz** [comment]
Also: Please define, what should happen, 
- when there's no WhatsApp
- when we can't use the camera for QR code scanning (could be dennied or in other ways unavailable)
- when there is no possibility to send SMS/iMessage. (can happen theoretically, at least in the Simulator, probably when iMessage is disabled and there is no SIM card available.)

Should we
1. grey out buttons
2. hide buttons
3. show error message after button press
4. other?

**Comment by cstiens** [comment]
@tladesignz Sorry for the slow response to your questions. Here you go!

> WeChat support was dropped - not possible in that way without integrating the WeChat API using a registered API key.

Okay. We can leave that out.

> Instead of the "nearby" symbol, we would need an "AirDrop" symbol.

Yes. Kaci has provided airdrop. You can ignore the nearby. We've added that to the Android ticket.

> According to iOS interface guidelines, the "share" button should look a little bit differently, than three dots ("..."). See https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/system-icons/ (search "share" on that page)

Yeah. We're breaking the rules again here. Please use the 3 dots to indicate that there are more options.

> Also: Please define, what should happen, when there's no WhatsApp

Don't show it. Only show iMessage and the 3 dots.

> when we can't use the camera for QR code scanning (could be denied or in other ways unavailable)

If the user has denied camera access, we should still show scanning as an option, and if tapped, we should ask again to allow access to the camera. We've had cases in testing where the user accidentally denies the request to use the camera, but wants to scan. So, we want to give them (and continue to give them) second chances.

If for some reason, there is no camera available at all, then we can hide the scan option. In what cases, will there not be a camera available at all?

> when there is no possibility to send SMS/iMessage. (can happen theoretically, at least in the Simulator, probably when iMessage is disabled and there is no SIM card available.)

Don't show it. Only show the 3 dots.

**Comment by kckthx** [comment]
[Add-Friends-From.zip](https://github.com/zom/Zom-iOS/files/1968255/Add-Friends-From.zip)
@tladesignz 
Sorry I misunderstood what icons you were needing
this zip folder has the WhatsApp, iMessage, QR Code and More

**Comment by tladesignz** [comment]
@N-Pex: What's the best way to read the user's Jabber ID?

**Comment by N-Pex** [comment]
@tladesignz In ZomNewBuddyViewController you can just access (self.account as? OTRXMPPAccount)?.username

**Comment by tladesignz** [comment]
@N-Pex: D'oh! Thanks! I'll spare the cast, though. username is a OTRAccount property.

**Comment by tiffrobo** [comment]
The new UI looks and functions great! Thank you for all the work. 

@tladesignz There are two things:

1) The bar at the top just needs the back arrow. Not the label with it 
<img width="386" alt="screen shot 2018-05-07 at 1 57 18 pm" src="https://user-images.githubusercontent.com/30634981/39719414-bfd77f36-51fe-11e8-83be-f0da9038afd2.png">

2) The new 'add friends' screen on the iPhone6, you must scroll to see everything. It is not the case for the iPhone 7

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 130

**Comment by tiffrobo** [comment]
@tladesignz This screenshot pertains to #1. from the above comment. When you tap + (add freinds), the bar at the top has the back arrow and label. We just need the back button arrow.

![img_e49afdcbb823-1](https://user-images.githubusercontent.com/30634981/39835687-8c594d94-5396-11e8-958a-512cb4d6cfb3.jpeg)

**Comment by tiffrobo** [comment]
@tladesignz I'm closing this ticket. A new ticket with the specific UI enhancements needed for the 'Add Friends' view are on ticket #607 .
