### ISSUE TITLE
Setting Up Account 'Congratulations' screen cut off 

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#591]
When I un-install and re-install an account on the iPhone 6, the 'Congratulations' screen always looks like there are two screens. One overlaying the other and you can tell because one is cut off. Apologizes for a poor explaination. Here is the screenshot. 

![img_0610](https://user-images.githubusercontent.com/30634981/39056583-c4fa35d8-447c-11e8-883d-50f102387dbf.PNG)
I have seen this with the last two new builds, always on the iPhone 6. Sometimes on the iPhone 7
Device: iPhone 6
OS: 10.3.3
App version: Build 129

**Comment by tiffrobo** [comment]
Still happening in build 133.

**Comment by N-Pex** [comment]
Should be fixed in 134.

**Comment by tiffrobo** [comment]
I haven't seen this during testing of build 135.

Device: iPhone 6, iPhone 7, iPad
OS: 10.3.3, 11.2.2, 10.3.2
App version: build 133
