### ISSUE TITLE
Zom codes are cut off in zom code view

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#598]
The zom code(s) in the new key view ('zom code') view are cut short.

![img_4880](https://user-images.githubusercontent.com/30634981/39436367-6394cabc-4c63-11e8-9989-bfe3cbcc7291.PNG)
![img_4881](https://user-images.githubusercontent.com/30634981/39436368-63ab5502-4c63-11e8-87c7-e4298942a208.PNG)

Device: iPhone7
OS: 11.2.2
App version: build 129

**Comment by cstiens** [comment]
Fixed! Thank you.
