### ISSUE TITLE
Grey out 'leave' option until you choose a new admin

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#601]
I created a group. 
Within my chat view I swiped the chat left to delete the group.
It asked me to choose an admin before leaving, but instead of choosing an admin, I tapped 'Leave' and it deleted the group from my chat view. 

Make 'Leave' grey until you select a new admin.

![img_4909](https://user-images.githubusercontent.com/30634981/39716787-e341a166-51f6-11e8-995e-5bbc29ebd8b7.PNG)

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 130

**Comment by N-Pex** [comment]
Ok should be fixed in 134.

**Comment by tiffrobo** [comment]
Great! This is in and working!

Device: iPhone 6, iPhone 7
OS: 10.3.3, 11.2.2
App version: build 135
