### ISSUE TITLE
Signed back into my account, and had no keys for my contacts

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#604]
I've been signed out of my carriezomios account off and on because I use it on a test device. When I logged back in to test, I noticed that I don't have any OMEMO or OTR keys for any of my contacts (in their profile or in groups). I did get an OMEMO key for one Android contact after some time. It was also after they had sent me a message. I think this is related to the overall issue we're having with keys not being fetched.

The other contributing thing that may be causing this scenario, is that I haven't talked to many of my contacts from this account in a while.

Device: iPhone 6
OS: erg. went to check and it started automatically updating to 11.3.1
Build: 130

**Comment by tiffrobo** [comment]
@cstiens will you test this one, please?

**Comment by tiffrobo** [comment]
Just tested this and it is still a problem. I signed out of my account and signed back in and I have no keys for any contacts!

Device: iPhone 7
OS: 11.2.2
App version: build 133

**Comment by tiffrobo** [comment]
Not seeing this issue in the latest build. 

Device: iPhone6, iPhone 7
OS: 10.3.3, 11.2.2 
Build 135
