### ISSUE TITLE
In 'Add Friends' pull WhatsApp and iMessage icons from app code

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#605]
@N-Pex @tladesignz Is there any way on iOS that we can pull the app icons for WhatsApp and iMessage from their app code instead of using static images in our UI. If we can make them live, we would avoid being outdated. ;) I know we've done this on Android in the past.

**Comment by tladesignz** [comment]
Sorry, but this is not possible. Apps don't have access to stuff outside their sandbox and other's apps icons *are* on the outside. Besides that, these icons can change in a way, which could break our design, so in that regard, that's also not a good idea.

Even though this might be possible on Android, it's discouraged to do so there, too.

The only way I could think of to achieve something like this, would be by loading icons from a web service. But that would introduce a dependency on a (foreign) web service and add dangerous traffic which might leak information.

**Comment by cstiens** [comment]
Got it. Thanks!
