### ISSUE TITLE
In 'Add friend' view, auto-add '@home.zom.im' when friends are manually entered

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#606]
@N-Pex We've discussed this briefly. In the 'add friends' view, if someone only enters a name (ex: carrie) and no server (ex: @home.zom.im), will you add the logic to automatically add the '@home.zom.im' to the entry, so that the user has a better chance of actually adding someone?

Let me know if you have questions. We do this on Android already.

**Comment by tiffrobo** [comment]
In and working!

Device: iPhone 7,  iPad
OS:  11.2.2, 10.3.2
App version: build 131
