### ISSUE TITLE
Extra space in the profile view inline 'add soandso as Friend'

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#612]
Within a contact's view the inline 'add friend' has an extra space after the contacts name before the 'as Friend'

![img_4967](https://user-images.githubusercontent.com/30634981/40074438-393dbe1c-583f-11e8-9939-bf75ca93205f.PNG)

T's phone
Device: iPhone 7
OS: 11.3.1
App version: build 130

**Comment by N-Pex** [comment]
@tiffrobo That's odd, I don't see that in the code and I can't reproduce for my contacts. Maybe there's a space in the display name, so it really is "Hey you "?

**Comment by tiffrobo** [comment]
@N-Pex Good to know it's not in the code! I think you are right, the user may have typed in an extra space when creating their account. I tested it a few times and am not seeing it. I will close the ticket!
