### ISSUE TITLE
YapDatabase Module not found

### ISSUE THREAD

**Issue by imoamen** [zom/Zom-iOS#614]
Hi 
I followed the steps for building as was written 
all of it was successful 
but whenever I try to build the project I got 3 errors 
1- YapDatabase Module not found 
2- could not build Objective-C module 'ChatSecureCore'
3- parse error YapDatabase module not found 
all related to  OTRYapDatabaseObject.h file  in ChatSure/Classes/Model/Yap Storage
I tried twice, deleted the 1st project and repeated the steps all over again with no success  
Any help is appreciated 
thanks
<img width="1140" alt="screen shot 2018-05-16 at 10 19 12 am" src="https://user-images.githubusercontent.com/12822814/40102728-f298da90-58f3-11e8-93a6-c823f3272f8d.png">
<img width="570" alt="screen shot 2018-05-16 at 10 20 11 am" src="https://user-images.githubusercontent.com/12822814/40102729-f2b98592-58f3-11e8-8d9e-c1b5efc3e83e.png">

**Comment by tladesignz** [comment]
Switch on the "Find Implicit Dependencies" build option in the "Zom" scheme, if it is disabled.
Clean before trying to build again. (Product -> Clean)

Steps to achieve this:
- In the drop-down menu select: Product -> Scheme -> Manage Schemes... 
- Select "Zom" scheme 
- Press "Edit..." button
- Select "Build" tab
- Select checkbox for "Find Implicit Dependencies"

(There's shorter ways - I'll leave that to yourself to find them... :-) )

**Comment by imoamen** [comment]
thanks a lot man, it worked (but it crashed :D but that probably because of me messing around)
thanks again
