### ISSUE TITLE
'Add Friends' background layout to fit all screen sizes

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#616]
@tladesignz @cstiens The blue background doesn't fit all screen sizes. Do we need a new UI or just a larger file size? 
Regarding the size:
On an iPhone 4s, there's obviously not enough room. I attached a screenshot. You could change the design, to fit all buttons on the screen, but, as far as I can see, that would basically mean to drop the background image.
![image](https://user-images.githubusercontent.com/30634981/40800964-63138da8-64d7-11e8-8739-07d27cab0984.png)

ipad
![img_0310](https://user-images.githubusercontent.com/30634981/40801039-91183ab4-64d7-11e8-907c-383354ed1e67.PNG)

Device: iPhone 7,  iPad
OS:  11.2.2, 10.3.2
App version: build 131

**Comment by tladesignz** [comment]
@tiffrobo What exactly do you want me to do with this?

**Comment by tiffrobo** [comment]
@tladesignz We can talk about this on the call Wednesday. How did you originally implement the blue background? Is it in the code?

**Comment by tladesignz** [comment]
It's from the image: [add-friends-illustration.png](/zom/Zom-iOS/blob/master/Zom/Zom/Images.xcassets/new_friends_bg.imageset/add-friends-illustration.png)

**Comment by tiffrobo** [comment]
Updating this ticket from our call.  I will figure out what design works best and send it to you. Preferably in a .pdf

**Comment by cstiens** [comment]
@tladesignz I've made this pdf the width of an ipad pro with the idea that you would crop it to fit different screens. Does this work? Or do you need multiple sizes for different screens?

[img_add-friends_v2.pdf](https://github.com/zom/Zom-iOS/files/2077972/img_add-friends_v2.pdf)

**Comment by tladesignz** [comment]
Yay! That's it!
