### ISSUE TITLE
icons are gone from permissions in group chat

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-iOS#617]
@N-Pex In Group Chat as the owner, you want to pass permissions all the icons have disappeared. The actions are there, but no icons. See #542 
Did we choose to remove them?
![img_5039](https://user-images.githubusercontent.com/30634981/40809774-37472cce-64f1-11e8-83d6-5c3281a32554.PNG)

Icons needed and colors:
![image](https://user-images.githubusercontent.com/30634981/40809911-b3093fe6-64f1-11e8-810d-f2ba64e9b29f.png)

Device: iPhone 7,  iPad
OS:  11.2.2, 10.3.2
App version: build 131

**Comment by N-Pex** [comment]
@tiffrobo Yeah, sort of, adding icons to a an iOS action sheet would mean having to write that functionality ourselves, requiring a lot of work.

**Comment by tiffrobo** [comment]
Ok thank you! I am closing this ticket.
