### ISSUE TITLE
Group Chat List

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#64]
When I try to see who is in my group chat the screen cuts off some people on the list. 

![img_7477](https://cloud.githubusercontent.com/assets/4604279/12209246/c1bd9dbc-b61f-11e5-9349-40e75ca7eaf5.jpg)

**Comment by n8fr8** [comment]
@rosagp is this still happening?

**Comment by cstiens** [comment]
Rosa is no longer having this problem.
