### ISSUE TITLE
Group Chat Delay

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#65]
When I start a group chat, the messages are all very delayed. Recipient receives them eventually but anywhere from 10-20 mins later.

**Comment by gekhung** [comment]
Same issue here. Messages sent from both Android and iOS device to a group chat delays receiving in iOS device.

**Comment by cstiens** [comment]
@davidchiles I tested the group chat with 3 phones in my office (1 iPhone, 2 Androids) and didn't have any issues with a delay.

**Comment by chrisballinger** [comment]
Are these all using the Dukgo server? Perhaps the server is just slow?

**Comment by N-Pex** [comment]
I have not seen this in my testing.

**Comment by cstiens** [comment]
I'm going to go ahead and close this since we haven't seen this in our internal testing this year. If it comes up again once we fix group chat, we'll address it.
