### ISSUE TITLE
Group Chat message

### ISSUE THREAD

**Issue by rosagp** [zom/Zom-iOS#66]
For a group that I started i received a message that said “rosa2016@duckgo.com/zom27040 invited you to the room…"

![img_7478](https://cloud.githubusercontent.com/assets/4604279/12209403/9b524a96-b620-11e5-8ff7-ec8dbe706be0.jpg)

**Comment by davidchiles** [comment]
I'm having trouble reproducing this one. Are there specific steps to trigger this bug or does it just happen randomly?

**Comment by cstiens** [comment]
This is a duplicate of #134 so I'm going to close it.
