### ISSUE TITLE
OTRData offer file length for AUDIO is 0

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#70]
I have confirmed this in the debugger sending from iOS to Android.

The file length header for an inbound audio is 0.

There also doesn't seem to be a file sha-1 hash present.

This doesn't happen for images or stickers, which work just fine.

**Comment by n8fr8** [comment]
Also, I have confirmed that when sending audio from Android to iOS, it does properly handle the OFFER and respond to the GET with the right set of bytes. It seems that something fails in the last step on the iOS side.

**Comment by davidchiles** [comment]
### What I found

It looks like from the volley bellow that we send over the entire audio file. I looked at the file (hexdump) and there are a lot of repeating zeros at the beginning. I don't know the exact file format for .m4a but I wrote the file to disk and it plays fine on the device as well as my computer.

I don't understand why once the file is transferred Android begins asking for the file again from the last bytes to the first? 


#### From iOS to Android
##### iOS sends offer:
```
OFFER otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
File-Length: 27816
Mime-Type: audio/x-m4a
Request-Id: CB16937B-3C74-4771-913E-B019F93F3202
File-Hash-SHA1: 5ef7446a96e11fd4124c3e560d7f7119567af633
File-Name: B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a
```
Android responds
```
HTTP/1.1 200 OK
Request-Id: CB16937B-3C74-4771-913E-B019F93F3202
```
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: da51e42f-9b8c-4c96-8b07-721cd4abaddb
Range: bytes=0-8191
```

iOS sends
```
HTTP/1.1 200 OK
Request-Id: da51e42f-9b8c-4c96-8b07-721cd4abaddb

[DATA]
```

Android responds
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: 1b0d7199-f42c-4808-8e1a-06c856ea91e1
Range: bytes=8192-16383
```

iOS sends
```
HTTP/1.1 200 OK
Request-Id: 1b0d7199-f42c-4808-8e1a-06c856ea91e1

[DATA]
```

Android responds
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: 70971d88-7f01-4249-ba87-065996d09b92
Range: bytes=16384-24575
```

iOS
```
HTTP/1.1 200 OK
Request-Id: 70971d88-7f01-4249-ba87-065996d09b92

[DATA]
```
Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: 6e911f12-9577-4dd0-9a24-1aa327cdf551
Range: bytes=24576-27815
```
iOS
```
HTTP/1.1 200 OK
Request-Id: 6e911f12-9577-4dd0-9a24-1aa327cdf551

[DATA]
```

Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: 56d9c2fa-6f8a-4f9e-93ef-0085aa399534
Range: bytes=24576-27815
```

iOS
```
HTTP/1.1 400 No such offer made
Request-Id: 56d9c2fa-6f8a-4f9e-93ef-0085aa399534
```

Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: b131caec-a893-4be5-8425-d7d9cf14f54c
Range: bytes=16384-24575
```

iOS
```
HTTP/1.1 400 No such offer made
Request-Id: b131caec-a893-4be5-8425-d7d9cf14f54c
```

Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: cf5c17d0-a54f-4ea6-9a44-50bcfd551a06
Range: bytes=8192-16383
```

iOS
```
HTTP/1.1 400 No such offer made
Request-Id: cf5c17d0-a54f-4ea6-9a44-50bcfd551a06
```

Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: 63c497ba-93a6-42f5-a956-e5b5c91598f6
Range: bytes=0-8191
```

iOS
```
HTTP/1.1 400 No such offer made
Request-Id: 63c497ba-93a6-42f5-a956-e5b5c91598f6
```

Android
```
GET otr-in-band:/storage/4FE21BFE-F8D8-4A27-87CE-509A4E39A548/B4F9DAAB-E63A-48A3-ABC2-489EEC91B3F0.m4a HTTP/1.1
Request-Id: cf8fe083-3665-4290-9ec5-e9237b29443c
Range: bytes=24576-27815
```

iOS
```
HTTP/1.1 400 No such offer made
Request-Id: cf8fe083-3665-4290-9ec5-e9237b29443c
```

Keeps on going like this...

**Comment by n8fr8** [comment]
Maybe the version of Zom I am using is out of date? I couldn't get past the first request.

Otherwise, yes, it does look like it is going through, but why does it keep saying "No such offer made"? Is that what happens after you complete a transfer - the offer is deleted on your side?

**Comment by n8fr8** [comment]
Otherwise, I will look into that behavior related to the backwards looping requests. I haven't seen that before.

Is there a recent ChatSecure up on testflight? Or maybe I can have @N-Pex do the Zom build and put it up there for debugging.

**Comment by n8fr8** [comment]
So I think the production Zom release must have a bug that your code doesn't, because this is consistently the OFFER headers I receive from iOS on Android when I send audio:

01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: incoming OFFER otr-in-band:/storage/B69AEBC7-422F-4A60-8B77-28E605852615/8AFDD49E-2110-40BD-9842-952DB59F16B1.m4a
01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: incoming header: File-Name=8AFDD49E-2110-40BD-9842-952DB59F16B1.m4a
01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: incoming header: Mime-Type=audio/x-m4a
01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: incoming header: File-Length=0
01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: incoming header: Request-Id=325ACF91-3EEA-4B97-ACC9-078109F46D75
01-27 23:33:37.319 12748-21480/org.awesomeapp.messenger.debug D/OTRDATA: send response File-Hash-SHA1 must be supplied for 325ACF91-3EEA-4B97-ACC9-078109F46D75

**Comment by davidchiles** [comment]
I think I figured it out!
In https://github.com/zom/Zom-iOS/blob/master/Zom/Zom/Info.plist is missing [this](https://github.com/ChatSecure/ChatSecure-iOS/blob/develop/ChatSecure/Info.plist#L45).
@N-Pex So you need to add `NSAppTransportSecurity` and allow arbitrary loads from `localhost`

**Comment by n8fr8** [comment]
tested and fixed!
