### ISSUE TITLE
Replace onboarding graphics with iOS version

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#71]
Our current onboarding graphic has an Android-style phone in it, which Apple doesn't like. We've created a new graphic here for us in the app:
https://github.com/zom/Zom-Assets/blob/master/designdocs/onboarding/originals/ZomiOS_Onboarding_Art-01-1024x768.png

We may also need new screenshots generated for all sizes unfortunately, since our current app store screenshots include a picture of that screen, as well.

**Comment by N-Pex** [comment]
[iOS Onboarding Welcome.zip](https://github.com/zom/Zom-iOS/files/113575/iOS.Onboarding.Welcome.zip)

@n8fr8 I did not have write permission in Zom-Assets, but here's the updated screen.
