### ISSUE TITLE
Push notification "from" disappears

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-iOS#81]
The push notifications are generally working great, but after I get a few, then it starts not showing the "from" name in the notification. It just says "wants to chat with you" without a name.

**Comment by chrisballinger** [comment]
It might be because we clear out used push tokens on the receiving end but the other client keeps using them instead of the other stored tokens. Are you sending from iOS or android

**Comment by n8fr8** [comment]
Sending from Android. Are tokens meant to be single use? How many tokens do we have stored generally?

**Comment by davidchiles** [comment]
We weren't able to produce this. We did find that notifications didn't seem to go through until after the first launch of the device is turned on. We think this is due to using 'content-available' flag on our pushes.

Do you have the HTTP request of the failing pushes?

**Comment by n8fr8** [comment]
I will try to capture it next time.

I also noticed something else which is with the background xmpp/otr sessions, the delivered flag isn't sent until you open the app. The messages do get received, but you just don't get the receipt back until tap the notification or open the app.

**Comment by n8fr8** [comment]
i haven't seen this again, so will close for now.
