### ISSUE TITLE
Accepting/rejecting a user 

### ISSUE THREAD

**Issue by jodiejones** [zom/Zom-iOS#87]
A consistent piece of feedback is that the accept/reject box that appears in the top lefthand of the Zom header once a user clicks on your share link is confusing for users. Tenchoe has flagged this before on calls. Instead of that box, a notification that pops up with an accept or reject option will be much more user-friendly.

**Comment by n8fr8** [comment]
Notifications are tricky on iOS, and don't work the same way as they do on Android. I think the answer for Zom is to automatically accept people, and then make the delete/block option easy. That way you don't have to go into that box at all for most cases.
