### ISSUE TITLE
zom.im iOS 9 trusted URL handler

### ISSUE THREAD

**Issue by chrisballinger** [zom/Zom-iOS#9]
http://blog.hokolinks.com/how-to-implement-apple-universal-links-on-ios-9/

@n8fr8 We need this on zom.im and a fallback to another URL scheme like `zom://`

- [x] Support to handle these links in app
- [x] **blocking** on server-side support for trusted links on zom.im
- [ ] Add zom.im to associated domains in app and for AppID on Apple site

**Comment by chrisballinger** [comment]
@n8fr8 we are blocking on this for server side. where is the repo for the zom.im site? can we just use zom.github.io GitHub Pages account and submit pull requests there? We can use Cloudflare to point https://zom.im at a GitHub Pages account and keep full TLS.

it'll need a little javascript to parse the JID/etc from the base64 anchor, and detect which URL schemes to show to the user to click through to the app

* ios 8 `zom://
* ios 9 trusted link `https://zom.im`
* android non-trusted link
* android trusted link

**Comment by n8fr8** [comment]
Got it. I will get that setup.

**Comment by chrisballinger** [comment]
https://github.com/zom/zom.github.io/issues/1

**Comment by N-Pex** [comment]
Did the implementation, but still need to add zom.im to "Associated Domains" in the app. This must be made by the account (or a team member of the account) that owns the app with app id im.zom.zom. Also, for this app id, the "Associated domains" feature need to be enabled for the app on the Apple dev site.

**Comment by n8fr8** [comment]
@N-Pex the app id is updated on the site... it might take a few minutes for the website to update properly.

**Comment by N-Pex** [comment]
Ok, yes, I get a 404 at the moment.

**Comment by n8fr8** [comment]
Strange. This is the URL I have up: https://zom.im/apple-app-site-association

It is definitely there. Is there some other path it should be at?

**Comment by N-Pex** [comment]
Sorry, yes, seems like my browser had an issue. Didn't get the invitation link to work yet though, but will investigate.

**Comment by N-Pex** [comment]
@n8fr8 Oh, I think we are missing a "," after the "appID" value in this file, to make it valid JSON.

**Comment by n8fr8** [comment]
okay fixed and pushed... again, not sure how long it will take to update all the caches

**Comment by N-Pex** [comment]
Cool, seems to work now!
