### ISSUE TITLE
Chat between iOS devices

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#91]
TL and I were able to add each other via QR Scan (Link invite took TL to Website download page).
Zom didn't crash when I clicked on the Approve/Reject notification.

When we started chatting, TL was getting all the messages that I sent, but I wasn't receiving any of the messages that she was sending. The lock was open throughout and when we enabled encryption, nothing happened.

(FYI, I scanned TL's QR Code)

**Comment by n8fr8** [comment]
What version of iOS / what device is TL using?

**Comment by n8fr8** [comment]
Also what app did TL use to receive the link?

**Comment by gekhung** [comment]
I am on iTouch 9.2 (I know I have to update ;) ) TL is on iPhone 6 version 8.4.1
TL received the link in Gmail,

**Comment by n8fr8** [comment]
Gmail doesn't yet support the app link handling, and just pushes it right into the browser. If you send via iMessage, SMS or other app, it should work.

**Comment by n8fr8** [comment]
(that said, the website should handle this situation better and show the xmpp://foo@foo.com link that will then open in Zom)

**Comment by n8fr8** [comment]
This is fixed now, at least in my testing between iPad and iPod with the new account approval process
