### ISSUE TITLE
QR Scan doesn't work between Zom Android and iOS

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#93]
I tried scanning QR code between Zom on Android and iOS devices and it doesn't work. (It worked between iOS devices)

**Comment by n8fr8** [comment]
Can you be more specific? What does or does not happen?

**Comment by gekhung** [comment]
When I tested, I scanned from iOS device and nothing happened. So I shared the link to my gmail instead to add the android device. I deleted the accounts from friend list and tried both ways again, and it worked. This time, after I scanned from iOS device, message was going through both ways. Msg didn't go through when I scanned from Android device and started chat.

**Comment by n8fr8** [comment]
Were the contacts added to the contact list? Let's not jump to messages going through. Scanning QR code is just initiating the link between accounts.

**Comment by gekhung** [comment]
Yes, contacts were added to the contact list.

**Comment by n8fr8** [comment]
From that it seems like the QR code scanning / contact adding is working, and there error is related to sending messages which is a separate area of code.

**Comment by gekhung** [comment]
Yes, it worked between my Android and iOS device, but it didn't work both when KW and TL tried as well as when KW and I tried.

**Comment by n8fr8** [comment]
Okay. Let's just try to keep the qr scanning / contacting adding bug reports separate from messaging sending / receiving bugs. Otherwise... looking into it!

**Comment by n8fr8** [comment]
Okay I have reproduced this step by step:

1) Create a new account on iOS
2) Scan the QR codes between iOS and Android to add contacts
3) Approve the contact on iOS in the notifications inbox
4) Start a chat

Problems: OTR Chat will never start, messages are received from iOS to Android, but nothing is received by iOS

Solution: if you swipe/kill the iOS app, and then re-open/start it, everything will work just fine. OTR starts right up, and messages flow both ways.

SO, this is some sort of first time / onboarding, something is not initialized right bug.

**Comment by gekhung** [comment]
Tried between iOS and Android.
User 1: 1Plus OS version 5.1.1
User 2: iTouch OS 9.3.1

Both users created fresh accounts for this testing:

User 2 (iOS) scannned User 1's (Android) QR code. Nothing happened.
User 1 (Android) scanned User 2's QR code. User 2 appeared in User 1's friend list, but user 2 didn't get verification notification and couldn't establish a chat.

**Comment by n8fr8** [comment]
I think this doesn't have anything to do with QR codes, and more related to other tickets involving notifications about new friends being added. Let's close this ticket.
