### ISSUE TITLE
Stickers - Are they actually send in the chat or just the code is being send?

### ISSUE THREAD

**Issue by dhongmar** [zom/Zom-iOS#94]
Are stickers send or are they inbuilt so that it doesn't need to be send. Using Android to Android, I don't see any issues of stickers taking time but when I send it from IOS to android, it shows the sending bar and takes a while to get send.

**Comment by n8fr8** [comment]
stickers are currently sent as files. what you are seeing on iOS is that they are actually showing the transfer, while on Android we hide that from the user.

We can support using sticker shortcodes on Android as well, but iOS doesn't have that yet.
