### ISSUE TITLE
Starting chat between Zom on iOS

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-iOS#99]
User 1: iPhone 6 OS version 8.3
User 2: iTouch 5 OS version 9.3.1

Users added by scanning QR Code

Once User 1 and 2 are able to add each other, when User 2 sent msgs in chat, User 1 was getting them, but User 2 wasn't getting msgs from User 1.

**Comment by n8fr8** [comment]
Let's close this since we have more detail now
